Zapper-fi/studio

- README.md
Added "1.1" to the BSL license statement in the readme.
> docs: add BSL license version to the readme

- README.md
> docs: update contribution guide link in readme

- .github/workflows/release.yml
Release workflow was not running the `pnpm build` script.
Run a release
> build: Run build on release

- .github/workflows/publish.yml
- .github/workflows/release.yml
Build should be in publish step.
After merge of release branch, the publish step will run and _build_ the library as well.
> build: Move build step to publish step

- .github/workflows/release-please.yml
Adds a self managed action for release on every commit on `main`
> ci: Add release please action

- .github/workflows/release-please.yml
Duplicate name field in the github action
> ci: Duplicate name in release-please action

- .github/workflows/release-please.yml
> ci: Fix duplicate branch field

- .github/workflows/release-please.yml
YAML engineering -- it's a way of life
> ci: Rugged again by depcrated GH action

- src/apps/tokemak/ethereum/tokemak.tvl-fetcher.ts
- src/apps/tokemak/tokemak.module.ts
Added a tvl fetcher for tokemak.
> feat: add tokemak tvl fetcher

- src/apps/olympus/olympus.module.ts
Wrong module definition
`yarn dev`
> fix: Fix Olympus module not loading

- src/apps/olympus/ethereum/olympus.s-ohm-v1.token-fetcher.ts
- src/apps/olympus/ethereum/olympus.s-ohm.token-fetcher.ts
- src/apps/olympus/olympus.module.ts
Remove circular dependencies from copy-pasta in Olympus
`yarn dev` with `ENABLED_APPS` including `olympus`. http://localhost:5001/apps/olympus/tokens?groupIds[]=g-ohm&network=arbitrum resolves successfully without a circular dependency crashing the app with a heap explosion.
> fix: Resolve circular dependencies in Olympus

- .env.sample
- README.md
> chore: add .env.sample file

- src/apps/curve/arbitrum/curve.balance-fetcher.ts
- src/apps/curve/arbitrum/curve.farm.contract-position-fetcher.ts
- src/apps/curve/avalanche/curve.balance-fetcher.ts
- src/apps/curve/avalanche/curve.farm.contract-position-fetcher.ts
- src/apps/curve/ethereum/curve.balance-fetcher.ts
- src/apps/curve/ethereum/curve.farm.contract-position-fetcher.ts
- src/apps/curve/fantom/curve.balance-fetcher.ts
- src/apps/curve/fantom/curve.farm.contract-position-fetcher.ts
- src/apps/curve/gnosis/curve.balance-fetcher.ts
- src/apps/curve/gnosis/curve.farm.contract-position-fetcher.ts
- src/apps/curve/harmony/curve.balance-fetcher.ts
- src/apps/curve/harmony/curve.farm.contract-position-fetcher.ts
- src/apps/curve/helpers/curve.pool.token-helper.ts
- src/apps/curve/helpers/curve.v1-pool.token-helper.ts
- src/apps/curve/helpers/curve.v2-pool.token-helper.ts
- src/apps/curve/optimism/curve.balance-fetcher.ts
- src/apps/curve/optimism/curve.farm.contract-position-fetcher.ts
- src/apps/curve/polygon/curve.balance-fetcher.ts
- src/apps/curve/polygon/curve.farm.contract-position-fetcher.ts
All references to global helpers should be using the app toolkit.
> fix(curve): Replace helper references for app toolkit

- .all-contributorsrc
- README.md
Add @zeJabun and @brightiron in our contributor list! 🔥
> docs(README): Update contributors

- src/apps/wban/helpers/wban.farm.contract-position-fetcher-helper.ts
Changes rewards to be per second, instead of per block.
> fix: fix rewards to be per second and not per block

- src/cache/cache-on-interval.service.ts
> fix: init cache earlier to prevent infinite loop

- scripts/codemod/update-api-imports.js
> chore: add some codemods

- src/apps/airswap/airswap.definition.ts
- src/apps/airswap/ethereum/airswap.s-ast.token-fetcher.ts
> feat(airswap): Fix linting in Airswap

- CHANGELOG.md
> chore: re-format changelog to match release-please spec

- src/apps/illuvium/illuvium.module.ts
`AbstractDynamicApp` was renamed to `AbstractApp`. Resolve the issue in Illuvium.
Build succeeds.
> fix: Resolve conflict in rename of AbstractApp

- src/apps/lido/ethereum/lido.steth.token-fetcher.ts
- src/apps/lido/ethereum/lido.wsteth.token-fetcher.ts
- src/apps/lido/lido.module.ts
Few linting errors and a merge conflict preventing build
Build succeeds.
> fix: Lido merge conflicts and linting

- src/app/app.definition.ts
- src/app/app.interface.ts
Class needs to pass through the links.
Links are exposed properly in `/v2/apps` route in Zapper API.
> fix: Update AppDefinition class with links

- src/app-toolkit/helpers/position/single-vault.token-helper.ts
Single vault fetcher wasn't computing reserve properly (double dividing by 10 ** 18)
[xJOE Price](http://localhost:5001/apps/trader-joe/tokens?groupIds[]=x-joe&network=avalanche)
> fix(trader-joe): Fix xJOE price

- src/app-toolkit/helpers/the-graph/the-graph.helper.ts
- src/apps/trader-joe/avalanche/trader-joe.tvl-fetcher.ts
- src/apps/uniswap-v2/ethereum/uniswap-v2.tvl-fetcher.ts
- src/apps/uniswap-v2/helpers/uniswap-v2.the-graph.tvl-helper.ts
- src/apps/uniswap-v2/uniswap-v2.module.ts
- Adds Uniswap V2 TVL helper for Uni V2 forks
- Adds Uniswap V2 TVL
http://localhost:5001/apps/trader-joe/tvl?network=avalanche
http://localhost:5001/apps/uniswap-v2/tvl
> feat: Uniswap V2 TVL helper

- cli/commands/create-app.ts
> chore: update create app to include links in def

- cli/commands/create-app.ts
> chore: fix typo in codegen

- studio.bat
> chore: add windows equivalent for studio.sh

- src/apps/airswap/ethereum/airswap.balance-fetcher.ts
Merged in changes from AirSwap PR too early.. oops.
[Will work correctly](https://zapper.fi/account/0x8592b46b16ba66ab8115e0c154f5760d1c4f1ba1)
> fix: AirSwap sAST V3 balances

- .github/workflows/ci.yml
- .github/workflows/semantic-pr.yml
Zapper Police didn't seem to run on forks
> ci(police): Make CI work on forks

- src/apps/pool-together/avalanche/pool-together.balance-fetcher.ts
- src/apps/pool-together/avalanche/pool-together.tvl-fetcher.ts
- src/apps/pool-together/celo/pool-together.tvl-fetcher.ts
- src/apps/pool-together/ethereum/pool-together.balance-fetcher.ts
- src/apps/pool-together/ethereum/pool-together.tvl-fetcher.ts
- src/apps/pool-together/helpers/pool-together-v3.prize-pool.token-helper.ts
- src/apps/pool-together/helpers/pool-together.api.prize-pool-registry.ts
- src/apps/pool-together/polygon/pool-together.tvl-fetcher.ts
- src/apps/pool-together/pool-together.module.ts
- src/cache/cache-on-interval.service.ts
- src/cache/cache.service.ts
Load was loading the caching files, and not priming the cache l0l
> fix(caching): No need to load the cache on start

- .all-contributorsrc
- README.md
@dylandesrosier @dylandesrosiers now kith
> docs(README): Wrong Dylan LOL

- README.md
- cli/commands/codegen-app.ts
- cli/commands/create-app.ts
- cli/commands/index.ts
- cli/commands/set-network-provider.ts
- src/network-provider/network-provider.service.ts
> feat(cli): Add the ability to set custom network providers

- src/apps/balancer-v1/index.ts
- src/apps/balancer-v2/balancer-v2.module.ts
- src/apps/balancer-v2/index.ts
So that consuming the balancer app is easier in zapper api
> fix(balancer): Add index files for Zapper API

- src/apps/balancer-v2/balancer-v2.module.ts
> fix(balancer): Forgot to add export in module - it's Friday

- src/apps/balancer-v2/index.ts
> fix(balancer): Also export the app module

- src/apps/balancer-v2/helpers/balancer-v2.spot-price.helper.ts
To avoid typing mismatches in Zapper API
> fix(balancer): Helpers should not accept multicall, resolve internally

- src/apps/balancer-v2/balancer-v2.module.ts
> fix(balancer): Export contract factory

- README.md
> chore: update readme to include links to openapi docs

- src/apps/olympus/ethereum/olympus.g-ohm.token-fetcher.ts
Olympus gOHM fetcher was being registered as a contract position fetcher.
gOHM price resolves correctly on prod.
> fix: Fix Olympus gOHM price

- src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
> fix: add missing mirror pools to uniswap pool token fetcher

- cli/commands/codegen-app.ts
- cli/commands/create-app.ts
- Descriptive error when codegen is ran with an invalid appId
- Mandatory supported network
- Supports mandatory tags
> fix(cli): Smol CLI improvements

- cli/commands/create-app.ts
- src/app/app.definition.ts
- src/apps/abracadabra/abracadabra.definition.ts
- src/apps/aelin/aelin.definition.ts
- src/apps/airswap/airswap.definition.ts
- src/apps/alpha-v1/alpha-v1.definition.ts
- src/apps/balancer-v1/balancer-v1.definition.ts
- src/apps/balancer-v2/balancer-v2.definition.ts
- src/apps/banano/banano.definition.ts
- src/apps/curve/curve.definition.ts
- src/apps/enzyme-finance/enzyme-finance.definition.ts
- src/apps/illuvium/illuvium.definition.ts
- src/apps/jpegd/jpegd.definition.ts
- src/apps/keeper-dao/keeper-dao.definition.ts
- src/apps/lido/lido.definition.ts
- src/apps/liquity/liquity.definition.ts
- src/apps/naos/naos.definition.ts
- src/apps/olympus/olympus.definition.ts
- src/apps/pancakeswap/pancakeswap.definition.ts
- src/apps/pickle/pickle.definition.ts
- src/apps/pie-dao/pie-dao.definition.ts
- src/apps/pool-together/pool-together.definition.ts
- src/apps/synthetix/synthetix.definition.ts
- src/apps/teddy-cash/teddy-cash.definition.ts
- src/apps/tokemak/tokemak.definition.ts
- src/apps/trader-joe/trader-joe.definition.ts
- src/apps/unagii/unagii.definition.ts
- src/apps/uniswap-v2/uniswap-v2.definition.ts
- src/apps/yearn/yearn.definition.ts
Infer app definition group keys (strongly typed) using the `appDefinition` helper function to infer the type.
> fix: Infer definition group keys using helper function

- src/apps/dfx/dfx.definition.ts
Small fixes to keep up with changes in AppDefinition imports.
Builds successfully.
> fix: Fix app definition helper in DFX, use correct imports for AppTag and AppAction

- src/apps/maker/ethereum/maker.balance-fetcher.ts
- src/apps/maker/ethereum/maker.vault.contract-position-fetcher.ts
Wasn't up to date with `main`.
Build succeeds.
> fix: Fix paths in Maker

- src/apps/maker/ethereum/maker.governance.contract-position-fetcher.ts
> fix: Fix another Maker path

- src/app/app.interface.ts
> fix: add back deprecated tags until we finish removal in api

- src/app/app.interface.ts
> fix: remove legacy tags after all

- src/apps/maker/ethereum/maker.balance-fetcher.ts
Account can have multiple CDPs open. Iterate over all available CDPs for the user.
`0xEe3372cd30cB1207B1ADAc09962025CEb4855521`
> fix(maker): Fix missing CDPs

- src/apps/beethoven-x/index.ts
- src/apps/qi-dao/index.ts
Beethoveen-X and Qi-Dao are missing the index file
N/A
> feat: Add index file to Qi-Dao and Beethoven-X

- src/apps/curve/ethereum/curve.pool.token-fetcher.ts
> chore(lint): Fix linting

- src/balance/balance.service.ts
Balance fetcher errors were being swallowed up. Log them to the console output and return the error as part of the response as well.
Throw an error in a balance fetcher (was discovered on and tested with #375)
> fix(balances): Log an error and return the error message on failed balance fetcher invocation

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- .github/workflows/upload-app-assets.yml
- .npmrc
- .nvmrc
- package.json
- pnpm-lock.yaml
> chore(node): Bump Node to 16 LTS

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- pnpm-lock.yaml
Uses the recommended version for node 16
> chore(pnpm): Bump pnpm to 7

- src/apps/apps.module.ts
There's a growing number of apps in Studio. In order to keep the project snappy for newcomers, do not allow the application to start if there are no applications enabled.
`yarn dev`
> fix(main): Log and exit when no apps are configured in the .env file

- src/apps/curve/helpers/curve.gauge-v2.reward-token-strategy.ts
Revert an unwanted change in Curve helper
> fix(curve): Fix Generic type in helper

- src/apps/trader-joe/avalanche/trader-joe.tvl-fetcher.ts
- src/balance/dto/get-balances-query.dto.ts
`addresses` query parameter follows square bracket array notation, like `?addresses[]=0x...`
`localhost:5000/docs`
> fix(swagger): Fix addresses query parameter in Swagger

- src/app-toolkit/helpers/position/vault.token-helper.ts
Add contract to parameters in `resolveReserve` for `VaultTokenHelper`.
Tested in Zapper API.
> fix(helpers): Add contract to parameters of resolveReserve for VaultTokenHelper

- package.json
Too strict, Zapper API is complaining.
> fix(dependencies): Relax peer dependency on Dataloader

- src/apps/thales/index.ts
- src/apps/thales/optimism/thales.balance-fetcher.ts
- src/apps/thales/thales.definition.ts
- src/apps/thales/thales.module.ts
Linting, index file, remove unsupported networks in definition, align labels.
> fix(thales): Fix linting and add index

- src/apps/abracadabra/ethereum/abracadabra.cauldron.contract-position-fetcher.ts
Added support for Stargate Cauldrons
Stargate USDC: 0x11039cf7f6413bc0ca4a62c8a043ef825ad91847
Stargate USDT: 0xc47fae56f3702737b69ed615950c01217ec5c7c8
> feat(Abracadabra): Added support for Stargate Cauldrons

- src/apps/curve/polygon/curve.balance-fetcher.ts
- src/apps/curve/polygon/curve.farm.contract-position-fetcher.ts
Same as the previous commits. We're supporting the Curve migration as described [here](https://gov.curve.fi/t/sidechain-gauge-upgrade-and-migration/3869).
Tested with https://polygonscan.com/address/0x0d423b6d81deedf22bd3d4f582232897f2862373
https://polygon.curve.fi/pools?see=0x0d423b6d81deedf22bd3d4f582232897f2862373
http://localhost:5001/apps/curve/balances?addresses[]=0x0d423b6d81deedf22bd3d4f582232897f2862373&network=polygon
> feat(curve): Update Polygon sidechain gauges

- src/apps/curve/fantom/curve.balance-fetcher.ts
- src/apps/curve/fantom/curve.farm.contract-position-fetcher.ts
Same as the previous commits. We're supporting the Curve migration as described [here](https://gov.curve.fi/t/sidechain-gauge-upgrade-and-migration/3869).
Tested with 0xa2581a5c24a534394629affb06be36b039f2ef29
http://localhost:5001/apps/curve/balances?addresses[]=0xa2581a5c24a534394629affb06be36b039f2ef29&network=fantom
https://ftm.curve.fi/pools?see=0xa2581a5c24a534394629affb06be36b039f2ef29
> feat(curve): Update Curve Fantom liquidity gauges

- src/apps/curve/gnosis/curve.balance-fetcher.ts
- src/apps/curve/gnosis/curve.farm.contract-position-fetcher.ts
More work for the [Curve sidechain/L2 gauge migration](https://gov.curve.fi/t/sidechain-gauge-upgrade-and-migration/3869/1). We are done after this, but we'll do a few more naming refactors as a follow-up.
0x9e04689ec4F4B6A8BdEe305Bcd0A93F8B908eA0d
> feat(curve): Support child liquidity gauges for Gnosis Curve

- src/apps/curve/harmony/curve.balance-fetcher.ts
- src/apps/curve/harmony/curve.farm.contract-position-fetcher.ts
- src/apps/curve/helpers/curve.child-liquidity-gauge.roi-strategy.ts
Use the child liquidity gauge factory to resolve child liquidity gauges.
> feat(curve): Support child liquidity gauges on Harmony

- src/apps/curve/ethereum/curve.farm.contract-position-fetcher.ts
Document the statically defined Curve gauges so we can refactor these clearly later to align better with Curve naming conventions.
N/A
> feat(curve): Document Curve gauge impls on Ethereum for future refactors

- src/apps/abracadabra/ethereum/abracadabra.cauldron.contract-position-fetcher.ts
- Added support for the yvstETH Concentrated Cauldron
- 0x42dac2ec3e4231a0d046e7ba6053519f9db20b7d
> feat: added support for yvstETH Concentrated

- src/apps/qi-dao/polygon/qi-dao.yield.token-fetcher.ts
Remove a duplicate yield present on qi-dao
> fix(qi-dao): Remove duplicate Yield

- src/apps/symphony/avalanche/symphony.balance-fetcher.ts
- src/apps/symphony/polygon/symphony.balance-fetcher.ts
This fixes the address total balance for a token.
If the user has multiple orders with the same token then now it will add all the deposited token amounts.
http://localhost:5001/apps/symphony/balances?addresses%5B%5D=0x0d8b207695f92c45d27be4d49bb7921e4059b113&network=polygon
> feat(symphony): Fix address balance

- .gitignore
- src/app-toolkit/constants/blocks.ts
- src/multicall/multicall.registry.ts
- src/network-provider/network-provider.registry.ts
- src/network-provider/network-provider.service.ts
- src/types/index.ts
- src/types/network.interface.ts
Support Aurora, Cronos, and Evmos.
Devs can now integrate Aurora, Cronos, and Evmos protocols in this repo.
> feat(network): Support Aurora, Cronos, and Evmos networks

- cli/commands/create-app.ts
- cli/generators/generate-app-index.ts
- src/apps/rari-fuse/index.ts
- src/apps/saddle/index.ts
Generate an index file when creating an app. Create missing indexes for Rari Fuse and Saddle.
> fix(codegen): Add indexes and generate on create app

- src/apps/plutus/arbitrum/plutus.balance-fetcher.ts
whoops
https://zapper.fi/account/0x4e190b3d31d96e0cd11a1520185a77b57a0182f2
> fix: display correct locked balance in plutus

- src/apps/balancer-v2/helpers/balancer-v2.pool.token-helper.ts
- src/apps/dfx/ethereum/dfx.curve.token-fetcher.ts
- src/apps/dfx/polygon/dfx.curve.token-fetcher.ts
- src/apps/pool-together/helpers/pool-together-v3.pod.token-helper.ts
- src/apps/pool-together/helpers/pool-together-v3.prize-pool.token-helper.ts
- src/apps/pool-together/helpers/pool-together-v4.prize-pool.token-helper.ts
- src/apps/sturdy/fantom/sturdy.lending.token-fetcher.ts
- src/apps/tarot/fantom/tarot.supply.token-fetcher.ts
- src/apps/tokemak/ethereum/tokemak.reactor.token-fetcher.ts
Stats item are gonna be pretty useful to have 😉
> feat: add more stats items

- src/app-toolkit/helpers/balance/contract-position-balance.helper.ts
- src/app-toolkit/helpers/balance/token-balance.helper.ts
- src/apps/rari-fuse/ethereum/rari-fuse.borrow.contract-position-balance-fetcher.ts
- src/apps/rari-fuse/ethereum/rari-fuse.supply.token-balance-fetcher.ts
- src/apps/rari-fuse/rari-fuse.module.ts
- Use Comptroller to get participated Fuse markets for borrow/supply positions
[http://localhost:5001/apps/rari-fuse/balances?addresses[]=0x9c5083dd4838e120dbeac44c052179692aa5dac5](http://localhost:5001/apps/rari-fuse/balances?addresses%5B%5D=0x9c5083dd4838e120dbeac44c052179692aa5dac5)
> Use Comptroller to optimize Rari Fuse

- .husky/pre-commit
- .lintstagedrc
- package.json
- pnpm-lock.yaml
Adds a pre-commit hook to run linting on staged files.
> build(lint): Add lint-staged as a pre-commit hook

- .eslintignore
- .eslintrc
- src/apps/market-xyz/avalanche/market-xyz.balance-fetcher.ts
- src/apps/market-xyz/fantom/market-xyz.balance-fetcher.ts
- src/apps/market-xyz/polygon/market-xyz.balance-fetcher.ts
- src/cache/cache-on-interval.service.ts
- src/main.ts
A big error source in Zapper API is misusing promises and floating promises, let's get rid of those from the get-go in Studio
> feat(ci): Enforce strict promise rules on linter

- src/apps/tempus/helpers/tempus.amm.token-helper.ts
whoops. i caught this one myself, not sure if the tempus team will find anything else.
> fix: tempus amm price

- src/apps/yearn/arbitrum/yearn.balance-fetcher.ts
- src/apps/yearn/arbitrum/yearn.vault.token-fetcher.ts
- src/apps/yearn/ethereum/yearn.balance-fetcher.ts
- src/apps/yearn/ethereum/yearn.farm.contract-position-fetcher.ts
- src/apps/yearn/ethereum/yearn.vault.token-fetcher.ts
- src/apps/yearn/ethereum/yearn.yield.token-fetcher.ts
- src/apps/yearn/fantom/yearn.balance-fetcher.ts
- src/apps/yearn/fantom/yearn.vault.token-fetcher.ts
> chore: Enabled Yearn TVL

- src/apps/aave-v2/helpers/aave-v2.lending.token-helper.ts
Regression from V2 balances was missing liquidation threshold and enabled as collateral data props. Add them in!
> feat(aave-v2): Add enabled as collateral and liquidation threshold data props

- src/apps/synthetix/ethereum/synthetix.synth.token-fetcher.ts
- src/apps/synthetix/helpers/synthetix.synth.token-helper.ts
> feat(synthetix): Make synths exchangeable

- src/apps/aave-v2/ethereum/aave-v2.supply.token-fetcher.ts
- src/apps/compound/ethereum/compound.supply.token-fetcher.ts
> feat(exchangeable-tokens): Turn off aave-v2 and compound tokens

- src/apps/bancor-v3/ethereum/bancor-v3.pool.token-fetcher.ts
> feat(bancor-v3): Include Pools data in tvl

- src/apps/beethoven-x/fantom/beethoven-x.farm.contract-position-fetcher.ts
Using the label resolver from the helper to make sure it does not contain `Staked`
> fix(beethoven-x): Update contrat position label

- src/apps/beethoven-x/fantom/beethoven-x.tvl-fetcher.ts
Update the tvl implementation
[http://localhost:5001/apps/beethoven-x/tvl?groupIds%5B%5D=farm&network=fantom](http://localhost:5001/apps/beethoven-x/tvl?groupIds%5B%5D=farm&network=fantom)
> feat(beethoven-x): Update TVL fetcher

- src/app-toolkit/helpers/master-chef/master-chef.contract-position-helper.ts
`x 100` the APR for the display value
> chore: Fix MasterChef helper APR display value

- src/apps/across/ethereum/across.pool.token-fetcher.ts
Fixed across label (removed Across prefix)
> fix: across label

- src/apps/maple/ethereum/maple.staked-bpt.token-fetcher.ts
- src/apps/sushiswap-bentobox/sushiswap-bentobox.definition.ts
- src/apps/unagii/ethereum/unagii.pool.token-fetcher.ts
- src/apps/yearn/ethereum/yearn.farm.contract-position-fetcher.ts
- src/apps/yearn/ethereum/yearn.yield.token-fetcher.ts
- src/apps/yearn/helpers/yearn.vault.token-helper.ts
- removed yearn farm and yield's position counting towards TVL
- Unagii cleanup
- fixed Maple staked balancer and sushiswap vault labels
> fix: Label fixes

- src/apps/compound/helper/compound.supply.token-helper.ts
- src/apps/iron-bank/avalanche/iron-bank.supply.token-fetcher.ts
- src/apps/iron-bank/ethereum/iron-bank.supply.token-fetcher.ts
- src/apps/iron-bank/fantom/iron-bank.supply.token-fetcher.ts
Remove the Borrow APY from the display section of the Supply position.
> fix(compound): Remove displayed borrow APY from supply position

- src/apps/compound/compound.definition.ts
Add presentation config to compound
> feat(compound): Add presentation config

- src/apps/aave-v2/aave-v2.definition.ts
Add presentation config to AAVE-V2
> feat(aave-v2): Add presentation config

- src/apps/synthetix/ethereum/synthetix.farm.contract-position-balance-fetcher.ts
- src/apps/synthetix/ethereum/synthetix.farm.contract-position-fetcher.ts
- src/apps/synthetix/ethereum/synthetix.mintr.contract-position-balance-fetcher.ts
- src/apps/synthetix/ethereum/synthetix.synth.token-balance-fetcher.ts
- src/apps/synthetix/ethereum/synthetix.synth.token-fetcher.ts
- src/apps/synthetix/ethereum/synthetix.transferable-snx.token-balance-fetcher.ts
- src/apps/synthetix/ethereum/synthetix.transferable-snx.token-fetcher.ts
- src/apps/synthetix/helpers/synthetix.synth.token-helper.ts
- src/apps/synthetix/optimism/synthetix.mintr.contract-position-balance-fetcher.ts
- src/apps/synthetix/optimism/synthetix.synth.token-balance-fetcher.ts
- src/apps/synthetix/optimism/synthetix.synth.token-fetcher.ts
- src/apps/synthetix/optimism/synthetix.transferable-snx.token-balance-fetcher.ts
- src/apps/synthetix/optimism/synthetix.transferable-snx.token-fetcher.ts
- src/apps/yearn/helpers/yearn.vault.token-helper.ts
- src/apps/yearn/yearn.definition.ts
- Removed suffix on yearn's vault
- Cleanup Synthetix's app
> fix: Removed suffix on yearn vaults

- src/apps/aave-v2/helpers/aave-v2.lending.token-helper.ts
- src/apps/compound/helper/compound.borrow.contract-position-helper.ts
Changing the Compound borrow helper and the AAVE-V2 lending helper to have the displayed liquidity not negated
> chore: Fix liquidity display value

- src/apps/yearn/ethereum/yearn.balance-fetcher.ts
- src/apps/yearn/yearn.definition.ts
> fix(yearn): Rename v1 vaults

- src/apps/coslend/helper/coslend.borrow.contract-position-helper.ts
> fix: add borrow liquidity to stats in coslend

- src/app/app.interface.ts
- src/apps/aave-v2/aave-v2.definition.ts
- src/apps/agave/agave.definition.ts
- src/apps/single/cronos/single.balance-fetcher.ts
- src/apps/single/cronos/single.lending.token-fetcher.ts
> feat(presentation): Add support for dropdown

- src/apps/dfx/ethereum/dfx.curve.token-fetcher.ts
- src/apps/dfx/ethereum/dfx.staking.contract-position-fetcher.ts
- src/apps/dfx/polygon/dfx.curve.token-fetcher.ts
- src/apps/dfx/polygon/dfx.staking.contract-position-fetcher.ts
- src/apps/euler/ethereum/euler.d-token.token-fetcher.ts
- src/apps/euler/ethereum/euler.e-token.token-fetcher.ts
- src/apps/llama-airforce/llama-airforce.definition.ts
- src/apps/solace/ethereum/solace.xslocker.contract-position-fetcher.ts
- src/apps/yearn/ethereum/yearn.governance.contract-position-fetcher.ts
> fix: Minor fixes

- src/apps/pancakeswap/binance/pancakeswap.syrup-cake.contract-position-fetcher.ts
- src/apps/pancakeswap/binance/pancakeswap.syrup-staking.contract-position-fetcher.ts
Update the syrup pools label to reflect the earned token.
> fix(pancakeswap): Update Syrup pools label

- src/apps/curve/helpers/curve.pool.token-helper.ts
> fix: remove curve label suffix in a non invasive manner

- src/apps/curve/helpers/curve.pool.token-helper.ts
> fix: revert rebindLabel on curve

- src/apps/pancakeswap/binance/pancakeswap.syrup-staking.contract-position-fetcher.ts
> feat(pancakeswap): Add missing ANTEX farm

- src/apps/aurigami/aurora/aurigami.supply.token-fetcher.ts
- src/apps/compound/helper/compound.borrow.contract-position-helper.ts
- Added logic preventing borrow liquidity to be greater than supply liquidity
- Cleaning up
> fix: borrow liquidity has to be lower then supply liquidity

- src/apps/curve/harmony/curve.pool.definitions.ts
> fix: remove curve suffix for harmony 3pool definition

- src/position/position.utils.ts
Narrow the type with a generic.
> fix(positions): Adjust signature on metatype helpers

- src/apps/rari-fuse/ethereum/rari-fuse.supply.token-fetcher.ts
Moved iFARM to an app token as part of clean-up.
> fix(rari-fuse): Add dependency to Harvest for iFARM

- src/app-toolkit/helpers/the-graph/the-graph.helper.ts
- src/apps/mean-finance/helpers/graph.ts
Adds a gqlFetchAll helper to the TheGraphHelper to fetch entire collections
Related docs PR: https://github.com/Zapper-fi/studio-docs/pull/22
http://localhost:5001/apps/mean-finance/positions?groupIds[]=dca-position&network=optimism
> Move gqlfetchall apptoolkit

- src/apps/euler/euler.definition.ts
Add presentation config to properly display lending related positions (Supply/Borrow) in the same UI section
> feat(euler): add presentation config

- src/apps/yearn/helpers/yearn.v1-vault.token-helper.ts
- src/apps/yearn/helpers/yearn.v2-vault.token-helper.ts
> fix(yearn): Fix vault displayed APY

- src/app-toolkit/app-toolkit.interface.ts
- src/app-toolkit/app-toolkit.module.ts
- src/app-toolkit/app-toolkit.service.ts
- src/app/app.api.ts
- src/app/app.module.ts
- src/app/app.registry.ts
- src/app/app.service.ts
- src/apps/curve/helpers/curve.pool.token-helper.ts
- src/apps/yearn/ethereum/yearn.yield.token-fetcher.ts
- src/apps/yearn/yearn.definition.ts
- src/balance/default.balance-presenter.factory.ts
- src/position/position.interface.ts
- src/stats/tvl/tvl.service.ts
- Remove Curve label overrides
- Instead, use the underlying labels, and prefix with the source app
- Remove `y` prefix in Yearn yield tokens
- Surface Yearn yield tokens in UI
- Add ability to retrieve app by ID with AppToolkit
> fix(curve): Adjust Curve labels, show Yearn yield tokens in explore

- src/apps/solace/aurora/solace.policies.contract-position-fetcher.ts
- src/apps/solace/ethereum/solace.bonds.contract-position-fetcher.ts
- src/apps/solace/ethereum/solace.policies.contract-position-fetcher.ts
- src/apps/solace/fantom/solace.policies.contract-position-fetcher.ts
- src/apps/solace/helpers/SolacePolicyBalanceHelper.ts
- src/apps/solace/polygon/solace.policies.contract-position-fetcher.ts
http://localhost:5001/apps/solace/positions?groupIds[]=policies&network=ethereum
http://localhost:5001/apps/solace/balances?addresses[]=0xfb5cAAe76af8D3CE730f3D62c6442744853d43Ef&network=ethereum
http://localhost:5001/apps/solace/positions?groupIds[]=policies&network=aurora
http://localhost:5001/apps/solace/balances?addresses[]=0x501AcE0e8D16B92236763E2dEd7aE3bc2DFfA276&network=aurora
http://localhost:5001/apps/solace/positions?groupIds[]=policies&network=polygon
http://localhost:5001/apps/solace/balances?addresses[]=0xF6DA0e773fa4095b8454E155A23446D8eBC068cF&network=polygon
http://localhost:5001/apps/solace/positions?groupIds[]=policies&network=fantom
http://localhost:5001/apps/solace/balances?addresses[]=0xa4C86a9706605611A6954A5F70fE9f8Afc5018ce&network=fantom
> fix: solace fix addresses and style

- src/apps/qi-dao/arbitrum/qi-dao.balance-fetcher.ts
- src/apps/qi-dao/arbitrum/qi-dao.vault.position-fetcher.ts
- src/apps/qi-dao/qi-dao.definition.ts
- src/apps/qi-dao/qi-dao.module.ts
- Add support for Arbitrum for Qi DAO (mai.finance)
This is a straightforward copy-paste of existing code, it should work as is!
> feat(qi-dao): add arbitrum support

- src/apps/maple/ethereum/maple.pool.token-fetcher.ts
- Filtered out maple pool positions without liquidity
> fix: filtered out maple pool positions without liquidity

- src/apps/pool-together-v3/celo/pool-together-v3.ticket-token-fetcher.ts
- src/apps/pool-together-v3/ethereum/pool-together-v3.pod-token-fetcher.ts
- src/apps/pool-together-v3/ethereum/pool-together-v3.ticket-token-fetcher.ts
- src/apps/pool-together-v3/polygon/pool-together-v3.ticket-token-fetcher.ts
- Disabled pool-together-v3's TVL
> fix: disabled pool-together-v3's TVL

- src/app-toolkit/app-toolkit.interface.ts
- src/app-toolkit/app-toolkit.service.ts
- src/app-toolkit/helpers/master-chef/master-chef.contract-position-helper.ts
- src/apps/lyra-avalon/optimism/lyra-avalon.options.contract-position-fetcher.ts
- src/position/position-key.service.ts
- src/position/position.module.ts
Add the position key builder, and add a unique key to all Lyra Avalon positions (these were complaining in Splunk). Also, add the unique key in the MasterChef position helper as well.
> fix(lyra-avalon): Add unique keys on Lyra Avalon positions and MasterChef positions

- src/apps/pool-together-v4/optimism/pool-together-v4.balance-fetcher.ts
- src/apps/pool-together-v4/optimism/pool-together-v4.ticket-token-fetcher.ts
- src/apps/pool-together-v4/pool-together-v4.definition.ts
- src/apps/pool-together-v4/pool-together-v4.module.ts
- Adds Optimism support for PoolTogether
`http://localhost:5001/apps/pool-together-v3/tokens?network=optimism&groupIds[]=ticket`
> Add Optimism support for PoolTogether

- src/apps/cronus-finance/cronus-finance.definition.ts
- src/apps/cronus-finance/evmos/cronus-finance.balance-fetcher.ts
- src/apps/cronus-finance/evmos/cronus-finance.farm.contract-position-fetcher.ts
- src/apps/cronus-finance/evmos/cronus-finance.pool.token-fetcher.ts
- src/apps/kinesis-labs/evmos/kinesis-labs.pool.token-fetcher.ts
- src/apps/market-xyz/avalanche/market-xyz.balance-fetcher.ts
- src/apps/market-xyz/fantom/market-xyz.balance-fetcher.ts
- src/apps/plutus/arbitrum/consts.ts
- src/apps/plutus/arbitrum/plutus.lock.contract-position-fetcher.ts
- src/apps/plutus/arbitrum/plutus.ve.token-fetcher.ts
- src/apps/plutus/plutus.definition.ts
- src/apps/polynomial/optimism/polynomial.balance-fetcher.ts
- src/apps/polynomial/polynomial.definition.ts
- src/apps/single/cronos/single.lyf.contract-position-fetcher.ts
- src/apps/single/single.definition.ts
- src/apps/trisolaris/aurora/trisolaris.balance-fetcher.ts
> chore(apps): cleanup bunch of apps

- src/apps/angle/ethereum/angle.perpetuals.contract-position-fetcher.ts
- src/apps/angle/ethereum/angle.santoken.token-fetcher.ts
- src/apps/angle/ethereum/angle.vaults.contract-position-fetcher.ts
- Use types properly to catch errors.
> fix(angle): Fix Angle images

- src/balance/balance.module.ts
- src/balance/default.token-balance-fetcher.factory.ts
Use the AppToolkit so we can override the implementations at runtime of Zapper API.
> fix(balance): Remove dependencies on Studio implementations of MulticallService and PositionService

- src/apps/atlendis-v1/atlendis-v1.definition.ts
- src/apps/atlendis-v1/polygon/atlendis-v1.balance-fetcher.ts
- src/balance/dto/get-balances-query.dto.ts
- API expects checksum address
- Amounts are returned in Wei, convert to underlying token decimals for drill balance
- Lowercase addresses in fetcher
- Change group name to "Lending"
- Lowercase addresses in controller to align with Zapper API
> fix(atlendis-v1): Fix decimals in balance, fix checksum address

- src/apps/rari-fuse/rari-fuse.definition.ts
> fix: use dropdown presentation for rari-fuse

- src/apps/bastion-protocol/bastion-protocol.definition.ts
> fix(bastion): Fix label typo

- src/apps/qi-dao/polygon/qi-dao.vault.contract-position-fetcher.ts
Adding missing vaults on Polygon
> feat(qi-dao): Add missing vaults on Polygon

- src/apps/curve/ethereum/curve.pool.definitions.ts
- Add missing non-factory pools: teth, spelleth, xautusd, euroc, 2pool, 4pool, fraxusdc
> feat(curve): Add missing Curve pools

- src/apps/argo-finance/cronos/argo-finance.balance-fetcher.ts
- src/apps/argo-finance/cronos/argo-finance.pledging.contract-position-fetcher.ts
Address from Argo Finance call was in checksum case; integration was broken when we lowercased all addresses.
> feat(argo-finance): Fix address lowercasing

- src/app-toolkit/helpers/the-graph/the-graph.helper.ts
- src/apps/ethereum/ethereum/ethereum.balance-fetcher.ts
- src/apps/mean-finance/graphql/getPairs.ts
- src/apps/mean-finance/graphql/getPositions.ts
- src/apps/mean-finance/graphql/getUserPositions.ts
- src/apps/mean-finance/helpers/tokens.ts
- src/apps/mean-finance/optimism/mean-finance.dca-position.contract-position-fetcher.ts
- src/apps/mean-finance/polygon/mean-finance.dca-position.contract-position-fetcher.ts
Changes contract position fetcher to fetch pairs instead of all user positions
http://localhost:5001/apps/mean-finance/positions?groupIds[]=dca-position&network=optimism
http://localhost:5001/apps/mean-finance/positions?groupIds[]=dca-position&network=polygon
> fix(mean-finance): fix mean-finance tvl view

- src/apps/balancer-v2/helpers/balancer-v2.the-graph.pool-token-address-strategy.ts
- src/apps/koyo/aurora/koyo.pool.token-fetcher.ts
Volume isn't working with this subgraph because of delay.
> feat(koyo): Fix response since volume isn't working

- src/apps/stargate/arbitrum/stargate.eth.token-fetcher.ts
- src/apps/stargate/ethereum/stargate.eth.token-fetcher.ts
- src/apps/stargate/optimism/stargate.eth.token-fetcher.ts
whoops
random address: https://zapper.fi/account/reply-with-your-ens.eth
> fix(stargate) - incorrect stargate eth price

- src/apps/stargate/arbitrum/stargate.ve.token-fetcher.ts
- src/apps/stargate/avalanche/stargate.ve.token-fetcher.ts
- src/apps/stargate/binance-smart-chain/stargate.ve.token-fetcher.ts
- src/apps/stargate/ethereum/stargate.ve.token-fetcher.ts
- src/apps/stargate/fantom/stargate.ve.token-fetcher.ts
- src/apps/stargate/optimism/stargate.ve.token-fetcher.ts
- src/apps/stargate/polygon/stargate.ve.token-fetcher.ts
same error as https://github.com/Zapper-fi/studio/pull/951
> fix: stargate - incorrect ve price

- src/apps/stargate/binance-smart-chain/stargate.pool.token-fetcher.ts
- Fixed Stargate Pools pricePerShare on BSC
> fix(stargate): fixed stargate pools pricePerShare on BSC

- src/app-toolkit/app-toolkit.interface.ts
- src/app-toolkit/app-toolkit.service.ts
- src/token/price-selector.service.ts
- src/token/token-price-selector.interface.ts
> fix(price-selector): Tweak interface a bit

- src/apps/uniswap-v2/helpers/uniswap-v2.on-chain.token-derivation-strategy.ts
- src/apps/uniswap-v2/helpers/uniswap-v2.pool.token-helper.ts
> feat(price-selector): Use prices selector for uni-v2 forks

- src/apps/balancer-v2/balancer-v2.module.ts
- src/apps/beethoven-x/beethoven-x.definition.ts
- src/apps/beethoven-x/beethoven-x.module.ts
- src/apps/beethoven-x/optimism/beethoven-x.balance-fetcher.ts
- src/apps/beethoven-x/optimism/beethoven-x.farm.contract-position-fetcher.ts
- src/apps/beethoven-x/optimism/beethoven-x.pool.token-fetcher.ts
Adding support for Optimism.
[To get pools positions](http://localhost:5001/apps/beethoven-x/tokens?groupIds%5B%5D=pool&network=optimism)
[To get staking positions](http://localhost:5001/apps/beethoven-x/positions?groupIds%5B%5D=farm&network=optimism)
> feat(beethoven-x): Add Optimism support

- src/apps/uniswap-v2/helpers/uniswap-v2.on-chain.token-derivation-strategy.ts
- src/apps/uniswap-v2/helpers/uniswap-v2.pool.token-helper.ts
Having `await` inside for loops is not as efficient for the event-loop
> fix(uniswap-v2): Tweak promise execution to improve DataLoader

- src/apps/meshswap/polygon/meshswap.supply.token-fetcher.ts
> fix(meshswap): fix exchangeRate decimals

- src/apps/compound/compound.module.ts
- src/apps/compound/ethereum/compound.balance-fetcher.ts
- src/apps/compound/ethereum/compound.claimable.contract-position-fetcher.ts
- src/apps/compound/helper/compound.claimable.balance-helper.ts
- src/apps/compound/helper/compound.claimable.contract-position-helper.ts
- src/apps/compound/index.ts
- src/token/price-selector.service.ts
> feat(compound): Extract claimable COMP as its own helper

- src/apps/curve/ethereum/curve.pool.token-fetcher.ts
> fix(curve): added badger dependency on curve pools

- src/apps/angle/angle.definition.ts
- src/apps/angle/angle.module.ts
- src/apps/angle/ethereum/angle.balance-fetcher.ts
- src/apps/angle/ethereum/angle.perpetuals.contract-position-fetcher.ts
- src/apps/angle/ethereum/angle.santoken.token-fetcher.ts
- src/apps/angle/ethereum/angle.vaults.contract-position-fetcher.ts
- src/apps/angle/ethereum/angle.veangle.contract-position-fetcher.ts
- src/apps/angle/helpers/angle.api.ts
- Fix angle's helper cache keys
> fix(angle): fixed angle's helper cache keys

- src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts
Refactor enzyme finance using appTokenTemplate
> chore(enzyme-finance): refactor enzyme using AppTokenTemplate

- src/apps/qi-dao/optimism/qi-dao.balance-fetcher.ts
- src/apps/qi-dao/optimism/qi-dao.vault.position-fetcher.ts
- src/apps/qi-dao/qi-dao.definition.ts
- src/apps/qi-dao/qi-dao.module.ts
Add support for QiDAO on Optimism.
This is a copy-paste of the Arbitrum config but with Optimism addresses.
> feat(qi-dao): add optimism support

- src/multicall/multicall.ethers.ts
- In production, we fire some useful events for capturing Multicall metrics before the `aggregate` call is fired.
- Enable a before hook so we can make use of this class in production
> feat(multicall): Enable a before hook for use in production

- src/multicall/multicall.ethers.ts
Add calls to parameters of before call hook
> feat(multicall): Add calls to parameters of before call hook

- src/position/template/app-token.template.position-fetcher.ts
> feat(template): Add get balances support to app tokens

- src/apps/sablier/ethereum/sablier.stream-legacy.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream.contract-position-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/contract-position.template.position-fetcher.ts
> feat(template): Add get balances support to contract positions

- src/apps/gmx/arbitrum/gmx.balance-fetcher.ts
- src/apps/gmx/arbitrum/gmx.option.contract-position-fetcher.ts
- src/apps/gmx/avalanche/gmx.balance-fetcher.ts
- src/apps/gmx/avalanche/gmx.option.contract-position-fetcher.ts
- src/apps/gmx/gmx.definition.ts
- src/apps/gmx/gmx.module.ts
- src/apps/gmx/helpers/gmx.option.balance-helper.ts
- src/apps/gmx/helpers/gmx.option.contract-position-helper.ts
- Add GMX short/long positions
> feat(gmx): added short/long positions

- src/apps/badger/badger.definition.ts
- src/apps/badger/badger.module.ts
- src/apps/badger/polygon/badger.claimable.contract-position-balance-fetcher.ts
- src/apps/badger/polygon/badger.claimable.contract-position-fetcher.ts
- src/apps/badger/polygon/badger.vault.token-fetcher.ts
> feat(badger): add badger on polygon

- src/apps/plutus/arbitrum/plutus.balance-fetcher.ts
- src/apps/plutus/arbitrum/plutus.lock.contract-position-fetcher.ts
- Add missing staking contract addresses (not always defined on the lock contracts)
- Off-by-one error for calculating epoch shares
> feat(plutus): Fix claimable amounts on lock contracts

- src/apps/hector-network/fantom/hector-network.bond.contract-position-fetcher.ts
- src/apps/hector-network/fantom/hector-network.stake-bond.contract-position-fetcher.ts
- src/apps/pickle/arbitrum/master-chef.template.contract-position-fetcher.ts
- src/apps/pickle/arbitrum/pickle.farm.contract-position-fetcher.ts
- src/apps/pickle/ethereum/pickle.farm.contract-position-fetcher.ts
- src/apps/pickle/polygon/pickle.farm.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream-legacy.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream.contract-position-fetcher.ts
- src/position/template/contract-position.template.position-fetcher.ts
- src/position/template/master-chef-v2.template.contract-position-fetcher.ts
- src/position/template/master-chef.template.contract-position-fetcher.ts
More migration towards more atomic method breakdown in position fetchers. Create a template that applies the same logic as the Master Chef position helper class.
> feat(master-chef): Create Master Chef contract position template

- src/apps/synthetix/helpers/synthetix.transferable-snx.token-helper.ts
Add missing exchangeable property on SNX app token.
> feat(synthetix): Add missing exchangeable property to SNX token

- src/apps/pickle/arbitrum/pickle.balance-fetcher.ts
- src/apps/pickle/arbitrum/pickle.jar.token-fetcher.ts
- src/apps/pickle/ethereum/pickle.balance-fetcher.ts
- src/apps/pickle/ethereum/pickle.jar.token-fetcher.ts
- src/apps/pickle/ethereum/pickle.single-staking.contract-position-fetcher.ts
- src/apps/pickle/ethereum/pickle.voting-escrow.contract-position-fetcher.ts
- src/apps/pickle/helpers/pickle.api.jar-registry.ts
- src/apps/pickle/polygon/pickle.balance-fetcher.ts
- src/apps/pickle/polygon/pickle.jar.token-fetcher.ts
- src/apps/tokemak/ethereum/tokemak.balance-fetcher.ts
- Use API registry because there are a few jars missing on the on chain implementation 
- Fix Tokemak and Pickle keys used for cache
> fix(pickle): Missing jars on polygon

- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/contract-position.template.position-fetcher.ts
> feat(template): Use token dependency resolution

- src/app-toolkit/helpers/balance/staked.token-helper.ts
- src/apps/aave-v2/helpers/aave-v2.claimable.contract-position-helper.ts
- src/apps/compound/helper/compound.claimable.contract-position-helper.ts
- src/apps/compound/helper/compound.supply.token-helper.ts
- src/apps/dopex/arbitrum/dopex.gohm-ssov.contract-position-fetcher.ts
- src/apps/dopex/helpers/dopex.ssov.contract-position-helper.ts
- src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts
- src/apps/gamma-strategies/ethereum/gamma-strategies.pool.token-fetcher.ts
- src/apps/iron-bank/ethereum/iron-bank.supply.token-fetcher.ts
- src/apps/looks-rare/ethereum/looks-rare.compounder.contract-position-fetcher.ts
- src/apps/market-xyz/avalanche/market-xyz.supply.token-fetcher.ts
- src/apps/market-xyz/fantom/market-xyz.supply.token-fetcher.ts
- src/apps/rari-fuse/ethereum/rari-fuse.supply.token-fetcher.ts
- src/apps/rari-fuse/helpers/rari-fuse.supply.token-helper.ts
- src/apps/sablier/ethereum/sablier.stream-legacy.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream.contract-position-fetcher.ts
- src/apps/trader-joe/avalanche/trader-joe.pool.token-fetcher.ts
- src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
- src/apps/uniswap-v2/helpers/uniswap-v2.on-chain.token-derivation-strategy.ts
- src/apps/uniswap-v2/helpers/uniswap-v2.pool.token-helper.ts
> feat(token-deps): Exclusively use `getTokenDependencySelector` as a selector

- src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
> feat(template): Add token loader as stage param

- src/apps/gmx/arbitrum/gmx.glp.token-fetcher.ts
- src/apps/gmx/avalanche/gmx.glp.token-fetcher.ts
- src/apps/gmx/helpers/gmx.glp.token-helper.ts
> fix(gmx): remove MIM from GLP index

- src/apps/polynomial/optimism/polynomial.balance-fetcher.ts
see https://github.com/Zapper-fi/studio/pull/1137#discussion_r944571796
pending txs can be found in https://optimistic.etherscan.io/address/0xa11451acd2fbdf4ae798f44c4227cab9517739d7 as Initiate Deposit/Withdrawal
> fix: polynomial - get correct range for deposit/withdrawal queue

- src/app-toolkit/app-toolkit.interface.ts
- src/app-toolkit/app-toolkit.service.ts
> feat(app-toolkit): Sunset other token selectors in favor of token deps

- src/apps/polynomial/optimism/polynomial.balance-fetcher.ts
based on https://github.com/Zapper-fi/studio/pull/1157. change there made a comment invalid. this pr makes it true again. alternatively, we can just delete the comment.
> fix: polynomial - fix incorrect comment

- src/position/template/app-token.template.position-fetcher.ts
> feat(apps): Add key to template fetcher

- src/apps/iron-bank/iron-bank.definition.ts
- src/apps/iron-bank/iron-bank.module.ts
- src/apps/iron-bank/optimism/iron-bank.balance-fetcher.ts
- src/apps/iron-bank/optimism/iron-bank.borrow.contract-position-fetcher.ts
- src/apps/iron-bank/optimism/iron-bank.supply.token-fetcher.ts
Added Optimism network for Iron Bank
- [v ] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
N/A
> feat: add optimism for iron bank

- src/token/selectors/token-price-selector.interface.ts
Add name property to BaseTokenPrice
> feat(token): add name property to BaseTokenPrice

- src/apps/badger/arbitrum/badger.claimable.contract-position-fetcher.ts
- src/apps/badger/arbitrum/badger.vault.token-fetcher.ts
- src/apps/badger/ethereum/badger.claimable.contract-position-fetcher.ts
- src/apps/badger/ethereum/badger.vault.token-fetcher.ts
- src/apps/badger/helpers/badger.claimable.contract-position-fetcher.ts
- src/apps/badger/helpers/badger.vault.token-fetcher.ts
- src/apps/badger/polygon/badger.claimable.contract-position-fetcher.ts
- src/apps/badger/polygon/badger.vault.token-fetcher.ts
Comparing symbol with address zzz
> feat(badger): Fix claimable DIGG amount

- src/apps/aave-amm/aave-amm.module.ts
- src/apps/aave-amm/ethereum/aave-amm.position-presenter.ts
- src/apps/aave-amm/helpers/aave-amm.lending.template.token-fetcher.ts
- src/balance/balance-presentation.service.ts
- src/position/position-presenter.registry.ts
- src/position/template/position-presenter.template.ts
> fix(aave-amm): Use template for everything

- src/apps/polynomial/helpers/formatters.ts
- src/apps/polynomial/optimism/polynomial.vaults.contract-position-fetcher.ts
- src/apps/polynomial/optimism/polynomial.vaults.token-fetcher.ts
susd denominated call vaults
see deposits to https://optimistic.etherscan.io/address/0xD01263Bb1C4B5ba7F2AFe90397212d84e74e1d0e
> fix: polynomial - add new call quote vault

- src/apps/robo-vault/avalanche/robo-vault.vault.token-fetcher.ts
- src/apps/robo-vault/common/robo-vault.api.client.ts
- src/apps/robo-vault/common/robo-vault.vault.token-fetcher.ts
- src/apps/robo-vault/contracts/abis/robo-vault.json
- src/apps/robo-vault/contracts/ethers/factories/RoboVault__factory.ts
- src/apps/robo-vault/fantom/robo-vault.vault.token-fetcher.ts
- src/apps/robo-vault/robo-vault.module.ts
> feat(robo-vault): Migrate to templates

- src/apps/tectonic/cronos/tectonic.balance-fetcher.ts
- src/apps/tectonic/tectonic.definition.ts
Update balance fetcher for https://github.com/Zapper-fi/studio/pull/1231
> fix(tectonic): update balance fetcher for xTONIC

- src/apps/geist/fantom/geist.incentives.contract-position-fetcher.ts
It legit never actually worked l0l
> fix(geist): Fix Geist incentives

- src/apps/stargate/ethereum/stargate.auction-locked.token-fetcher.ts
> fix(stargate): fix aaSTG pricePerShare

- src/token/selectors/token-price-selector.interface.ts
Add verified property to BaseTokenPrice
> feat(token): add verified property to BaseTokenPrice

- src/apps/aave-v2/avalanche/aave-v2.stable-debt.token-fetcher.ts
- src/apps/aave-v2/avalanche/aave-v2.supply.token-fetcher.ts
- src/apps/aave-v2/avalanche/aave-v2.variable-debt.token-fetcher.ts
- src/apps/aave-v2/ethereum/aave-v2.stable-debt.token-fetcher.ts
- src/apps/aave-v2/ethereum/aave-v2.supply.token-fetcher.ts
- src/apps/aave-v2/ethereum/aave-v2.variable-debt.token-fetcher.ts
- src/apps/aave-v2/polygon/aave-v2.stable-debt.token-fetcher.ts
- src/apps/aave-v2/polygon/aave-v2.supply.token-fetcher.ts
- src/apps/aave-v2/polygon/aave-v2.variable-debt.token-fetcher.ts
- src/apps/agave/gnosis/agave.deposit.token-fetcher.ts
- src/apps/agave/gnosis/agave.stable-borrow.token-fetcher.ts
- src/apps/agave/gnosis/agave.variable-borrow.token-fetcher.ts
- src/apps/geist/fantom/geist.stable-debt.token-fetcher.ts
- src/apps/geist/fantom/geist.supply.token-fetcher.ts
- src/apps/geist/fantom/geist.variable-debt.token-fetcher.ts
- src/apps/nereus-finance/avalanche/nereus-finance.stable-debt.token-fetcher.ts
- src/apps/nereus-finance/avalanche/nereus-finance.supply.token-fetcher.ts
- src/apps/nereus-finance/avalanche/nereus-finance.variable-debt.token-fetcher.ts
> fix(aave-forks): Fix tertiary labels using APY

- src/apps/beefy/common/beefy.vault-token-fetcher.ts
- Updated getPricePerShare function to use multicall
> fix(beefy): fix price per share

- src/apps/yearn/ethereum/yearn.v1-vault.token-fetcher.ts
- src/apps/yearn/ethereum/yearn.v2-vault.token-fetcher.ts
- Fix yearn APY (were off by 100x)
> fix(yearn): fix apy

- src/apps/plutus/arbitrum/plutus.lock.contract-position-fetcher.ts
Lock balances were broken because of NaN
> feat(plutus): Fix lock balances

- src/apps/pool-together-v4/common/pool-together-v4.log-provider.ts
> feat(pool-together-v4): Add 1 hour TTL for logs

- src/apps/pool-together-v4/common/pool-together-v4.log-provider.ts
> fix(pool-together-v4): Packer was unable to cache the logs

- src/balance/balance.service.ts
- src/balance/default.position-presenter.factory.ts
- src/position/position-fetcher.template-registry.ts
> feat(template): Add more features to template registry

- src/apps/morpho/ethereum/morpho.morpho-compound.contract-position-fetcher.ts
- src/apps/morpho/ethereum/morpho.position-presenter.ts
- Fix presenter throwing in Morpho
- Fix cETH underlying (morpho uses WETH underlying)
> feat(morpho): Fix presenter and cETH underlying

- src/position/position-fetcher.template-registry.ts
> feat(position-registry): Fix derp not registering contract positions

- src/apps/furucombo/polygon/furucombo.fund.token-fetcher.ts
Lowercasing broke the token fetcher. Take the opportunity to refactor it to use definitions instead of a member variable for the fund tokens.
> fix(furucombo): Fix broken token fetcher

- src/apps/pika-protocol-v3/optimism/pika-protocol-v3.balance-fetcher.ts
Corrects the logic responsible for calculating an address' vault position
> fix: updates vault position calculation logic

- src/apps/convex/common/convex.farm.contract-position-fetcher.ts
Optimize the Convex balance fetching by wrapping the supply calls for the CVX token.
> feat(convex): Optimize Convex balance fetching

- src/apps/arrakis/ethereum/arrakis.pool.token-fetcher.ts
- src/apps/arrakis/optimism/arrakis.pool.token-fetcher.ts
- src/apps/arrakis/polygon/arrakis.pool.token-fetcher.ts
> fix(arrakis): fix arrakis decorator

- src/apps/atlendis-v1/graphql/getPositions.ts
- src/apps/atlendis-v1/polygon/atlendis-v1.balance-fetcher.ts
Balances were failing 100% of the time, the Heroku subgraph was dead. Switch to using the TheGraph hosted service subgraph.
> feat(atlendis-v1): Fix balances by hitting TheGraph instead

- src/position/template/master-chef-v2.template.contract-position-fetcher.ts
Detect zero address for rewarder address when retrieving reward rates.
> fix(pickle): Fix Master Chef V2 position fetchers

- src/apps/morpho/ethereum/morpho.morpho-aave-v2.contract-position-fetcher.ts
- src/apps/morpho/ethereum/morpho.morpho-compound.contract-position-fetcher.ts
- src/apps/morpho/ethereum/morpho.position-presenter.ts
- src/apps/morpho/helpers/position-fetcher.common.ts
- The pct value was normalized to 1 instead of 100 for a percentage
- I have also added the matched value to stats items
> fix(morpho): fix Utilization Rate

- src/apps/redacted-cartel/redacted-cartel.definition.ts
Updates protocol metadata for Redacted 
Changes are only to data, not logic...Run associated UI
> feat: update redacted app definition

- src/position/template/contract-position.template.position-fetcher.ts
> fix(contract-position-template): Fix stat item liquidity for debt

- package.json
- pnpm-lock.yaml
- src/app-toolkit/decorators/index.ts
- src/app-toolkit/decorators/position-template.decorator.ts
- src/app-toolkit/decorators/presenter-template.decorator.ts
- src/apps/compound/ethereum/compound.borrow.contract-position-fetcher.ts
- src/apps/compound/ethereum/compound.claimable.contract-position-fetcher.ts
- src/apps/compound/ethereum/compound.position-presenter.ts
- src/apps/compound/ethereum/compound.supply.token-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/contract-position.template.position-fetcher.ts
- src/position/template/position-presenter.template.ts
- src/utils/stack.ts
> feat(template): Read attributes from template path

- src/apps/tarot/fantom/tarot.vault.token-fetcher.ts
> fix(tarot): Fix vault price per share

- src/apps/__tests__/app.fetchers.test.ts
> feat(tests): Add classname test

- src/apps/kwenta/optimism/kwenta.perp.contract-position-fetcher.ts
Add enriched display items for Kwenta perp positions:
- Funding Rate
- Side (LONG/SHORT)
- Size
- Notional Value
- PnL
- Last Price
- Liquidation Price
Test address: 0xcd1d321485f74d740988f691276971f01073103b
> feat(kwenta): enriched display item

- src/apps/concave/concave.definition.ts
- src/apps/concave/ethereum/concave.liquid-staking.contract-position-fetcher.ts
- Fix rewards balance (subtract original deposit to prevent double counting initial)
- Fix label and description
> fix(concave): Fix rewards balance, fix description and label

- src/apps/euler/common/euler.d-token.token-fetcher.ts
- src/apps/euler/common/euler.e-token.token-fetcher.ts
- src/apps/euler/ethereum/euler.e-token.token-fetcher.ts
- Fix Euler underlying balances
- Update pricePerShare using exchangeRate between eToken and underlying
> fix(euler): fix euler underlying balances + update pricePerShare using exchangeRate between eToken and underlying

- src/apps/curve/curve.module.ts
- src/apps/curve/helpers/curve.pool.virtual.price-strategy.ts
This calculation lands the 4pool price close to 0.1036, which is quite close to this recent transaction for removing liquidity [here](https://ftmscan.com/tx/0x03ae66f59848598a841c18d8723550c8b6c3a51b04a92855fda3572cfa040e93).
> fix(curve): Fix price resolution strategy to fix 4pool prices

- src/apps/stakefish/ethereum/stakefish.staking.contract-position-fetcher.ts
Delicious
CC @tonzgao FYI, old API route was broken.
> feat(stakefish): Fix stakefish balance

- src/app-toolkit/helpers/position/vault.token-helper.ts
- src/apps/aave-amm/helpers/aave-amm.lending.template.token-fetcher.ts
- src/apps/aave-v2/avalanche/aave-v2.stable-debt.token-fetcher.ts
- src/apps/aave-v2/helpers/aave-v2.lending.template.token-fetcher.ts
- src/apps/aave-v2/polygon/aave-v2.stable-debt.token-fetcher.ts
- src/apps/kwenta/optimism/kwenta.perp.contract-position-fetcher.ts
- src/apps/kyberswap-dmm/kyberswap-dmm.module.ts
- src/apps/mean-finance/optimism/mean-finance.balance-fetcher.ts
- src/apps/mean-finance/polygon/mean-finance.balance-fetcher.ts
- src/apps/pickle/common/pickle.api.jar-registry.ts
- src/apps/pickle/ethereum/pickle.voting-escrow.contract-position-fetcher.ts
- src/apps/pickle/optimism/pickle.masterchef-v2-farm.contract-position-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
> fix(aave-v2): Fix empty stable debt positions

- src/app-toolkit/helpers/position/single-staking-farm.contract-position-helper.ts
Fix APY/APR on single/dual reward farms (1inch)
> fix(1inch): Fix APY/APR on single/dual reward farms

- src/apps/velodrome/optimism/velodrome.voting-escrow.contract-position-fetcher.ts
Fix veVelodrome supplied and claimable token balances
> fix(velodrome): Fix supplied and claimable  token balances in the voting-escrow position

- src/apps/homora-v2/common/homora-v2.farm.contract-position-fetcher.ts
- src/apps/homora-v2/interfaces/interfaces.ts
Farm balances were not implemented, quick fix by copying over what we had in the internal repo.
> feat(homora-v2): Add missing farm balances

- src/apps/vendor-finance/arbitrum/vendor-finance.balance-fetcher.ts
> fix(vendor-finance): debt is getting added to networth instead of subtracting

- src/apps/velodrome/optimism/velodrome.voting-escrow.contract-position-fetcher.ts
> fix(velodrome): Revert a veVelo balances fix

- src/apps/yield-yak/avalanche/yield-yak.vault.token-fetcher.ts
> fix(yield-yak): fix pps

- src/apps/homora-v2/homora-v2.definition.ts
Lending positions have been removed in a recent PR
> chore(homora-v2): Removed unnecessary lending group

- src/apps/alpha-v1/ethereum/alpha-v1.lending.token-fetcher.ts
Migrate Alpha-v1 to template
(it also fixes fetching balances for lending token)
> chore(alpha-v1): Migrate to template

- src/apps/banano/banano.definition.ts
- src/apps/banano/banano.module.ts
- src/apps/banano/ethereum/banano.balance-fetcher.ts
- src/apps/banano/ethereum/banano.farm.contract-position-fetcher.ts
- src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
Added ETH network for Banano.
Request a position for a random wallet like `0x268c77bf6da19dc60c236667fe225338c95273df`?
> feat(banano): Banano on ETH

- src/apps/banano/banano.module.ts
- src/apps/banano/ethereum/banano.farm.contract-position-fetcher.ts
> chore(banano): Linting

- src/apps/art-gobblers/ethereum/art-gobblers.claimable.contract-position-fetcher.ts
- Fix metatype on claimable position
> fix(art-gobblers): Fix Art-Gobblers claimable metatype

- src/apps/maker/ethereum/maker.vault.contract-position-fetcher.ts
> fix(maker): Fix Maker's TIV

- src/apps/llamapay/common/llamapay.stream.api-client.ts
- src/apps/llamapay/ethereum/llamapay.balance-fetcher.ts
- src/apps/llamapay/llamapay.definition.ts
- Fix llamapay early return condition
- Added llamapay links
> fix(llamapay): Fix llamapay early return when address has no balance

- src/position/template/single-staking.template.contract-position-fetcher.ts
In many cases, the staked token is in another contract. Extract `getReserves` so it can be overridden.
> feat(apps): Extract getReserve call so it can be overridden

- src/apps/gearbox/gearbox.definition.ts
- Capitalize name 
- Add missing links
> chore(gearbox): Capitalize name and add links to Gearbox's app definition

- src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-fetcher.ts
- Remove duplicates from definitions
> fix(kyberswap-elastic): Remove duplicates from definitions

- src/apps/concentrator/concentrator.module.ts
> chore(concentrator): Linting

- src/balance/balance-presentation.service.ts
Remove left-over from previous refactor of the presenter service, which is not necessary.
> fix(presenter): Remove left-over from previous refactor of the presenter service

- src/balance/balance-presentation.service.ts
This will allow us to avoid doing `Foo as unknown as AppService` and rely on the type system correctly.
> fix(presenter): Use interface and DI concrete implementation

- src/apps/gearbox/ethereum/gearbox.lending.token-fetcher.ts
> fix(gearbox): Fix Gearbox liquidity

- src/apps/euler/common/euler.d-token.token-fetcher.ts
- src/apps/euler/common/euler.e-token.token-fetcher.ts
- src/apps/euler/common/euler.position-presenter.ts
- src/apps/euler/ethereum/euler.d-token.token-fetcher.ts
- src/apps/euler/ethereum/euler.e-token.token-fetcher.ts
- src/apps/euler/euler.module.ts
> fix(euler): Add position presenter

- src/app-toolkit/constants/blocks.ts
- Update ethereum number of block per day constant post merge
> fix(block-per-day): Update Ethereum number of block per day post merge

- src/apps/furucombo/polygon/furucombo.fund.token-fetcher.ts
- src/apps/good-ghosting/common/good-ghosting.game.games.api-source.ts
- src/apps/hedgefarm/avalanche/hedgefarm.alpha-one.token-fetcher.ts
- src/apps/maple/helpers/maple.cache-manager.ts
- src/apps/mm-finance/cronos/mm-finance.pool.cache-manager.ts
- src/apps/mycelium/helpers/mycelium.api.helper.ts
- src/apps/openleverage/helpers/openleverage-pool.apy-helper.ts
- src/apps/pancakeswap/binance-smart-chain/pancakeswap.pool.cache-manager.ts
- src/apps/pickle/common/pickle.api.jar-registry.ts
- src/apps/polygon-staking/ethereum/polygon-staking.deposit.contract-position-fetcher.ts
- src/apps/reaper/common/reaper.vault.cache-manager.ts
- src/apps/rhino-fi/common/rhino-fi.cache-manager.ts
- src/apps/tokemak/ethereum/tokemak.balance-fetcher.ts
- src/apps/trisolaris/aurora/trisolaris.pool.cache-manager.ts
- src/apps/unipilot/helpers/unipilot-vault.apy.helper.ts
- src/apps/vaporwave-finance/aurora/vaporwave-finance.vault.token-fetcher.ts
- src/apps/vvs-finance/cronos/vvs-finance.pool.cache-manager.ts
This is currently the default behaviour. Since we want to change the default, I want to be sure that the same behaviour is preserved. Then we can gradually switch it to true where necessary.
> chore(cache): Preserve old failOnMissingData behaviour

- src/apps/gmx/helpers/gmx.glp.token-helper.ts
> fix(gmx): Fix GLP price

- src/apps/kwenta/kwenta.definition.ts
- src/apps/kwenta/kwenta.module.ts
- src/apps/kwenta/optimism/kwenta.staking.contract-position-fetcher.ts
> chore(apps): Linting

- src/position/template/contract-position.template.position-fetcher.ts
There's a few cases that throw when there's a mismatch between the number of balances and the number of tokens.
> fix(contracts): Throw error on missing balances

- src/apps/angle/helpers/angle.api.ts
- src/apps/mux/arbitrum/mux.mlp.token-fetcher.ts
- src/apps/mux/avalanche/mux.mlp.token-fetcher.ts
- src/apps/mux/binance-smart-chain/mux.mlp.token-fetcher.ts
- src/apps/mux/fantom/mux.mlp.token-fetcher.ts
- src/apps/mux/helpers/mux.mlp.token-helper.ts
- src/apps/mux/mux.module.ts
- Cache underlying token addresses 
- Linting
- Fix Angle Key
> fix(mux): Cache underlying asset token response

- src/apps/insurace/helpers/index.ts
> fix(insurace): Add missing statsItems on positions

- src/apps/mahadao/ethereum/mahadao.balance-fetcher.ts
- src/apps/mahadao/ethereum/mahadao.locker.contract-position-fetcher.ts
- src/apps/mahadao/mahadao.definition.ts
- src/apps/mahadao/mahadao.module.ts
> chore(mahadao): Linting

- src/apps/maple/helpers/maple.cache-manager.ts
- Fix pool query (contractAddress -> id)
> fix(maple): Fix pool query

- src/apps/geist/fantom/geist.platform-fees.contract-position-fetcher.ts
I'm removing the duplicated geist claimable token since we are not able to identify which one it actually is when trying to rebuild the position. Since we map by key, we will always pick the value of the first claimable token since they have the same key.
> fix(geist): Fix duplicated claimable token

- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/contract-position.template.position-fetcher.ts
Small optimization, and makes debugging a bit easier too.
> fix(positions): Avoid generating the key in a loop

- src/position/template/contract-position.template.position-fetcher.ts
> chore(typo): Remove unused variable

- src/apps/arth/arth.module.ts
- src/apps/b-protocol/ethereum/b-protocol.compound-borrow.contract-position-fetcher.ts
- src/apps/balancer-v2/common/balancer-v2.claimable.contract-position-fetcher.ts
- src/apps/bend-dao/ethereum/bend-dao.variable-debt.token-fetcher.ts
- src/apps/chicken-bond/ethereum/chicken-bond.bond.contract-position-fetcher.ts
- src/apps/concave/ethereum/concave.liquid-staking.contract-position-fetcher.ts
- src/apps/euler/common/euler.d-token.token-fetcher.ts
- src/apps/euler/common/euler.e-token.token-fetcher.ts
- src/apps/good-ghosting/common/good-ghosting.game.contract-position-fetcher.ts
- src/apps/hedgefarm/avalanche/hedgefarm.types.ts
- src/apps/homora-v2/common/homora-v2.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/common/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/maker/ethereum/maker.vault.contract-position-fetcher.ts
- src/apps/mean-finance/mean-finance.module.ts
- src/apps/meshswap/polygon/meshswap.supply.token-fetcher.ts
- src/apps/polygon-staking/ethereum/polygon-staking.deposit.contract-position-fetcher.ts
- src/apps/qi-dao/common/qi-dao.vault.contract-position-fetcher.ts
- src/apps/rari-fuse/common/rari-fuse.borrow.contract-position-fetcher.ts
- src/apps/rari-fuse/common/rari-fuse.supply.token-fetcher.ts
- src/apps/ren/ethereum/ren.darknode.contract-position-fetcher.ts
- src/apps/rhino-fi/ethereum/rhino-fi.deposit.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream-legacy.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream.contract-position-fetcher.ts
- src/apps/unipilot/utils/helpers.ts
- src/apps/uniswap-v3/common/uniswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/wolf-game/ethereum/wolf-game.wool-pouch.contract-position-fetcher.ts
- src/apps/yield-protocol/common/yield-protocol.borrow.contract-position-fetcher.ts
- src/position/template/custom-contract-position.template.position-fetcher.ts
> fix(lint): Fix all linting errors

- src/apps/aurora-plus/aurora/aurora-plus.balance-fetcher.ts
- Filter out token with no claimables from balances
> fix(aurora-plus): Filter out tokens with no claimables

- src/apps/pika-protocol/optimism/pika-protocol.balance-fetcher.ts
Balances are not usually a fractional value.
> fix(pika-protocol): Remove fractional balance

- src/apps/mean-finance/arbitrum/mean-finance.balance-fetcher.ts
- src/apps/mean-finance/optimism/mean-finance.balance-fetcher.ts
- src/apps/mean-finance/polygon/mean-finance.balance-fetcher.ts
- Get tokens from positions (which have metaType)
> fix(mean-finance): Added metatype to balance token

- src/apps/maple/helpers/maple.cache-manager.ts
- src/apps/maple/maple.module.ts
> fix(maple): Fix Pool APY

- src/apps/hex/ethereum/hex.balance-fetcher.ts
- src/apps/hex/ethereum/hex.stake.contract-position-fetcher.ts
- src/apps/hex/hex.definition.ts
- src/apps/hex/hex.module.ts
- Lining
- Added Links in app definition
> fix(hex): Linting + added links in app definition

- src/apps/insurace/helpers/index.ts
- src/apps/insurace/insurace.module.ts
> fix(insurace): Fix APY

- src/apps/penguin/avalanche/penguin.i-pefi.token-fetcher.ts
Not sure how this ever worked.
> fix(penguin): Fix iPEFI groupId

- src/apps/thales/optimism/thales.balance-fetcher.ts
We need to return the same number balances as the number of tokens we expect.
> fix(thales): Add missing reward token balance for thales escrow

- src/apps/geist/fantom/geist.platform-fees.contract-position-fetcher.ts
Geist claimable token is also counted in the additional claimable tokens.
> fix(geist): Fix double counting of geist claimable

- src/apps/llamapay/ethereum/llamapay.balance-fetcher.ts
> fix(llamapay): Fix missing balances using contract address from the stream

- .env.sample
As pointed out by @dimsome 
Closes #1854
> fix(env): Add missing .env.sample file

- cli/generators/generate-app-definition.ts
- src/apps/enzyme-finance/enzyme-finance.definition.ts
- src/apps/enzyme-finance/enzyme-finance.module.ts
- src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts
Enzyme price was set, but price per share was default. That's broken af.
> feat(enzyme-finance): Fix price per share

- src/apps/apecoin/ethereum/apecoin.staking.contract-position-fetcher.ts
Tested: http://localhost:5001/apps/apecoin/balances?addresses[]=0x10ccd4136471c7c266a9fc4569622989fb4cab99
> feat(apecoin): Add staked ApeCoin getBalances and address

- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/contract-position.template.position-fetcher.ts
I want to try and chunk the balance calculations into smaller batches. I have no idea if this will work, but this could potentially reduce the contention on the system (situation where we spawn 500+ promises that makes calls on chain) and make things a bit more predictable. It may generate a few more web3 calls due to the way multicall works, but it may at least succeed more often.
> feat(balances): Chunk balance calculations

- src/apps/iq/ethereum/iq.hiiq.contract-position-fetcher.ts
- src/apps/iq/iq.module.ts
> fix(iq): Linting

- src/apps/banano/arbitrum/banano.balance-fetcher.ts
- src/apps/banano/arbitrum/banano.farm.contract-position-fetcher.ts
- src/apps/banano/banano.definition.ts
- src/apps/banano/banano.module.ts
Added Arbitrum network for Banano.
Request a position for a random wallet like `0x59c3e4a92de15b4de6fbfd7aec0034992cd40eed`?
> feat(banano): Banano on Arbitrum

- src/apps/art-gobblers/art-gobblers.definition.ts
> fix(art-gobbler): Add description

- src/app-toolkit/app-toolkit.interface.ts
- src/app-toolkit/app-toolkit.service.ts
- src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
> feat(uniswap-v2): Get positions for balances from DB

- src/apps/apecoin/apecoin.definition.ts
> fix(apecoin): Add description

- src/balance/balance-presentation.service.ts
Since the presenters can run any arbitrary code, let's ignore the errors when they happen.
> fix(presenter): Catch and ignore presenter errors

- src/apps/synthetix/common/synthetix.position-presenter.ts
In some very odd cases this is undefined since it's being called with an empty balance set. Still trying to figure out why, but this will prevent a hard crash.
> fix(synthetix): Check if the contract position is undefined

- src/apps/uniswap-v2/common/uniswap-v2.pool.subgraph.template.token-fetcher.ts
Dataloader must return same length of array.
> feat(uniswap-v2): Fix volume data loader when graph is not synced

- src/position/selectors/token-dependency-selector.interface.ts
Working towards loading an NFT as an underlying token with a template fetcher.
> feat(token-loader): Support NFT as a token dependency

- src/apps/cask-protocol/cask-protocol.definition.ts
- src/apps/cask-protocol/common/cask-protocol.wallet.token-fetcher.ts
> feat: cask app label updates

- src/position/template/app-token.template.position-fetcher.ts
Resolving dependencies needs to match on address, network, and (maybe) token ID. Previous implementation wasn't broken, but this change is required for matching on underlying NFTs (for NFTX and NFT20 migrated to templates)
> feat(app-tokens): Match on network and token ID as well

- src/position/template/app-token.template.position-fetcher.ts
Collapse same-collection NFTs under an app token into a single object. We'll want to change this logic to keep them separate, but that would break mobile and web, so I'm just matching the existing implementation to keep things working with templates.
> feat(app-tokens): Collapse NFT tokens into collections

- src/apps/lyra-avalon/optimism/lyra-avalon.options.contract-position-fetcher.ts
- src/apps/lyra-avalon/optimism/lyra-avalon.pool.token-fetcher.ts
Update subgraph links
- [x ] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
> Update Lyra subgraph links

- src/apps/olympus/common/olympus.bond.contract-position-fetcher.ts
> feat(olympus): Allow extending Olympus definition

- src/app-toolkit/helpers/presentation/image.present.ts
> feat(nftx): Fix images

- src/apps/art-gobblers/art-gobblers.definition.ts
- src/apps/art-gobblers/art-gobblers.module.ts
- src/apps/art-gobblers/ethereum/art-gobblers.factory.contract-position-fetcher.ts
- src/apps/llama-airforce/ethereum/llama-airforce.vault.token-fetcher.ts
Align with terminology from ArtGobblers
> feat(art-gobblers): GOO Factory

- src/apps/gmx/common/gmx.perp.contract-position-fetcher.ts
- Fix label + balance in profit
> fix(gmx): Fix label and balances in profit

- src/apps/metavault-trade/polygon/metavault-trade.es-mvx.token-fetcher.ts
- Add group label to esMVX token-fetcher
> fix(metavault-trade): Add group label to esMVX token-fetcher

- src/apps/gearbox/ethereum/gearbox.credit-accounts.contract-position-fetcher.ts
- src/apps/gearbox/ethereum/gearbox.phantom.token-fetcher.ts
- src/apps/gearbox/gearbox.module.ts
> fix(gearbox): Fix Phantom tokens

- src/apps/gearbox/ethereum/gearbox.phantom.token-fetcher.ts
- Exclude phantom tokens from TIV and explorer
> fix(gearbox): Exclude phantom token from TIV and explorer

- src/apps/pods-yield/ethereum/config.ts
Added new stETHvv v2 strategy 
You can check the position of an address of the new vault using `impersonator.xyz `
On the page of the strategy itself: https://app.pods.finance/strategy/0x463f9ed5e11764eb9029762011a03643603ad879-1/
> feat(pods): updated pods-yield new strategy

- .eslintrc
- package.json
- pnpm-lock.yaml
- src/apps/exactly/.eslintrc.yaml
setup eslint typescript resolver as discussed here: https://github.com/Zapper-fi/studio/pull/1895#discussion_r1051213628
`pnpm lint`
> chore(eslint): 🧑‍💻 setup typescript resolver

- src/apps/gearbox/ethereum/gearbox.credit-accounts.contract-position-fetcher.ts
> fix(gearbox): Linting

- src/apps/keeper/common/keeper.job.contract-position-fetcher.ts
- src/apps/keeper/keeper.definition.ts
Corrects Keep3r name on UI and adds Jobs name to the contract positions
http://localhost:5001/apps/keeper/balances?addresses[]=0x45feebbd5cf86df61be8f81025e22ae07a07cb23&network=ethereum
> feat(keeper): Add keep3r job names

- .gitignore
ignore node version management config files.
- asdf (`.tool-versions`): https://asdf-vm.com/manage/configuration.html#tool-versions
- nodenv (`.node-version`): https://github.com/nodenv/nodenv#choosing-the-node-version
- nvm (`.nvmrc`): https://github.com/nvm-sh/nvm#nvmrc
`asdf local nodejs 16.19.0`
> chore(gitignore): 🙈 ignore version management config

- package.json
- pnpm-lock.yaml
We do not want to have a hard dependency on nestjs here, since it messes with symbol resolution. Just NPM things I suppose.
> fix(dependencies): Fix nestjs dependency issues

- src/apps/beefy/common/beefy.vault.token-definition-resolver.ts
- src/apps/beefy/common/beefy.vault.token-fetcher.ts
Shows the Beefy jSGD/XSGD pool mentioned in https://github.com/Zapper-fi/studio/issues/1889
Closes https://github.com/Zapper-fi/studio/issues/1889 fr
> feat(beefy): Show paused vaults

- src/apps/exactly/common/exactly.definitions-resolver.ts
- src/apps/exactly/common/exactly.fixed-position-fetcher.ts
- src/apps/exactly/common/exactly.token-fetcher.ts
- src/apps/exactly/contracts/abis/previewer.json
- src/apps/exactly/contracts/ethers/Previewer.ts
- src/apps/exactly/contracts/ethers/factories/Previewer__factory.ts
- src/apps/exactly/ethereum/exactly.borrow.token-fetcher.ts
- src/apps/exactly/ethereum/exactly.deposit.token-fetcher.ts
- src/apps/exactly/ethereum/exactly.fixed-borrow.token-fetcher.ts
- src/apps/exactly/ethereum/exactly.fixed-deposit.token-fetcher.ts
- src/apps/exactly/exactly.definition.ts
- fix: multiply rates by 100
- feat: add variable deposit rates
- update app name and description
- `0x872a7b69baa1a0226f0c2515c6350f964e215f2e`
- `0x8a6134eCba73D51f64794F93c6d0C057893d328d`
> feat(exactly): fix rates (x100), add deposit rates, update metadata

- src/apps/aave-amm/aave-amm.module.ts
- src/apps/agave/agave.module.ts
- src/apps/arrakis/arrakis.module.ts
- src/apps/b-protocol/b-protocol.module.ts
- src/apps/comethswap/comethswap.definition.ts
- src/apps/comethswap/comethswap.module.ts
- src/apps/geist/geist.module.ts
- src/apps/granary-finance/granary-finance.module.ts
- src/apps/inverse/contracts/abis/inverse-controller.json
- src/apps/inverse/contracts/ethers/InverseController.ts
- src/apps/inverse/contracts/ethers/factories/InverseController__factory.ts
- src/apps/inverse/inverse.module.ts
- src/apps/looks-rare/looks-rare.module.ts
- src/apps/meshswap/meshswap.module.ts
- src/apps/nereus-finance/nereus-finance.module.ts
- src/apps/pancakeswap/pancakeswap.module.ts
- src/apps/sturdy/sturdy.module.ts
- src/apps/teddy-cash/teddy-cash.module.ts
Remove dependencies between apps. Since app modules are dynamically configured, we use patch the imports to be `externallyConfigured`, and this is a complexity we don't need if we eliminate inter-app dependencies.
> feat(apps): Remove app to app dependencies

- src/apps/apps.module.ts
We've eliminated all inter-app dependencies, so the app importer becomes stupid simple.
> feat(apps): Simplify apps importer

- src/apps/sushiswap-kashi/binance-smart-chain/sushiswap-kashi.lending.token-fetcher.ts
- Previous subgraph returns `indexing_error`
> fix(sushiswap-kashi): Updated subgraph url

- src/apps/mux/fantom/mux.perp.contract-position-fetcher.ts
> feat(mux): Fix reader address

- src/apps/inverse-firm/ethereum/inverse-firm.loan.contract-position-fetcher.ts
- Early return when wallet doesn't have a position
> fix(inverse-firm): Fix escrow address for nil balances

- src/apps/polynomial/optimism/polynomial.call-selling-vault-queue.contract-position-fetcher.ts
- src/apps/polynomial/optimism/polynomial.call-selling-vault.token-fetcher.ts
- src/apps/polynomial/optimism/polynomial.put-selling-vault-queue.contract-position-fetcher.ts
- src/apps/polynomial/optimism/polynomial.put-selling-vault.token-fetcher.ts
- src/apps/polynomial/polynomial.definition.ts
- src/apps/polynomial/polynomial.module.ts
Messed up a few things in Polynomial when I refactored it to templates. Clean it up.
> feat(polynomial): Clean clean clean

- src/apps/gamma-strategies/arbitrum/gamma-strategies.pool.token-fetcher.ts
- src/apps/gamma-strategies/celo/gamma-strategies.pool.token-fetcher.ts
- src/apps/gamma-strategies/contracts/index.ts
- src/apps/gamma-strategies/ethereum/gamma-strategies.pool.token-fetcher.ts
- src/apps/gamma-strategies/gamma-strategies.definition.ts
- src/apps/gamma-strategies/gamma-strategies.module.ts
- src/apps/gamma-strategies/helpers/gamma-strategies.api.ts
- src/apps/gamma-strategies/helpers/gamma-strategies.pool.token-fetcher.ts
- src/apps/gamma-strategies/optimism/gamma-strategies.pool.token-fetcher.ts
- src/apps/gamma-strategies/polygon/gamma-strategies.pool.token-fetcher.ts
for gamma strategies
* fix ethereum uniswap
* add uniswap for arbitrum, celo, optimism, polygon
* add quickswap
see discussion in https://discord.com/channels/815421435900198962/815421435900198965/1061390518329811044
note: not affiliated with gamma team, implementation might be eligible for bounty, idk
this is a good address to test, it has small positions in most? pools 0xade38bd2e8d5a52e60047affe6e595bb5e61923a
> feat(gamma-strategies): implement other networks and exchanges

- src/apps/pirex/ethereum/pirex.vault.token-fetcher.ts
- src/apps/pirex/index.ts
> feat(pirex): To template

- src/apps/bend-dao/ethereum/bend-dao.position-presenter.ts
- src/apps/euler/common/euler.position-presenter.ts
Missing usages of `PresenterTemplate`
> fix(presenters): Use PresenterTemplate decorator

- cli/generators/generate-app-module.ts
- cli/generators/utils.ts
- src/apps/b-protocol/ethereum/b-protocol.maker-vault.contract-position-fetcher.ts
- src/apps/exactly/common/exactly.fixed-position-fetcher.ts
- src/apps/exactly/common/exactly.position-presenter.ts
- src/apps/geist/fantom/geist.incentives.contract-position-fetcher.ts
- src/apps/kwenta/common/kwenta.perp.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-builder.ts
- src/apps/kyberswap-elastic/common/kyberswap-elastic.liquidity.contract-position-builder.ts
- src/apps/llama-airforce/ethereum/llama-airforce.merkle-cache.ts
- src/apps/market-xyz/avalanche/market-xyz.position-presenter.ts
- src/apps/market-xyz/fantom/market-xyz.position-presenter.ts
- src/apps/market-xyz/polygon/market-xyz.position-presenter.ts
- src/apps/midas/midas.module.ts
- src/apps/openleverage/common/openleverage-pool.apy-helper.ts
- src/apps/rari-fuse/ethereum/rari-fuse.position-presenter.ts
- src/apps/robo-vault/common/robo-vault.api.client.ts
- src/apps/sushiswap-bentobox/common/sushiswap-bentobox.vault-tokens-resolver.ts
- src/apps/sushiswap-kashi/common/sushiswap-kashi.leverage.contract-position-fetcher.ts
- src/apps/synthetix/common/synthetix.mintr.snx-holders.cache.ts
- src/apps/synthetix/common/synthetix.synth.token-fetcher.ts
- src/apps/unipilot/common/unipilot-vault.apy.helper.ts
- src/apps/uniswap-v3/common/uniswap-v3.liquidity.contract-position-builder.ts
- src/apps/votium/ethereum/votium.merkle-cache.ts
Working towards codeless apps.
> feat(apps): Remove remaining app definition uses

- src/apps/synthetix/optimism/synthetix.perp-v2.contract-position-fetcher.ts
- src/apps/synthetix/synthetix.module.ts
> fix(synthethix): Linting

- src/apps/illuvium/ethereum/illuvium.s-ilv2.token-fetcher.ts
> fix(illuvium): Remove console log

- src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
- src/apps/pendle-v2/ethereum/pendle-v2.pool.token-fetcher.ts
- src/apps/pendle-v2/ethereum/pendle-v2.principal.token-fetcher.ts
- src/apps/pendle-v2/ethereum/pendle-v2.standardized-yield.token-fetcher.ts
- src/apps/pendle-v2/ethereum/pendle-v2.yield.token-fetcher.ts
- src/apps/pendle-v2/pendle-v2.module.ts
- Fix default dataProps (pendle-v2 + defiedge)
> fix(pendle-v2): Fix app tokens default dataProps

- src/apps/uwu-lend/ethereum/uwu-lend.position-presenter.ts
- src/apps/uwu-lend/uwu-lend.module.ts
- Add missing position presenter
> fix(uwu-lend): Add position presenter

- src/apps/unlockd-finance/ethereum/unlockd-finance.position-presenter.ts
- src/apps/unlockd-finance/unlockd-finance.module.ts
- Add missing position presenter
> fix(unlockd-finance): Add position presenter

- src/apps/convex/ethereum/convex.cvx-crv-staking-wrapped.contract-position-fetcher.ts
- src/apps/convex/ethereum/index.ts
Fix cvxCrvStakingWrapped reward balances + ad l
Set APY to 0 until we figure it out
> fix(convex): Fix cvxCrvStakingWrapped reward token balances

- src/apps/euler/ethereum/euler.position-presenter.ts
- Add farms to position presenter
> fix(euler): Add farms to position presenter

- src/apps/euler/ethereum/euler.single-staking-farm.contract-position-fetcher.ts
- Fix single staking farm definitions
> fix(euler): Fix single staking farm definition

- src/apps/index-coop/ethereum/index-coop.index.token-fetcher.ts
- Add dsETH
- Update labels showing which product are deprecated
**JPG** isn't part of Index-Coop anymore
> feat(index-coop): Add dsETH

- src/apps/beefy/beefy.module.ts
- src/apps/beefy/common/beefy.vault.token-definition-resolver.ts
- src/apps/beefy/ethereum/beefy.vault.token-fetcher.ts
- src/apps/beefy/moonriver/beefy.vault.token-fetcher.ts
- Support Beefy on Ethereum and Moonriver
https://github.com/Zapper-fi/studio/issues/1844
> feat(beefy): Support Beefy on Ethereum and Moonriver

- src/apps/thales/optimism/thales.vault.contract-position-fetcher.ts
- src/apps/thales/thales.module.ts
- Linting
- Update vault definition
> fix(thales): Fix vault definitions

- src/apps/beefy/common/beefy.vault.token-definition-resolver.ts
- src/apps/beefy/common/beefy.vault.token-fetcher.ts
display apy for beefy vaults.
`0xb997cab4f30ebc3249f7a8db42918b7d3b6704c4`
> feat(beefy): ✨ display vault apy

- src/apps/beefy/common/beefy.vault.token-definition-resolver.ts
> fix(beefy): Uncomment cache decorator

- src/apps/lyra-avalon/ethereum/lyra-avalon.stk-lyra.token-fetcher.ts
- src/apps/lyra-avalon/lyra-avalon.module.ts
stkLyra on ethereum mainnet
0xdcb7e8f1b586c94dde9b430557e4df6727779aca
> feat(lyra-avalon): ethereum L1 staking contract

- src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
> fix(defiedge): Fix strategy liquidity

- src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
- <s>Added `getBalances()` in `defiedge.strategy.token-fetcher.ts`</s> (reverted)
- Fixed `pricePerShare` calculation
Fetch balance of `0x47b517225f39Bb1853416D1d57Da9Afeb1460cDd` on polygon
http://localhost:5001/apps/defiedge/balances?addresses[]=0x47b517225f39Bb1853416D1d57Da9Afeb1460cDd&network=polygon
> fix(defiedge): pricePerShare calculation

- src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
- Decode symbol on strategy app tokens
> fix(defiedge): Decode symbol on strategy app tokens

- src/apps/stake-dao/ethereum/stake-dao.locker.token-fetcher.ts
> fix(stake-dao): Add sdYFI locker

- src/apps/velodrome/optimism/velodrome.bribe.contract-position-fetcher.ts
- Filter out not supported pool token addresses (aka which contains OptiDoge)
> fix(velodrome): Filter out not supported underlying tokens on bribe contract position

- src/apps/velodrome/optimism/velodrome.bribe.contract-position-fetcher.ts
> fix(velodrome): Fix bribe balances

- src/apps/velodrome/common/velodrome.definitions-resolver.ts
- src/apps/velodrome/optimism/velodrome.farm.contract-position-fetcher.ts
> fix(velodrome): Fix definition resolver url and set staking position reward rates to 0 (temporary)

- src/apps/lido/ethereum/lido.steth.token-fetcher.ts
- src/apps/lido/ethereum/lido.wsteth.token-fetcher.ts
- Show stETH and wstETH balances
**will hide correspondin base token as this hits prod
> fix(lido): Show stETH and wstETH balances

- src/apps/impermax/arbitrum/impermax.position-presenter.ts
- src/apps/impermax/common/impermax.borrow.contract-position-fetcher.ts
- src/apps/impermax/common/impermax.position-presenter.ts
- src/apps/impermax/ethereum/impermax.position-presenter.ts
- src/apps/impermax/impermax.module.ts
- src/apps/impermax/polygon/impermax.position-presenter.ts
> fix(impermax): Add position presenter

- src/apps/lyra-avalon/ethereum/lyra-avalon.staking.contract-position-fetcher.ts
- src/apps/lyra-avalon/lyra-avalon.module.ts
Lyra LP farming on Ethereum
0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50
> feat(lyra): Ethereum LP farming

- src/apps/amp/amp.module.ts
- src/apps/amp/common/amp.staking-resolver.ts
- src/apps/amp/ethereum/amp.farm.contract-position-fetcher.ts
- src/apps/gamma-strategies/helpers/gamma-strategies.api.ts
- Fix Amp staking balances
- Linting Gamma strategies api helper
Fixed staking balances (it was comparing string instead of numbers) + re-wrote some sections making the code a bit cleaner for the future updates
cc: @bubby-eth
> fix(amp): Fix staking balances

- src/apps/amp/common/amp.staking-resolver.ts
- src/apps/amp/ethereum/amp.farm.contract-position-fetcher.ts
> fix(amp): Fix staking label

- src/apps/beanstalk/common/beanstalk.balance-resolver.ts
**NOTE**: The fixes in this PR are also included in #2275. This can be closed in favor of that PR that fixes these bugs and adds new feat.
Fix bug in Beanstalk when a user has no account on the system.
> fix(beanstalk): bug fixes

- src/apps/impermax/common/impermax.lend.token-fetcher.ts
- Fix IMX TIV on Arbitrum + removing deprecated markets
What was wrong with the TIV ? 
IMX market had a exchange rate of 74k leading to 2B liquidity in that single market
fix https://github.com/Zapper-fi/studio/issues/2281
> fix(impermax): Fix Impermax IMX TIV on Arbitrum

- src/apps/velodrome/common/velodrome.definitions-resolver.ts
- src/apps/velodrome/velodrome.module.ts
- Filter pool APYs above a certain threshold
> fix(velodrome): Filtering APYs above a certain threshold

- src/apps/beanstalk/beanstalk.module.ts
- src/apps/beanstalk/ethereum/beanstalk.silo-deposit.contract-position-fetcher.ts
- src/apps/beanstalk/ethereum/beanstalk.silo-earned.contract-position-fetcher.ts
- Refactor getTokenBalancesPerPosition of the silo deposit position
> fix(beanstalk): Refactor fetching balances of silo deposit position

- src/apps/vendor-finance/graphql/getLendingPoolsQuery.ts
Fix for Vendor Finance.
Graph query that was used was filtering out pools that were supposed to be included.
> fix: update vendor query

- src/apps/clever/clever.module.ts
- src/apps/clever/ethereum/addresses.ts
- src/apps/clever/ethereum/clever.abc.token-fetcher.ts
- src/apps/clever/ethereum/clever.farming.contract-position-fetcher.ts
- src/apps/clever/ethereum/clever.vesting.contract-position-fetcher.ts
- src/apps/vendor-finance/arbitrum/vendor-finance.pool.contract-position-fetcher.ts
- Linting
- Fix farming definitions
- smol refactor
> fix(clever): Refactor faming position and commented out abc token

- src/apps/maple/ethereum/maple.pool.token-fetcher.ts
As provided by Maple dev team, the exchange rate of the token is calculated as `(totalAssets - unrealizedLosses) / supply`.
> feat(maple): Fix price per share on pools

- src/apps/gamma-strategies/common/gamma-strategies.definition-resolver.ts
> fix(gamma-strategies): Fix endpoint url

- src/apps/platypus-finance/avalanche/platypus-finance.pool.token-fetcher.ts
- src/apps/platypus-finance/common/platypus-finance.pool.token-fetcher.ts
- Remove deprecated AND faulty pool from static list
> fix(platypus-finance): Remove deprecated faulty pool

- src/apps/honeyswap/gnosis/honeyswap.pool.token-fetcher.ts
- src/apps/honeyswap/honeyswap.module.ts
- src/apps/honeyswap/polygon/honeyswap.pool.token-fetcher.ts
- src/apps/uniswap-v2/common/uniswap-v2.pool.subgraph.template.token-fetcher.ts
- Add skipVolume condition
- Refactor honeyswap to use default template
> fix(uniswap-v2): Add condition on skipVolume

- src/apps/clearpool/clearpool.module.ts
- src/apps/clearpool/common/clearpool.pool-definition-resolver.ts
- src/apps/clearpool/common/clearpool.pool.token-fetcher.ts
- Fix endpoint (url) + extract external calls into a resolver
> fix(clearpool): Fix endpoint URL + extract external calls into a resolver

- src/apps/vendor-finance/ethereum/vendor-finance.pool.contract-position-fetcher.ts
- src/apps/vendor-finance/graphql/constants.ts
- src/apps/vendor-finance/graphql/getLendingPoolsQuery.ts
- src/apps/vendor-finance/vendor-finance.module.ts
Added mainnet support for Vendor Finance.
> feat: added a new chain for vendor finance

- src/apps/kwenta/common/kwenta.perp.contract-position-fetcher.ts
- src/apps/synthetix/optimism/synthetix.perp-v2.contract-position-fetcher.ts
> fix(apps): Linting

- src/apps/across/common/across.pool-v2.token-fetcher.ts
- src/apps/across/ethereum/across.pool-v2.token-fetcher.ts
Fetching and searching through a lot of logs has it's limitations.. 
- Fix across v2 pools
> fix(across): Fix pools-v2

- src/apps/lyra-newport/arbitrum/lyra-newport.options.contract-position-fetcher.ts
- src/apps/lyra-newport/arbitrum/lyra-newport.pool.token-fetcher.ts
- src/apps/lyra-newport/lyra-newport.module.ts
> fix(lyra-newport): Linting

- src/apps/ethereum-staking/ethereum/ethereum-staking.deposit.contract-position-fetcher.ts
Use the fair-use [beaconcha.in](https://beaconcha.in) API to retrieve the actual balances for the validators belonging to a user. I've consolidated the balances together, but it actually might make more sense to split using custom balances.
http://localhost:5001/apps/ethereum-staking/balances?addresses[]=0xfef0e7635281ef8e3b705e9c5b86e1d3b0eab397
Shows `32` in production, and `36.356508043` in local.
> feat(ethereum-staking): Use beaconcha.in API to retrieve real actual balance

- src/apps/ethereum-staking/ethereum/ethereum-staking.deposit.contract-position-fetcher.ts
For very large validator pools (see [here](https://beaconcha.in/validators/deposit-leaderboard)), there is no way to poll the live amount without busting our rate limits. As such, when there are more than 500 deposits, rely on the subgraph as the source of truth for deposits.
http://localhost:5001/apps/ethereum-staking/balances?addresses%5B%5D=0xfef0e7635281ef8e3b705e9c5b86e1d3b0eab397 has 4 validators
http://localhost:5001/apps/ethereum-staking/balances?addresses[]=0xa40dfee99e1c85dc97fdc594b16a460717838703 has 319648 ETH deposited (it's the Kraken depositor)
> feat(ethereum-staking): Deal with rate limits by falling back to subgraph

- src/apps/llama-airforce/ethereum/llama-airforce.airdrop.contract-position-fetcher.ts
- Fix merkle distributor addresses
> fix(llama-airforce): Fix merkle distributor addresses

- src/contract/contracts/ethers/Multicall.ts
- src/contract/contracts/ethers/factories/Multicall__factory.ts
- src/multicall/multicall.service.ts
> fix(multicall-contract): Revert contract interfaces update

- src/apps/idle/ethereum/idle.best-yield.contract-position-fetcher.ts
- src/apps/idle/ethereum/idle.junior-tranche.token-fetcher.ts
- src/apps/idle/ethereum/idle.senior-tranche.token-fetcher.ts
- src/apps/idle/idle.module.ts
- Testing group renaming
- Cleanup
> fix(idle): Testing renaming group + cleanup

- src/apps/exactly/common/exactly.borrow.token-fetcher.ts
- src/apps/exactly/common/exactly.definitions-resolver.ts
- src/apps/exactly/common/exactly.deposit.token-fetcher.ts
- src/apps/exactly/common/exactly.fixed-borrow.token-fetcher.ts
- src/apps/exactly/common/exactly.fixed-deposit.token-fetcher.ts
- src/apps/exactly/contracts/abis/previewer.json
- src/apps/exactly/contracts/ethers/Previewer.ts
- src/apps/exactly/contracts/ethers/factories/Previewer__factory.ts
- src/apps/exactly/ethereum/exactly.borrow.token-fetcher.ts
- src/apps/exactly/ethereum/exactly.deposit.token-fetcher.ts
- src/apps/exactly/ethereum/exactly.fixed-borrow.token-fetcher.ts
- src/apps/exactly/ethereum/exactly.fixed-deposit.token-fetcher.ts
- src/apps/exactly/exactly.module.ts
- src/apps/exactly/optimism/exactly.borrow.token-fetcher.ts
- src/apps/exactly/optimism/exactly.deposit.token-fetcher.ts
- src/apps/exactly/optimism/exactly.fixed-borrow.token-fetcher.ts
- src/apps/exactly/optimism/exactly.fixed-deposit.token-fetcher.ts
- src/apps/exactly/optimism/exactly.position-presenter.ts
- add optimism support
- use new previewer contract on ethereum
`0xAF935695EB156b6fe95af0E83Daafbd62CA37Af5`
> feat(exactly): ✨ add optimism support

- src/apps/robo-vault/common/robo-vault.api.client.ts
- src/apps/robo-vault/robo-vault.module.ts
> fix(robo-vault): Update endpoint url

- src/apps/llamapay/common/llamapay.vesting-escrow.contract-position-fetcher.ts
- Fix disabled streams
- Added cliff length and steam end time
> fix(llamapay): Fix disabled streams

- src/apps/gains-network/arbitrum/gains-network.g-token.token-fetcher.ts
- src/apps/gains-network/arbitrum/gains-network.locked.contract-position-fetcher.ts
- src/apps/gains-network/arbitrum/gains-network.staking.contract-position-fetcher.ts
- src/apps/gains-network/common/gains-network.g-token.token-fetcher.ts
- src/apps/gains-network/common/gains-network.locked.contract-position-fetcher.ts
- src/apps/gains-network/common/gains-network.staking.contract-position-fetcher.ts
- src/apps/gains-network/gains-network.module.ts
- src/apps/gains-network/polygon/gains-network.g-token.token-fetcher.ts
- src/apps/gains-network/polygon/gains-network.locked.contract-position-fetcher.ts
- src/apps/gains-network/polygon/gains-network.staking.contract-position-fetcher.ts
- Add locked gTokens on Arbitrum
- Extracted duplicated logic
> feat(gains-network): Add locked gTokens positions on Arbitrum

- src/apps/aave-v2/polygon/aave-v2.supply.token-fetcher.ts
- src/apps/nereus-finance/avalanche/nereus-finance.stable-debt.token-fetcher.ts
- src/apps/nereus-finance/avalanche/nereus-finance.supply.token-fetcher.ts
- src/apps/nereus-finance/avalanche/nereus-finance.variable-debt.token-fetcher.ts
> fix(aave): Liting Aave supply token fetcher

- src/apps/uniswap-v3/binance-smart-chain/uniswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/uniswap-v3/uniswap-v3.module.ts
> feat(uniswap-v3): Add pools on BSC

- src/apps/uniswap-v3/celo/uniswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/uniswap-v3/uniswap-v3.module.ts
> feat(uniswap-v3): Add Pools on Celo

- src/apps/silo-finance/common/silo-finance.d-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.definition-resolver.ts
- src/apps/silo-finance/common/silo-finance.s-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.silo.contract-position-fetcher.ts
- src/apps/silo-finance/common/silo-finance.sp-asset.token-fetcher.ts
- Fix s, sp and d tokens definitions and fix d-token balances
> fix(silo-finance): Fix asset token definitions and d-token balances

- src/apps/solace/common/solace.xs-locker.contract-position-fetcher.ts
- Fix xs-locker balances (appId: Solace)
> fix(solace): Fix xs-locker balances

- src/apps/polynomial/optimism/polynomial.perp.contract-position-fetcher.ts
Trying to fix polynomial perp
0xacbe85b298d2c1b791ece44ec2c17021b011db03
> fix(polynomial): smart account address

- src/apps/silo-finance/common/silo-finance.d-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.s-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.silo.contract-position-fetcher.ts
- Fix s token balances and images
> fix(silo-finance): Fix S token balances and images

- src/apps/mux/common/mux.perp.contract-position-fetcher.ts
- Updated Perp definition to be consistent across all positions
> fix(mux): Fix Mux perp definitions and balances

- src/apps/thales/optimism/thales.vault.contract-position-fetcher.ts
New thales vault
0x21fff64975b0c9cf1202771aed6cf104c99a1667
> feat(thales): Overtime Parlay Discount vault

- src/apps/radiant-capital/arbitrum/radiant-capital.position-presenter.ts
- Add staking position to presenter
> fix(radiant-capital): Add staking position to presenter

- src/apps/polynomial/optimism/polynomial.perp.contract-position-fetcher.ts
- src/apps/polynomial/polynomial.module.ts
> fix(polynomial): Linting

- src/apps/superfluid/polygon/superfluid.vault.token-fetcher.ts
> fix(superfluid): Filter out non Supertoken addresses

- src/apps/dopex/arbitrum/dopex.ssov-v3-deposit.contract-position-fetcher.ts
> fix(dopex): Fix SSOV v3 deposit underlying token

- src/apps/kwenta/optimism/kwenta.perp-v1-cross-margin.contract-position-fetcher.ts
- src/apps/synthetix/optimism/synthetix.perp-v1.contract-position-fetcher.ts
- src/apps/synthetix/optimism/synthetix.perp-v2.contract-position-fetcher.ts
- src/apps/synthetix/optimism/synthetix.perp.contract-position-fetcher.ts
Reduce duplication of code between v1, v2 and other implementations on top for synthetix perp
N/A
> feat(synthetix): perp refactor

- src/apps/idle/ethereum/idle.vault.token-fetcher.ts
Paused vault tokens throw an error when attempting to fetch `getTokenPrice`, so filter them out while retrieving addresses.
> feat(idle): Filter out paused vault tokens that crash the fetcher

- src/apps/dopex/arbitrum/dopex.ssov-v3-option.token-fetcher.ts
> feat(dopex): Filter out expired options

- src/apps/yield-protocol/common/yield-protocol.borrow.contract-position-fetcher.ts
- src/apps/yield-protocol/common/yield-protocol.lend.token-fetcher.ts
- src/apps/yield-protocol/common/yield-protocol.pool.token-fetcher.ts
- Check if pool address is zero
- Check pool balance
- Fix nullable asset ID
> fix(yield-protocol): Fix failing positions

- src/apps/beethoven-x/common/beethoven-x.pool.token-fetcher.ts
- src/apps/beethoven-x/fantom/beethoven-x.pool.token-fetcher.ts
- src/apps/beethoven-x/optimism/beethoven-x.pool.token-fetcher.ts
Derive new logic from the Beethoven X backend code.
> feat(studio): Update logic for BeethovenX token supplies

- src/apps/exactly/common/exactly.borrow.token-fetcher.ts
`0xAF935695EB156b6fe95af0E83Daafbd62CA37Af5`
> fix(exactly): 🐛 variable borrow label

- src/apps/uniswap-v3/celo/uniswap-v3.liquidity.contract-position-builder.ts
- src/apps/uniswap-v3/celo/uniswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/uniswap-v3/uniswap-v3.module.ts
Celo has a different address for the manager (comparatively to other networks). This PR is updating the code for Celo by adding the right address for contract position fetcher.
> fix(studio): Fixing balance builder for UniV3 positions on Celo

- src/apps/lyra-avalon/arbitrum/lyra-avalon.options.contract-position-fetcher.ts
- src/apps/lyra-avalon/arbitrum/lyra-avalon.stk-lyra-claimable.contract-position-fetcher.ts
- src/apps/lyra-avalon/arbitrum/lyra-avalon.stk-lyra.token-fetcher.ts
- src/apps/lyra-avalon/lyra-avalon.module.ts
> feat(lyra-avalon): Add staked Lyra and Options on Arbitrum

- src/apps/silo-finance/common/silo-finance.incentives.contract-position-fetcher.ts
- src/apps/silo-finance/ethereum/silo-finance.incentives.contract-position-fetcher.ts
- src/apps/silo-finance/silo-finance.module.ts
- Add Incentive position on Ethereum
- Extract fetching sToken addresses from `getTokenBalancesPerPosition` into definiton
`0x357dfdc34f93388059d2eb09996d80f233037cba`
> feat(silo-finance): Add Incentive position on Ethereum

- src/apps/curve/common/curve.pool-dynamic.token-fetcher.ts
- src/apps/curve/common/curve.pool-static.token-fetcher.ts
- src/apps/meshswap/polygon/meshswap.supply.token-fetcher.ts
- src/apps/pancakeswap/common/pancakeswap.pool-dynamic.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.d-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.s-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.sp-asset.token-fetcher.ts
- src/apps/sushiswap-kashi/common/sushiswap-kashi.lending.token-fetcher.ts
- src/apps/uniswap-v2/common/uniswap-v2.pool.on-chain.template.token-fetcher.ts
- src/apps/yield-protocol/common/yield-protocol.lend.token-fetcher.ts
- src/apps/yield-protocol/common/yield-protocol.pool.token-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/app-token.template.types.ts
Very helpful when resolving data through the GQL layer in activity feed.
> feat(studio): Pass through isDebt as a data prop

- src/apps/thales/arbitrum/thales.vault.contract-position-fetcher.ts
- src/apps/thales/common/thales.vault.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.vault.contract-position-fetcher.ts
- src/apps/thales/thales.module.ts
Thales/Overtime vaults on Arbitrum
0xaa32a69dcc7f0fb97312ab9fc3a96326dda124c4
> feat(thales): Arbitrum Vaults

- src/apps/thales/arbitrum/thales.escrow.contract-position-fetcher.ts
- src/apps/thales/arbitrum/thales.overtime-amm-lp.contract-position-fetcher.ts
- src/apps/thales/arbitrum/thales.staking.contract-position-fetcher.ts
- src/apps/thales/arbitrum/thales.vault.contract-position-fetcher.ts
- src/apps/thales/common/thales.overtime-amm-lp.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.escrow.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.overtime-amm-lp.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.staking.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.vault.contract-position-fetcher.ts
- src/apps/thales/thales.module.ts
> fix(thales): Linting

- src/apps/exactly/common/exactly.rewards.contract-position-fetcher.ts
- src/apps/exactly/exactly.module.ts
- src/apps/exactly/optimism/exactly.rewards.contract-position-fetcher.ts
Add claimable rewards for [Exactly](https://zapper.xyz/apps/exactly)
> feat(exactly): ✨ add claimable rewards

- src/apps/plutus/arbitrum/plutus.farm-pls-rdnt.contract-position-fetcher.ts
- Fix plsRdnt token order
`0x3b8e1903ed6d4da2c7f88422b72c4b182570293c`
> fix(plutus): Fix plsRdnt token order

- package.json
- pnpm-lock.yaml
The installed version of the KS SDK was out-dated. Installing the latest version helped fetching positions that were missing.
Impersonating `0xca86d57519dbfe34a25eef0923b259ab07986b71`
```
{
"0xca86d57519dbfe34a25eef0923b259ab07986b71":{
"products":[
{
"label":"Pools",
"assets":[
{
"type":"contract-position",
"address":"0x2b1c7b41f6a8f2b2bc45c3233a5d5fb3cd6dc9a8",
"appId":"kyberswap-elastic",
"groupId":"liquidity",
"network":"avalanche",
"tokens":[
{
"metaType":"supplied",
"type":"base-token",
"network":"avalanche",
"address":"0x6e84a6216ea6dacc71ee8e6b0a5b7322eebc0fdd",
"symbol":"JOE",
"decimals":18,
"price":0.585899,
"balance":1804891.906527159,
"balanceRaw":"1804891906527159022852460",
"balanceUSD":1057484.3631423558
},
{
"metaType":"supplied",
"type":"base-token", …
```
> fix(studio): Update KyberSwap SDK to latest version

- src/apps/silo-finance/common/silo-finance.d-token.token-fetcher.ts
- src/apps/silo-finance/common/silo-finance.s-token.token-fetcher.ts
> fix(studio): Fix zero totals case

- src/apps/reserve-protocol/ethereum/reserve-protocol.cooldown.contract-position-fetcher.ts
- src/apps/reserve-protocol/ethereum/reserve-protocol.staked-rsr.token-fetcher.ts
- src/apps/reserve-protocol/reserve-protocol.module.ts
> fix(reserve-protocol): Linting

- src/apps/lyra-avalon/arbitrum/lyra-avalon.options.contract-position-fetcher.ts
- Fix Lyra Avalon option collateral decimals
`0xe1303f0cfd614622026b6e91eb1e862d28c28c94`
> fix(lyra-avalon): Fix Lyra Avalon collateral decimals

- src/apps/dolomite/arbitrum/dolomite.borrow.contract-position-fetcher.ts
- src/apps/dolomite/arbitrum/dolomite.contract-position.template.position-fetcher.ts
- src/apps/dolomite/arbitrum/dolomite.dolomite.contract-position-fetcher.ts
- src/apps/dolomite/arbitrum/dolomite.pools.token-fetcher.ts
- src/apps/dolomite/common/dolomite.contract-position.template.position-fetcher.ts
- src/apps/dolomite/common/utils.ts
- src/apps/dolomite/dolomite.module.ts
> fix(dolomite): Linting and Cleanup

- src/apps/botto/ethereum/botto.farm.contract-position-fetcher.ts
- src/apps/euler/ethereum/euler.single-staking-farm.contract-position-fetcher.ts
- src/apps/jones-dao/arbitrum/jones-dao.farm.contract-position-fetcher.ts
- Fix getIsActive underflow errors
> fix(apps): Fix getIsActive underflow errors

- src/apps/redacted-cartel/ethereum/redacted-cartel.revenue-lock.contract-position-fetcher.ts
- Fix WETH claimable balances 
cc @albuquerque-rafael
> fix(redacted-cartel): Fix revenue lock WETH claimable balances

- src/apps/dolomite/arbitrum/dolomite.borrow.contract-position-fetcher.ts
- src/apps/dolomite/arbitrum/dolomite.dolomite.contract-position-fetcher.ts
- src/apps/dolomite/common/dolomite.contract-position.template.position-fetcher.ts
> fix(dolomite): Rename dolomite positions

- src/apps/pool-together-v3/common/pool-together-v3.community-ticket.token-fetcher.ts
- src/apps/pool-together-v3/ethereum/pool-together-v3.community-ticket.token-fetcher.ts
- src/apps/pool-together-v3/gnosis/pool-together-v3.community-ticket.token-fetcher.ts
- src/apps/pool-together-v3/polygon/pool-together-v3.community-ticket.token-fetcher.ts
- Filter out addresses from community ticket addresses
> fix(pool-together-v3): Filter out ticket addresses returned by API from community tickets

- src/apps/lemma-finance/optimism/lemma-finance.usdl.token-fetcher.ts
- src/apps/moonrock/ethereum/moonrock.index.token-fetcher.ts
> feat(apps): Fix pricePerShare

- src/apps/wombat-exchange/binance-smart-chain/wombat-exchange.pool.token-fetcher.ts
> fix(wombat-exchange): Add pool token addresses

- src/apps/wombat-exchange/arbitrum/wombat-exchange.pool.token-fetcher.ts
- src/apps/wombat-exchange/arbitrum/wombat-exchange.voting-escrow.contract-position-fetcher.ts
- src/apps/wombat-exchange/binance-smart-chain/wombat-exchange.pool.token-fetcher.ts
- src/apps/wombat-exchange/common/wombat-exchange.pool.token-fetcher.ts
- src/apps/wombat-exchange/wombat-exchange.module.ts
- Add pools and voting escrow on Arbtitrum
> feat(wombat-exchange): Add pools and voting escrow position on Arbitrum

- src/apps/shapeshift/ethereum/shapeshift.farm.contract-position-fetcher.ts
- Updates ShapeShift's Fox Farms.
- Marks inactive as such.
http://localhost:5001/apps/shapeshift/positions?groupIds[]=farm
> fix(shapeshift): update fox farms

- src/apps/convex/polygon/convex.lp-farm.contract-position-fetcher.ts
> fix(convex): Fix underlying lp token addresses

- src/apps/thales/arbitrum/thales.vault.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.vault.contract-position-fetcher.ts
overtime upsettoor vault (yes that is the actual name)
For both OP and ARB: 0xaa32a69dcc7f0fb97312ab9fc3a96326dda124c4
> feat(thales): upsettoor vault

- src/apps/ensuro/common/ensuro.api-registry.ts
- src/apps/ensuro/ensuro.module.ts
- src/apps/ensuro/polygon/ensuro.e-token.token-fetcher.ts
> fix(ensuo): Linting

- src/apps/rocket-pool/ethereum/rocket-pool.minipool.contract-position-fetcher.ts
> fix(rocket-pool): Fix Minipool raw balances

- src/apps/rocket-pool/ethereum/rocket-pool.minipool.contract-position-fetcher.ts
- Using the same key requires extending custom contract position
> fix(rocket-pool): Extend the custom contract position

- src/apps/synthetix/common/synthetix.position-presenter.ts
- src/apps/synthetix/ethereum/synthetix.position-presenter.ts
- src/apps/synthetix/optimism/synthetix.position-presenter.ts
Mintr presenter isn't working on OP due to hardcoded mainnet addresses
0x324Fbd9536bf3d77d36137310fd4abe5130DfEA9
> fix(synthetix): OP position presenter

- src/apps/synthetix/optimism/synthetix.perp-v1.contract-position-fetcher.ts
- src/apps/synthetix/optimism/synthetix.perp-v2.contract-position-fetcher.ts
- src/apps/synthetix/optimism/synthetix.perp.contract-position-fetcher.ts
- Fix perp balances + smol refactor
> fix(synthetix): Fix Perp balances and smol refactor

- README.md
- This command was removed at the same time we removed definition files
> fix(readme): Remove create-group command from docs

- src/apps/synthetix/optimism/synthetix.perp.contract-position-fetcher.ts
Revert updates related to balances 
** added to my todo
> fix(synthetix): Revert Synthetix PERP balance updates

- src/apps/yearn/optimism/yearn.v2-vault.token-fetcher.ts
- src/apps/yearn/yearn.module.ts
- Add support for Yean v2 vaults on Optimism
> feat(yearn): Add v2 vaults on Optimism

- src/apps/arrakis/common/arrakis.pool-definition-resolver.ts
- src/apps/aura/common/aura.balancer-pool.resolver.ts
- src/apps/ren/common/ren.api.client.ts
- src/apps/rubicon/common/rubicon.bath.token-definition-resolver.ts
- src/apps/sentiment/common/sentiment.accounts-resolver.ts
- src/apps/silo-finance/common/silo-finance.definition-resolver.ts
- src/apps/solid-lizard/common/solid-lizard.definitions-resolver.ts
- src/apps/sushiswap-bentobox/common/sushiswap-bentobox.vault-tokens-resolver.ts
- src/apps/synthetix/common/synthetix.mintr.snx-holders.cache.ts
- src/apps/tenderize/common/tenderize.token-definition-resolver.ts
This reverts commit 2053d92059bc5d97f54c7aad2042dfc4f5da0c9e.
TheGraph subgraph database maintenance is over
> fix(subgraph): Bump cached data ttl to an hour

- src/apps/granary-finance/arbitrum/granary-finance.position-presenter.ts
- src/apps/granary-finance/arbitrum/granary-finance.stable-debt.token-fetcher.ts
- src/apps/granary-finance/arbitrum/granary-finance.supply.token-fetcher.ts
- src/apps/granary-finance/arbitrum/granary-finance.variable-debt.token-fetcher.ts
- src/apps/granary-finance/granary-finance.module.ts
- src/network-provider/network-provider.registry.ts
- Granary finance lending markets on Arbtitrum
- Update RPC endpoint (previous one was 💀 )
> feat(granary-finace): Add lending markets on Arbitrum

- .github/workflows/release-please.yml
Add no git checks to prevent failing publish
> feat(studio): Add no git checks

- pnpm-lock.yaml
- src/apps/rigoblock/arbitrum/rigoblock.pool.token-fetcher.ts
- src/apps/rigoblock/common/rigoblock.log-provider.ts
- src/apps/rigoblock/common/rigoblock.pool.pool-builders.ts
- src/apps/rigoblock/common/rigoblock.pool.token-fetcher.ts
- src/apps/rigoblock/ethereum/rigoblock.pool.token-fetcher.ts
- src/apps/rigoblock/optimism/rigoblock.pool.token-fetcher.ts
- src/apps/rigoblock/polygon/rigoblock.pool.token-fetcher.ts
- src/apps/rigoblock/rigoblock.module.ts
> fix(rigoblock): Fix Linting

- src/apps/superfluid/polygon/superfluid.vault.token-fetcher.ts
- Filter out RIC address because it's a base token, not an app token
> fix(superfluid): Filter out RIC app token address from vault position

- pnpm-lock.yaml
- src/apps/pancakeswap-v3/binance-smart-chain/pancakeswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/pancakeswap-v3/common/pancakeswap-v3.liquidity.contract-position-builder.ts
- src/apps/pancakeswap-v3/common/pancakeswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/pancakeswap-v3/common/pancakeswap-v3.liquidity.types.ts
- src/apps/pancakeswap-v3/pancakeswap-v3.module.ts
> fix(pancakeswap-v3): Linting

- src/apps/raft/common/raft.position.contract-position-fetcher.ts
- src/apps/raft/ethereum/raft.position-presenter.ts
- src/apps/reflexer/ethereum/reflexer.position-presenter.ts
see https://github.com/Zapper-fi/studio/pull/2732, https://discord.com/channels/647279669388771329/964569348243075082/1117193673034170438
http://localhost:5001/apps/raft/balances?network=ethereum&addresses%5B%5D=0x6bddefb9f04b01c326b43b218059ee6938ea1ca8
```
"meta": [
{
"label": "C-Ratio",
"type": "pct",
"value": 1.587133344315028
},
{
"label": "Liquidation Price",
"type": "dollar",
"value": 1480.4464536954717
}
]
}
],
```
> fix(raft,reflexer): fix missing position presenters

- src/apps/tai/ethereum/tai.collateral-fetcher.ts
- src/apps/tai/ethereum/tai.safe.contract-position-fetcher.ts
> fix(tai): Linting

- src/apps/raft/common/raft.position.contract-position-fetcher.ts
- src/apps/raft/ethereum/raft.position-presenter.ts
- src/apps/raft/raft.module.ts
> fix(raft): Linting

- src/apps/mean-finance/arbitrum/mean-finance.dca-position.contract-position-fetcher.ts
- src/apps/mean-finance/binance-smart-chain/mean-finance.dca-position.contract-position-fetcher.ts
- src/apps/mean-finance/ethereum/mean-finance.dca-position.contract-position-fetcher.ts
- src/apps/mean-finance/mean-finance.module.ts
- src/apps/mean-finance/optimism/mean-finance.dca-position.contract-position-fetcher.ts
- src/apps/mean-finance/optimism/mean-finance.optimism-airdrop.contract-position-fetcher.ts
- src/apps/mean-finance/polygon/mean-finance.dca-position.contract-position-fetcher.ts
- Fix Airdrop position balances
- Linting
> fix(mean-finance): Fix airdrop position balances

- src/apps/kyberswap-elastic/arbitrum/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/arbitrum/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/avalanche/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/avalanche/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/binance-smart-chain/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/binance-smart-chain/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-builder.ts
- src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/contracts/abis/kyberswap-elastic-lm.json
- src/apps/kyberswap-elastic/contracts/ethers/KyberswapElasticLm.ts
- src/apps/kyberswap-elastic/contracts/ethers/factories/KyberswapElasticLm__factory.ts
- src/apps/kyberswap-elastic/contracts/index.ts
- src/apps/kyberswap-elastic/ethereum/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/ethereum/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/fantom/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/kyberswap-elastic.module.ts
- src/apps/kyberswap-elastic/optimism/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/polygon/kyberswap-elastic.farm.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/polygon/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- Updates addresses for liquidity and farm positions
- Update ABIs and regenerate contract interfaces
> fix(kyberswap-elastic): Update addresses and abis

- src/apps/looks-rare/ethereum/looks-rare.farm.contract-position-fetcher.ts
- Remove Standard Method's APY
> fix(looks-rare): Remove standard method apy

- src/apps/jones-dao/arbitrum/jones-dao.strategy.token-fetcher.ts
- Fix strategy token price per share
> fix(jones-dao): Fix strategy token price per share

- src/apps/uniswap-v3/common/uniswap-v3.liquidity.abstract.contract-position-builder.ts
- src/apps/uniswap-v3/common/uniswap-v3.liquidity.contract-position-builder.ts
- src/apps/uniswap-v3/common/uniswap-v3.liquidity.utils.ts
> fix(uniswap-v3): Linting

- src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
- Temporary replace current subgraph with the development one until the indexing issues are resolved
> fix(uniswap-v2): Temporary replace subgraph url until indexing issues are fixed

- src/apps/arrakis/common/arrakis.pool.token-fetcher.ts
- src/apps/balancer-v1/ethereum/balancer-v1.pool.token-fetcher.ts
- src/apps/bancor-v3/ethereum/bancor-v3.pool.token-fetcher.ts
- src/apps/bastion-protocol/aurora/bastion-protocol.pool.token-fetcher.ts
- src/apps/curve/common/curve.pool-dynamic.token-fetcher.ts
- src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts
- src/apps/pancakeswap/common/pancakeswap.pool-dynamic.token-fetcher.ts
- src/apps/rigoblock/common/rigoblock.pool.token-fetcher.ts
- src/apps/unipilot/common/unipilot.vault.token-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
- Early return when supply is ZERO
> fix(app-token-template): Early return when supply is zero

- src/apps/beethoven-x/common/beethoven-x.farm.contract-position-fetcher.ts
- src/apps/beethoven-x/contracts/abis/beethoven-x-gauge.json
- src/apps/beethoven-x/contracts/ethers/BeethovenXGauge.ts
- src/apps/beethoven-x/contracts/ethers/factories/BeethovenXGauge__factory.ts
- src/apps/beethoven-x/contracts/index.ts
- src/apps/beethoven-x/fantom/beethoven-x.pool.token-fetcher.ts
- src/apps/beethoven-x/optimism/beethoven-x.farm.contract-position-fetcher.ts
- Fix farm definitions
- Add missing composable pool factory address
> fix(beethoven-x): Fix farm addressses and add missing composable pool factory

- src/apps/sablier/ethereum/sablier.stream-legacy.contract-position-fetcher.ts
- src/apps/sablier/ethereum/sablier.stream.contract-position-fetcher.ts
A user is seeing an unexpected balance, but it seems like this is just a legacy balance that perhaps isn't shown in the Sablier UI anymore. Label the stream ID so they can find out how to claim their funds.
> feat(sablier): Append stream ID to label

- src/apps/thales/arbitrum/thales.amm.contract-position-fetcher.ts
- src/apps/thales/optimism/thales.amm.contract-position-fetcher.ts
Overtime Parlay LP for thales stakers
On OP: 0x324Fbd9536bf3d77d36137310fd4abe5130DfEA9
> feat(thales): overtime parlay amm lp

- src/apps/kyberswap-classic/kyberswap-classic.module.ts
- src/apps/kyberswap-elastic/arbitrum/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- src/apps/kyberswap-elastic/binance-smart-chain/kyberswap-elastic.liquidity.contract-position-fetcher.ts
- Update Arbitrum and bsc subgraph url
> fix(kyberswap-elastic): Update arbitrum and bsc subgraph url

- src/apps/teahouse/arbitrum/teahouse.vaults.token-fetcher.ts
- src/apps/teahouse/common/teahouse.vaults.token-fetcher.ts
- src/apps/teahouse/ethereum/teahouse.vaults.token-fetcher.ts
- src/apps/teahouse/optimism/teahouse.vaults.token-fetcher.ts
- Added return types, fixed errors and optimized query filters adding `from block`
> fix(teahouse): Vault token query filter optimization

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- .github/workflows/upload-app-assets.yml
- .npmrc
- .nvmrc
- package.json
- pnpm-lock.yaml
> chore: Upgrade Node to Hydrogen (LTS 18)

- README.md
> feat: Update readme with Node Hydrogen version

- src/apps/dolomite/common/dolomite.contract-position.template.position-fetcher.ts
- src/apps/dolomite/common/utils.ts
- Replaced Subgraph URL + smol refactor
`0x03842b4c71c18188191cad1cb9a8dab32d2eab7e`
> fix(dolomite): Update subgraph URL

- src/apps/stake-dao/ethereum/stake-dao.locker.token-fetcher.ts
- Add PENDLE, FPIS, APW and BPT locker app tokens + gauge positions
> feat(stake-dao): Add Pendle, FPIS, APW and BPT locker tokens

- src/apps/sonne/optimism/sonne.staking.contract-position-fetcher.ts
Claimable velo-v2 (velo v1 can be removed later)
0x324Fbd9536bf3d77d36137310fd4abe5130DfEA9
> feat(sonne): claimable velo-v2 from staking

- src/apps/arrakis/common/arrakis.pool.token-fetcher.ts
- src/apps/balancer-v1/ethereum/balancer-v1.pool.token-fetcher.ts
- src/apps/bancor-v3/ethereum/bancor-v3.pool.token-fetcher.ts
- src/apps/bastion-protocol/aurora/bastion-protocol.pool.token-fetcher.ts
- src/apps/curve/common/curve.pool-dynamic.token-fetcher.ts
- src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts
- src/apps/pancakeswap/common/pancakeswap.pool-dynamic.token-fetcher.ts
- src/apps/rigoblock/common/rigoblock.pool.token-fetcher.ts
- src/apps/unipilot/common/unipilot.vault.token-fetcher.ts
- src/position/template/app-token.template.position-fetcher.ts
This reverts commit 9d872a44913035741e302ab9e928c040a0cd67ce.
> revert(app-token-template): Early return when supply is zero (#2770)

- src/apps/polynomial/optimism/polynomial.smart-wallet.contract-position-fetcher.ts
USDT and DAI deposited into smart wallet
> feat(polynomial): Smart Wallet USDT/DAI balance

- src/apps/curve/common/curve.factory-pool-v2.token-fetcher.ts
- src/apps/curve/common/curve.pool-dynamic-v2.token-fetcher.ts
- src/apps/curve/ethereum/curve.crv-usd-pool.token-fetcher.ts
- src/apps/curve/ethereum/index.ts
- Add crvUSD pools 
- Renamed 'new factory' to 'factory-v2'
> feat(studio): Add Curve crvUSD pools

- src/multicall/multicall.registry.ts
- Update multicall contract address on Base network
> fix(multicall): Update multicall contract address on Base network

- src/multicall/multicall.registry.ts
> fix(multicall): Update multicall address on Base

- src/apps/halofi/common/halofi.game.constants.ts
> feat: adds support to read contract versions dynamically

- src/apps/curve/ethereum/curve.vesting-escrow.contract-position-fetcher.ts
- Updated vesting escrow contract address
`0x7a16ff8270133f063aab6c9977183d9e72835428`
> fix(curve): Update vesting escrow contract address

- src/apps/uniswap-v3/base/uniswap-v3.liquidity.abstract.contract-position-builder.ts
- src/apps/uniswap-v3/base/uniswap-v3.liquidity.contract-position-builder.ts
- src/apps/uniswap-v3/base/uniswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/uniswap-v3/uniswap-v3.module.ts
- Add uniswap-v3 on Base
** Position won't be showing on the app explorer, but it's temporary until there's a subgraph available 
`0x69e67aad5495a48c4ef3f770d93a99935e1dc90d`
> feat(uniswap-v3): Add Uniswap-v3 on Base

- src/apps/vendor-finance/arbitrum/vendor-finance.pool-v2.contract-position-fetcher.ts
- src/apps/vendor-finance/common/vendor-finance.pool-v2.contract-position-fetcher.ts
- src/apps/vendor-finance/common/vendor-finance.pool.contract-position-fetcher.ts
- src/apps/vendor-finance/common/vendor-finance.pool.types.ts
- src/apps/vendor-finance/ethereum/vendor-finance.pool-v2.contract-position-fetcher.ts
- src/apps/vendor-finance/vendor-finance.module.ts
> fix(vendor-finance): Linting

- src/apps/index-coop/ethereum/index-coop.index.token-fetcher.ts
Adding Index Coop's Money Market Index token
Adding Index Coop's $icSMMT token
idk what this means really, but you can find the Money Market Index on coingecko at https://www.coingecko.com/en/coins/money-market-index
> feat(index-coop): Add Money Market Index ($icSMMT)

- src/apps/curve/ethereum/curve.crv-usd-pool-gauge.contract-position-fetcher.ts
- src/apps/curve/ethereum/index.ts
- Add crvUSD pool gauge
`0x7a16ff8270133f063aab6c9977183d9e72835428`
> fix(curve): Add crvUsd pool gauge positions

- src/apps/jarvis/polygon/jarvis.synth.token-fetcher.ts
- src/apps/pendle-v2/common/pendle-v2.standardized-yield.token-fetcher.ts
- src/apps/pendle-v2/pendle-v2.module.ts
- src/apps/wombat-exchange/common/wombat-exchange.pool.token-fetcher.ts
Filter out some duplicate definitions in responses.
> feat(studio): Filter out some duplicate definitions in responses

- src/apps/balancer-v2/ethereum/balancer-v2.ve-bal-rewards.contract-position-fetcher.ts
> fix(balancer-v2): Fix label

- src/apps/balancer-v2/avalanche/balancer-v2.boosted.token-fetcher.ts
- src/apps/balancer-v2/avalanche/balancer-v2.farm.contract-position-fetcher.ts
- src/apps/balancer-v2/avalanche/balancer-v2.pool.token-fetcher.ts
- src/apps/balancer-v2/balancer-v2.module.ts
- src/apps/balancer-v2/base/balancer-v2.boosted.token-fetcher.ts
- src/apps/balancer-v2/base/balancer-v2.farm.contract-position-fetcher.ts
- src/apps/balancer-v2/base/balancer-v2.pool.token-fetcher.ts
- Support Balancer-v2 positions on Base and Avalanche
> feat(balancer-v2): Support Avalanche and Base

- src/apps/mux/common/mux.perp.contract-position-fetcher.ts
- src/apps/mux/common/utils.ts
> fix(mux): Fix perp balances

- src/apps/y2k-finance/arbitrum/y2k-finance.farm-v1.contract-position-fetcher.ts
- src/apps/y2k-finance/arbitrum/y2k-finance.mint-v1.contract-position-fetcher.ts
- src/apps/y2k-finance/arbitrum/y2k-finance.mint-v2.contract-position-fetcher.ts
- src/position/selectors/app-token-selector.interface.ts
- src/position/selectors/token-dependency-selector.interface.ts
- src/position/template/app-token.template.position-fetcher.ts
- src/position/template/app-token.template.types.ts
- src/position/template/contract-position.template.types.ts
- `tokenId?: number => tokenId?: string`
> fix(position): Update tokenId's type to String

- src/apps/tenderize/common/tenderize.swap.token-fetcher.ts
- src/apps/tenderize/common/tenderize.tender.token-fetcher.ts
- src/apps/tenderize/common/tenderize.token-definition-resolver.ts
- Endpoint used for fetching APY doesn't exist anymore
> fix(tenderize): Remove code fetching APY externally

- src/apps/balancer-v2/common/balancer-v2.boosted.token-fetcher.ts
Some boosted app tokens throws on `getWrappedTokenRate()`
> fix(balaner-v2): Fix boosted app tokens price per share

- src/apps/vendor-finance/base/vendor-finance.pool-v2.contract-position-fetcher.ts
- src/apps/vendor-finance/vendor-finance.module.ts
Adds support for Vendor V2 Lending pools on the Base network.
`pnpm dev`
Visit: `http://localhost:5001/apps/vendor-finance/balances?addresses%5B%5D=0x18252F28234C010Cf3353A82f3cBe71DB1B74773&network=base`
> feat(vendor-finance): Adds Coinbase Base network support for Vendor V2 Pools

- src/apps/dopex/arbitrum/dopex.ssov-v3-option.token-fetcher.ts
`OptionValue` can return 0 resulting in 💥
> fix(dopex): Fix SSOV V3 option price

- src/apps/yearn/common/yearn.vault.token-definitions-resolver.ts
- Fix Yearn app integraiton (ydeamon prod environment is currently down)
> fix(yearn): Update url fetching vaults definitions

- src/apps/sonne/base/sonne.borrow.contract-position-fetcher.ts
- src/apps/sonne/base/sonne.position-presenter.ts
- src/apps/sonne/base/sonne.supply.token-fetcher.ts
- src/apps/sonne/sonne.module.ts
- Sonne lending markets on Base
> feat(sonne): Add lending markets on Base

- src/apps/curve/base/curve.child-liquidity-gauge.contract-position-fetcher.ts
- src/apps/curve/base/curve.factory-crypto-pool.token-fetcher.ts
- src/apps/curve/base/curve.factory-stable-pool.token-fetcher.ts
- src/apps/curve/base/curve.tricrypto-pool.token-fetcher.ts
- src/apps/curve/base/index.ts
- src/apps/curve/common/curve.pool-dynamic-v2.token-fetcher.ts
- src/apps/curve/common/curve.pool-dynamic.token-fetcher.ts
- src/apps/curve/curve.module.ts
On hold until Curve'a API support Base (allowing us to track volume)
> feat(curve): Add positions on Base

- src/apps/kwenta/kwenta.module.ts
- src/apps/kwenta/optimism/kwenta.escrow-v2.contract-position-fetcher.ts
Display unstaked escrowed kwenta balances
0x324Fbd9536bf3d77d36137310fd4abe5130DfEA9
> feat(kwenta): escrow v2

- src/apps/silo-finance/common/silo-finance.incentives.contract-position-fetcher.ts
> fix(silo-finance): Update groupId to target app tokens implemented using ATI

- src/app-toolkit/constants/address.ts
- src/position/template/app-token.template.position-fetcher.ts
> fix(template): early return for dead address

- .github/PULL_REQUEST_TEMPLATE.md
> fix(studio): Fix contributing guidelines link

- src/apps/angle/common/angle.api.ts
- src/apps/angle/ethereum/angle.vault.contract-position-fetcher.ts
Reduced external dependencies as much as possible and fixed huge supplied balances
> fix(angle): Reduce external dependencies on vault balances

- src/apps/pool-together-v5/common/pool-together-v5.prize-vault.token-fetcher.ts
- src/apps/pool-together-v5/common/pool-together.v5.constants.ts
- src/apps/pool-together-v5/optimism/pool-together-v5.prize-vault.token-fetcher.ts
- src/apps/pool-together-v5/pool-together-v5.module.ts
> fix(pool-together-v5): Linting

- src/apps/mux/arbitrum/mux.mux-lp-staking.contract-position-fetcher.ts
- src/apps/mux/mux.module.ts
> feat(mux): Add MuxLP Staking

- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.borrow.contract-position-fetcher.ts
- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.n-token.token-fetcher.ts
- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.p-cash.token-fetcher.ts
- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.p-debt.token-fetcher.ts
- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.supply.contract-position-fetcher.ts
- src/apps/notional-finance-v3/notional-finance-v3.module.ts
> fix(notional-finance-v3): Cleanup

- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.p-cash.token-fetcher.ts
> fix(notional-finance-v3): Fix pricePerShare

- src/apps/convex/ethereum/convex.stash-token-wrapped.token-fetcher.ts
> feat(convex): Add WstETH stash token

- src/apps/trader-joe/avalanche/trader-joe.chef-v2-farm.contract-position-fetcher.ts
- src/apps/trader-joe/avalanche/trader-joe.chef-v3-farm.contract-position-fetcher.ts
> fix(trader-joe): Fix reward balances

- src/apps/wombat-exchange/arbitrum/wombat-exchange.pool.token-fetcher.ts
- src/apps/wombat-exchange/binance-smart-chain/wombat-exchange.pool.token-fetcher.ts
- src/apps/wombat-exchange/common/wombat-exchange.pool.token-fetcher.ts
Add missing wombat exchange pools (required for Magpie)
> feat(wombat-exchange): Add new pools

- src/apps/index-coop/ethereum/index-coop.index.token-fetcher.ts
Added 2 Index Coop assets
- [ x] I have followed the [Contributing Guidelines](https://github.com/Zapper-fi/studio/blob/main/CONTRIBUTING.md)
- [ x] (optional) As a contributor, my Ethereum address/ENS is: crews.eth
- [ x] (optional) As a contributor, my Twitter handle is: @theyoungcrews
I just added two token addresses
> feat(index-coop): Add ic21 and cdETI

- src/apps/aave-amm/common/aave-amm.lending.template.token-fetcher.ts
- src/apps/clearpool/common/clearpool.pool-definition-resolver.ts
- src/apps/curve/ethereum/curve.voting-escrow.contract-position-fetcher.ts
- src/apps/keeper/ethereum/keeper.vest.contract-position-fetcher.ts
- src/apps/morpho/ethereum/morpho.morpho-aave-v2.contract-position-fetcher.ts
Few more that slipped through.
> fix(studio): Fix remaining viem migration regressions

- src/apps/raft/common/raft.position.contract-position-fetcher.ts
Missing types on input params = no type safety
> fix(raft): Fix Raft regression

- src/apps/morpho/ethereum/morpho.morpho-aave-v2.contract-position-fetcher.ts
- src/apps/morpho/ethereum/morpho.morpho-aave-v3.contract-position-fetcher.ts
- src/apps/morpho/utils/P2PInterestRates.ts
> fix(morpho): Fix regressions on APY calculations

- src/apps/mux/common/utils.ts
> fix(mux): Fix destructure of assets

- src/apps/vector-finance/avalanche/vector-finance.farm.contract-position-fetcher.ts
- src/apps/vector-finance/vector-finance.module.ts
- src/position/template/master-chef-v2.template.contract-position-fetcher.ts
- src/position/template/master-chef.template.contract-position-fetcher.ts
Fix incorrect usage of is multicall underlying error.
> fix(vector-finance): Fix failing deposit token call

- src/apps/dopex/arbitrum/dopex.ssov-v3-option.token-fetcher.ts
Catch the revert error and return 0.
> fix(dopex): Catch error for calling optionValue

- src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
> fix(uniswap-v2): Update Uniswap v2 subgraph url

- src/apps/curve/ethereum/curve.crypto-pool.token-fetcher.ts
> fix(curve): Filter out hacked crypto pool

- src/apps/aura/base/aura.lp-farm.contract-position-fetcher.ts
- src/apps/aura/common/aura.farm.contract-position-fetcher.ts
- src/apps/aura/ethereum/aura.aura-bal-staking.contract-position-fetcher.ts
- src/apps/aura/ethereum/aura.lp-farm.contract-position-fetcher.ts
- src/network-provider/network-provider.registry.ts
- Extract base reward token addresses into abstract vars
> fix(aura): Fix Aura Lp Staking on Base

- src/apps/aura/arbitrum/aura.lp-farm.contract-position-fetcher.ts
- src/apps/aura/aura.module.ts
- src/apps/aura/optimism/aura.lp-farm.contract-position-fetcher.ts
- Added Lp staking position and balances (arb + op)
> feat(aura): Added Lp Staking positon on Arbitrum and Optimism

- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.borrow.contract-position-fetcher.ts
- src/apps/notional-finance-v3/arbitrum/notional-finance-v3.supply.contract-position-fetcher.ts
> fix(notional-finance-v3): Fix supply and borrow position key

- src/apps/aave-safety-module/ethereum/aave-safety-module.stk-abpt-claimable.contract-position-fetcher.ts
- src/apps/aave-v2/common/aave-v2.claimable.contract-position-fetcher.ts
- src/apps/across/common/across.pool-v1.token-fetcher.ts
- src/apps/across/common/across.pool-v2.token-fetcher.ts
- src/apps/api3/ethereum/api3.staking.contract-position-fetcher.ts
- src/apps/arbor-finance/ethereum/arbor-finance.bond.token-fetcher.ts
- src/apps/badger/common/badger.claimable.contract-position-fetcher.ts
- src/apps/badger/common/badger.claimable.rewards-resolver.ts
- src/apps/camelot/arbitrum/camelot.dividend.contract-position-fetcher.ts
- src/apps/cask-protocol/common/cask-protocol.wallet.token-fetcher.ts
- src/apps/chicken-bond/ethereum/chicken-bond.bond.contract-position-fetcher.ts
- src/apps/ease/common/ease.rca.token-fetcher.ts
- src/apps/gains-network/common/gains-network.locked.contract-position-fetcher.ts
- src/apps/geist/fantom/geist.incentives.contract-position-fetcher.ts
- src/apps/hex/ethereum/hex.stake.contract-position-fetcher.ts
- src/apps/idle/ethereum/idle.best-yield.contract-position-fetcher.ts
- src/apps/impermax/common/impermax.borrow.contract-position-fetcher.ts
- src/apps/insurace/common/insurace.mining.token-fetcher.ts
- src/apps/iq/ethereum/iq.hiiq.contract-position-fetcher.ts
- src/apps/lyra-avalon/common/lyra-avalon.stk-lyra-claimable.contract-position-fetcher.ts
- src/apps/opnx/ethereum/opnx.veox.contract-position-fetcher.ts
- src/apps/penguin/avalanche/penguin.vault-claimable.contract-position-fetcher.ts
- src/apps/plutus/arbitrum/plutus.tge-claimable.contract-position-fetcher.ts
- src/apps/pool-together-v3/common/pool-together-v3.airdrop.contract-position-fetcher.ts
- src/apps/pool-together-v3/common/pool-together-v3.claimable.contract-position-fetcher.ts
- src/apps/rook/ethereum/rook.claimable.contract-position-fetcher.ts
- src/apps/silo-finance/common/silo-finance.incentives.contract-position-fetcher.ts
- src/apps/tokemak/ethereum/tokemak.claimable.contract-position-fetcher.ts
- src/apps/zharta/ethereum/zharta.lending-pool-core.contract-position-fetcher.ts
> chore(apps): Clean up labels

- src/apps/hidden-hand/common/hidden-hand.rewards-resolver.ts
Add missing market identifiers to fetch claimed amounts correctly
> fix(hidden-hand): add market identifiers to fetch claimed amounts

- src/apps/angle/common/angle.api.ts
- src/apps/homora-v2/common/homora-v2.farm.contract-position-fetcher.ts
- src/apps/polynomial/common/polynomial.api.ts
- src/apps/ren/common/ren.api.client.ts
- src/apps/robo-vault/common/robo-vault.api.client.ts
- src/apps/synthetix/common/synthetix.mintr.snx-holders.cache.ts
- src/cache/cache.decorator.ts
Remove the need to specify caching instances
> feat(general): Remove caching instances

- src/apps/defiedge/common/defiedge.strategy.token-fetcher.ts
Some tokens have super weird symbol which can't be resolved..
> fix(defiedge): Fix strategy symbol

- src/apps/lyra-avalon/optimism/lyra-avalon.options.contract-position-fetcher.ts
With the new subgraphs, logic for balances is now the same on both networks (Optimism + Arbitrum)
> fix(lyra-finance): Fix options balances on Optimism

- src/apps/pickle/common/pickle.api.jar-registry.ts
- src/apps/pickle/common/pickle.jar-univ3.token-fetcher.ts
- src/apps/pickle/common/pickle.jar.token-fetcher.ts
- src/apps/pickle/ethereum/pickle.single-staking-farm.contract-position-fetcher.ts
- src/apps/pickle/fantom/pickle.jar.token-fetcher.ts
- src/apps/pickle/pickle.module.ts
- Updated endpoint we use to fetch jars addresses
> fix(pickle): Fix jars definitions

- src/apps/reaper/arbitrum/reaper.vault.token-fetcher.ts
- src/apps/reaper/binance-smart-chain/reaper.vault.token-fetcher.ts
- src/apps/reaper/common/reaper.vault.cache-manager.ts
- src/apps/reaper/common/reaper.vault.token-fetcher.ts
- src/apps/reaper/reaper.module.ts
- Fixed cache manager
- Added Vaults on BSC and Arbitrum
> fix(reaper): Fix vault definitions

- src/apps/uniswap-v3/base/uniswap-v3.liquidity.contract-position-fetcher.ts
- src/apps/uniswap-v3/common/uniswap-v3.liquidity.contract-position-builder.ts
> fix(uniswap-v3): Cleanup and update subgraph url

- src/apps/mux/arbitrum/mux.mux-lp-staking.contract-position-fetcher.ts
> fix(mux): Fix lp staking token definitions

- src/apps/abracadabra/arbitrum/abracadabra.arbitrum.constants.ts
Added GmLINK Cauldron + Linting
> feat(abracadabra): Added GmSOL cauldron

- src/apps/velodrome-v2/common/velodrome-v2.addresses-resolver.ts
> fix(velodrome-v2): Revert groupId update
