cli/strings/strings.ts
Running `yarn studio create-app` and input `a-b-c` as ID of the app and the following error will be encountered.
```
yarn run v1.22.18
$ ./studio.sh create-app
What is the name of the app : abc
What is the ID of the app  [abc]: a-b-c
What is the description of your app : abc
What is the URL of your app : abc.com
? Select networks supported by the app ethereum
SyntaxError: ',' expected. (6:18)
4 | import { Network } from '~types/network.interface';
5 |
> 6 | export const A_B C_DEFINITION = {
|                  ^
7 |   id: 'a-b-c',
8 |   name: 'abc',
9 |   description: 'abc',
at $e (/home/haotongye/Repos/studio/node_modules/.pnpm/prettier@2.6.0/node_modules/prettier/parser-typescript.js:1:15901)
at vU (/home/haotongye/Repos/studio/node_modules/.pnpm/prettier@2.6.0/node_modules/prettier/parse …
```
=> fix(cli): string upperCase and kebabCase error

.github/workflows/publish.yml
Revert message in a previous commit had double quotes, which is failing the build.
Publish step succeeds.
=> fix: Use single quotes for release body on publish in case commit message has double quotes

.github/workflows/release-please.yml
thebritican/fetch-latest-release@v1 doesn't exist anymore
=> ci: Rugged by deprecated github action version

src/apps/olympus/olympus.module.ts
Some weird infinite loop occurring that is crashing the app when Olympus is activated. Temporarily prevent it from being loaded until we can look into this further.
`yarn dev` with `olympus` in `ENABLED_APPS` doesn't crash the application.
=> fix: Temporarily disable Olympus

src/cache/cache-on-interval.service.ts, src/cache/cache.service.ts
So the process doesn't crash when a job fails in background
=> fix: Catch @Cache & @CacheOnInterval errors

src/apps/tokemak/ethereum/tokemak.tvl-fetcher.ts, src/apps/tokemak/tokemak.module.ts
Would have broken when consumed into Zapper API
=> fix(tokemak): Use App Toolkit instead of position service

src/apps/olympus/ethereum/olympus.balance-fetcher.ts, src/apps/olympus/ethereum/olympus.bond.contract-position-fetcher.ts, src/apps/olympus/helpers/olympus.bond-v1.contract-position-balance-helper.ts, src/apps/olympus/helpers/olympus.bond-v2.contract-position-balance-helper.ts, src/apps/olympus/helpers/olympus.bond.contract-position-helper.ts, src/apps/olympus/olympus.module.ts, src/apps/tokemak/ethereum/tokemak.balance-fetcher.ts
- Olympus bond balance helper is split into V1 and V2 helpers (V1 helper is still being used in Zapper API for Olympus V1 forks)
- Keep bond position fetcher generic since its also being used for Olympus V1 forks
- Fix linting in Tokemak
[gOHM Bonds](http://localhost:5001/apps/olympus/balances?addresses[]=0x7ea8e1b9feb9f6a3420538a21497180866e44765)
=> fix: Split Olympus bond balance helper for v1 and v2 bonds, keep bond position fetcher generic, fix linting

src/app-toolkit/helpers/master-chef/master-chef.default.reward-token-reward-rate-strategy.ts, src/apps/naos/ethereum/naos.farm.contract-position-fetcher.ts
We support reward per block and reward per second, so rename `resolveTotalRewardPerBlock` to `resolveTotalRewardRate`.
N/A. Refactor.
=> fix: Rename resolveTotalRewardPerBlock to resolveTotalRewardRate

src/apps/olympus/index.ts, src/apps/synthetix/index.ts, src/apps/uniswap-v2/index.ts
- Add index files for simple importing of helpers in Zapper API
Consume in Zapper API.
=> fix: Create index files for Uniswap V2 and Olympus modules

src/apps/illuvium/ethereum/illuvium.balance-fetcher.ts, src/apps/illuvium/ethereum/illuvium.farm.contract-position-fetcher.ts, src/apps/illuvium/ethereum/illuvium.migration-manager.ts, src/apps/illuvium/illuvium.module.ts
- Missing await in V1 balances
- Add migration manager class (not used right now) for tracking migrations... might be useful, but not used in Illuvium FE anyway
http://localhost:5001/apps/illuvium/balances?addresses[]=0x1f279aad56278d67d31ca1c89480ac7152e5c45a
Tested with Impersonator on Illuvium staking, final amount matches.
=> fix(illuvium): Fix missing await in v1 staked balances

package.json, scripts/run-cli.js
Need to provide a way to switch scripts between windows and *nix like envs
=> chore: Add script intermediary

src/position/position-source/position-source.registry.ts
- Unprimed cache returns undefined; default to an empty array in `getPositions` so that callers run successfully
No errors when starting `ENABLED_APPS` as `pickle,yearn,curve,synthetix`
=> fix: Fix undefined positions when cache is not primed

.github/workflows/trigger-studio-docs-deploy.yml
When `CHANGELOG.md` is updated, trigger a deployment on Studio Docs so that https://studio-docs.zapper.fi/docs/CHANGELOG is updated.
=> build: Trigger Studio Docs deployment when CHANGELOG.md is updated

src/apps/balancer-v2/helpers/balancer-v2.pool.token-helper.ts, src/apps/balancer-v2/index.ts
=> fix(balancer): Add missing exports for zapper api

pnpm-lock.yaml, src/position/dto/get-positions-query.dto.ts
The nest swagger module would not pass in the required `[]` to the query param. Instead, we will explicitly set the name at doc level.
Although the string is url-encoded, it'll work just as expected.
=> chore: explicitely set groupIds swagger property to groupIds[]

src/apps/dfx/dfx.definition.ts
Small fix to capitalize the DFX app name.
Name displays properly in DFX app page.
=> fix: Capitalize DFX app name

src/apps/curve/ethereum/curve.pool.token-fetcher.ts
Convex sCHF ibCHF & sAUD ibAUD positions were not displayed because synths were not used in curve's deps
=> fix(convex): Add synths as deps for factory pools

src/apps/klima/index.ts, src/apps/klima/klima.definition.ts, src/apps/klima/klima.module.ts, src/apps/klima/polygon/klima.balance-fetcher.ts, src/apps/klima/polygon/klima.bond.contract-position.ts, src/apps/klima/polygon/klima.s-klima.token-fetcher.ts, src/apps/klima/polygon/klima.ws-klima.token-fetcher.ts
Migrate Klima (Olympus fork) to Studio
[http://localhost:5001/apps/klima/positions?groupIds%5B%5D=bond&network=polygon](http://localhost:5001/apps/klima/positions?groupIds%5B%5D=bond&network=polygon)
[http://localhost:5001/apps/klima/tokens?network=polygon&groupIds%5B%5D=sklima&groupIds%5B%5D=wsKlima](http://localhost:5001/apps/klima/tokens?network=polygon&groupIds%5B%5D=sklima&groupIds%5B%5D=wsKlima)
=> feat: Migrate Klima to Studio

src/apps/gro/gro.definition.ts
Required for correctly typing the `ArrayOfOneOrMore` type.
N/A
=> fix(gro): Add missing appDefinition wrapper to fix failing build

src/token/token.service.ts
If the cache is not set with a TTL, then the prices cache is never cleared. This was an issue for a user that needed the THALES token. We added the token, but their prices response still didn't have THALES token because it was always reading from cache.
=> fix(prices): Cache prices for 1 minute

cli/commands/codegen-app.ts
Module code generation was behind. Fix it!
`yarn studio create-app`
=> fix(codegen): Update module codegen

pnpm-lock.yaml, src/apps/balancer-v2/arbitrum/balancer-v2.balance-fetcher.ts, src/apps/balancer-v2/arbitrum/balancer-v2.staked.contract-position-fetcher.ts, src/apps/balancer-v2/balancer-v2.module.ts, src/apps/balancer-v2/polygon/balancer-v2.balance-fetcher.ts, src/apps/balancer-v2/polygon/balancer-v2.staked.contract-position-fetcher.ts
Add missing Gauge vaults for Arbitrum and Polygon
[http://localhost:5001/apps/balancer-v2/positions?groupIds%5B%5D=farm&network=arbitrum](http://localhost:5001/apps/balancer-v2/positions?groupIds%5B%5D=farm&network=arbitrum)
=> feat: Add missing Balancer-v2 farms in Polygon and Arbitrum

src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
Fixes this [issue](https://github.com/Zapper-fi/support/issues/210). 
Missing Uniswap-V2 pool causing Mirror mSLV/UST position not to be available.
There was a fix attempt but the address was incorrect.
=> fix(uniswap-v2): Fix required pool address

src/apps/pancakeswap/binance/pancakeswap.balance-fetcher.ts
We need to subtract the boosted share amount. See [here](https://github.com/pancakeswap/pancake-frontend/blob/cbb404da0439024f691c3293b4ee36efe7ac8a54/src/state/pools/helpers.ts#L104) for details.
http://localhost:5001/apps/pancakeswap/balances?addresses[]=0xfbE849ea94Aa5Acd53C83776449620B1B51976DB&network=binance-smart-chain
=> fix(pancakeswap): Fix staked cake balance

src/apps/curve/arbitrum/curve.farm.contract-position-fetcher.ts, src/apps/curve/avalanche/curve.farm.contract-position-fetcher.ts, src/apps/curve/fantom/curve.farm.contract-position-fetcher.ts, src/apps/curve/gnosis/curve.farm.contract-position-fetcher.ts, src/apps/curve/optimism/curve.balance-fetcher.ts, src/apps/curve/optimism/curve.farm.contract-position-fetcher.ts, src/apps/curve/polygon/curve.farm.contract-position-fetcher.ts
Use the child liquidity gauge factory to resolve child liquidity gauges.
Staked factory sUSD+3CRV in factory liquidity gauge 😓 
[0x5c461a0c595d6b2a4b0f4a42fd55be7aaed8af80](https://optimistic.etherscan.io/address/0x5c461a0c595d6b2a4b0f4a42fd55be7aaed8af80)
https://optimism.curve.fi/pools?see=0x5c461a0c595d6b2a4b0f4a42fd55be7aaed8af80
http://localhost:5001/apps/curve/balances?addresses[]=0x5c461a0c595d6b2a4b0f4a42fd55be7aaed8af80&network=optimism
=> feat(curve): Add child liquidity gauges to Optimism

src/apps/curve/arbitrum/curve.farm.contract-position-fetcher.ts, src/apps/curve/avalanche/curve.farm.contract-position-fetcher.ts, src/apps/curve/curve.module.ts, src/apps/curve/fantom/curve.farm.contract-position-fetcher.ts, src/apps/curve/gnosis/curve.farm.contract-position-fetcher.ts, src/apps/curve/harmony/curve.farm.contract-position-fetcher.ts, src/apps/curve/helpers/curve.rewards-only-gauge.reward-token-strategy.ts, src/apps/curve/helpers/curve.rewards-only-gauge.roi-strategy.ts, src/apps/curve/index.ts, src/apps/curve/optimism/curve.farm.contract-position-fetcher.ts, src/apps/curve/polygon/curve.farm.contract-position-fetcher.ts
Legacy sidechain/L2 Curve gauges were called "RewardsOnlyGauge". Do not confuse this with Liquidity Gauge V2.
No regressions expected.
=> refactor(curve): Rename rewards only gauge strategies to match the Curve naming

src/apps/polynomial/optimism/polynomial.balance-fetcher.ts
Did some more operations on polynomial vaults since the pr to do more testing - found that balances pending withdrawal are not being tracked.
curl -X 'GET' \
'http://localhost:5001/apps/polynomial/positions?network=optimism&groupIds%5B%5D=vaults' \
-H 'accept: */*'
=> polynomial: track vault balances in withdrawal

src/app-toolkit/helpers/position/single-staking-farm.contract-position-helper.ts, src/apps/polynomial/optimism/polynomial.vaults.contract-position-fetcher.ts
sorry, another polynomial small fix
```
gautham — Today at 4:33 AM
Ser nice job on the zapper pr
Is there anyway we can change the name of the vault from staked sETH to Eth covered call
Image
gautham — Today at 4:43 AM
The image is also a bit low resolution
tonz — Today at 11:59 AM
i think every image is 150x150, but you can submit a pr to update this image if you have a better one https://github.com/Zapper-fi/studio/blob/main/src/apps/polynomial/assets/logo.png
GitHub
[studio/logo.png at main · Zapper-fi/studio](https://github.com/Zapper-fi/studio/blob/main/src/apps/polynomial/assets/logo.png)
Zapper App Integrations. Contribute to Zapper-fi/studio development by creating an account on GitHub.
studio/logo.png at main · Zapper-fi/studio
ill submit a pr to change the name from staked to …
```
=> fix: update polynomial vault name

src/apps/impermax/impermax.definition.ts
=> fix: fix typo in impermax definition

src/apps/qi-dao/helpers/qi-dao.vault.position-helper.ts, src/position/position.interface.ts
Adding a dataProps to qi-dao vault position to specify the underlying asset standard. In this case we want to expose that the underlying asset is of an ERC721 (NFT) type.
=> feat(qi-dao): Add assetStandard to vault dataProps

src/apps/compound/ethereum/compound.balance-fetcher.ts, src/apps/impermax/helpers/impermax.balance-helper.ts
Prevent the breaking change for Compound losing the C-Ratio in the Zapper FE.
=> fix(compound): Put meta on app level for Impermax instead of Compound

src/apps/impermax/ethereum/impermax.collateral.token-fetcher.ts
Fix a typo with `Arbitrum` instead of `Ethereum` in the fetcher.
=> fix(impermax): Fix wrong Network in fetcher

src/app-toolkit/helpers/master-chef/master-chef.contract-position-helper.ts, src/app-toolkit/helpers/position/single-staking-farm.contract-position-helper.ts, src/apps/dfx/ethereum/dfx.staking.contract-position-fetcher.ts, src/apps/dfx/polygon/dfx.staking.contract-position-fetcher.ts, src/apps/symphony/avalanche/symphony.tvl-fetcher.ts, src/apps/symphony/avalanche/symphony.yolo.contract-position-fetcher.ts, src/apps/symphony/helpers/types.ts, src/apps/symphony/polygon/symphony.tvl-fetcher.ts, src/apps/symphony/polygon/symphony.yolo.contract-position-fetcher.ts, src/apps/thales/optimism/thales.escrow.contract-position-fetcher.ts, src/apps/thales/optimism/thales.pool2.contract-position-fetcher.ts, src/apps/thales/optimism/thales.staking.contract-position-fetcher.ts, src/apps/tokemak/ethereum/tokemak.tvl-fetcher.ts
Added a liquidity dataProps which holds the same value as TotalValueLocked. It will be easier to rename/remove TotalValueLocked in studio and in api.
=> chore: added liquidity dataPropps with same value as TotalValueLocked in order to rename/remove TotalValueLocked in zapper-api and studio

src/apps/lyra-avalon/optimism/helpers/consts.ts, src/apps/lyra-avalon/optimism/lyra-avalon.balance-fetcher.ts, src/apps/lyra-avalon/optimism/lyra-avalon.options.contract-position-fetcher.ts, src/apps/lyra-avalon/optimism/lyra-avalon.pool.token-fetcher.ts
https://github.com/Zapper-fi/studio/pull/526#discussion_r883784390
=> fix: lyra-avalon - address post merge comments

src/apps/olympus/ethereum/olympus.g-ohm.token-fetcher.ts, src/apps/olympus/ethereum/olympus.s-ohm-v1.token-fetcher.ts, src/apps/olympus/ethereum/olympus.s-ohm.token-fetcher.ts
Wrong group were set for sOhm and sOhm v1 on Ethereum
=> fix(olympus): Fix wrong groups on Ethereum

src/apps/yield-protocol/arbitrum/yield-protocol.lend.token-fetcher.ts, src/apps/yield-protocol/ethereum/yield-protocol.lend.token-fetcher.ts
Really small fix to try to prevent the "-" from rendering before maturity for fyTokens (`lend` group id).
=> fix: yield protocol lend tertiary label

src/apps/tarot/index.ts
=> fix(tarot): Export module

src/apps/compound/helper/compound.borrow.contract-position-helper.ts, src/apps/impermax/arbitrum/impermax.borrow.contract-position-fetcher.ts, src/apps/impermax/ethereum/impermax.borrow.contract-position-fetcher.ts, src/apps/impermax/impermax.module.ts, src/apps/impermax/polygon/impermax.borrow.contract-position-fetcher.ts
Make a resolver for the `cash` contract call. For some protocol using the helper, the `getCash` method does not exist on the borrowable token contract. 
[http://localhost:5001/apps/impermax/positions?groupIds%5B%5D=borrow&network=ethereum](http://localhost:5001/apps/impermax/positions?groupIds%5B%5D=borrow&network=ethereum)
[http://localhost:5001/apps/compound/positions?groupIds%5B%5D=borrow&network=ethereum](http://localhost:5001/apps/compound/positions?groupIds%5B%5D=borrow&network=ethereum)
=> feat(compound): Add resolver in helper method

src/apps/curve/curve.module.ts, src/apps/curve/helpers/curve.crypto-factory-pool.token-helper.ts, src/apps/curve/helpers/curve.liquidity-and-virtual.price-strategy.ts, src/apps/curve/helpers/curve.v2-pool.token-helper.ts
Fix for this [issue](https://github.com/Zapper-fi/support/issues/226). For TriCrypto2 and other v2 Pools, we are using a liquidity based price calculation (`liquidity / supply`). The pool virtual price ignored. The right calculation should be `virtual price * LP token price`.
[http://localhost:5001/apps/curve/tokens?groupIds%5B%5D=pool&network=ethereum](http://localhost:5001/apps/curve/tokens?groupIds%5B%5D=pool&network=ethereum)
=> fix(curve): Use virtual price in v2 Pools price calculation

.github/workflows/ci.yml, package.json
Run lint faster on CI by only linting files changed between the feature branch and `main`.
=> build(lint): Lint only changed files between branch and main

src/apps/uniswap-v2/helpers/uniswap-v2.the-graph.pool-token-address-strategy.ts
Some apps are using the `UniswapV2TheGraphPoolTokenAddressStrategy` helper to perform external query to The Graph. The result is cached for 5 minutes. The problem is the cache has only the `Network` as dynamic parameter, meaning multiple Apps using that helper might have collisions.
I am changing the cache key building strategy to prevent that. Now the network, appId and groupId will be used as part of the cache key.
[http://localhost:5001/apps/uniswap-v2/tokens?network=ethereum&groupIds%5B%5D=pool&api_key=562eee97-e90e-42ac-8e7b-363cdff5cdaa](http://localhost:5001/apps/uniswap-v2/tokens?network=ethereum&groupIds%5B%5D=pool&api_key=562eee97-e90e-42ac-8e7b-363cdff5cdaa)
=> fix(uniswap-v2): Make cache key generic in helper

src/apps/aave-v2/helpers/aave-v2.lending.token-helper.ts
The AAVE-V2 lending helper is multiplying the APY by 100 when adding it the statsItems list. This is causing the value to be off by 100x on the UI because the Frontend is already making that calculation. The value is off on AAVE-V2 and GEIST.
=> fix(aave-v2): Fix APY statsItem in helper

src/position/position-fetcher.registry.ts, src/stats/tvl/tvl.service.ts
This enables `includeInTvl` to work for TVL calculation, when a custom TVL isn't provided.
As a follow-up, custom TVLs will be deprecated in favor of group based TVLs.
=> feat(tvl): Use group based strategy for local TVLs

src/apps/compound/helper/compound.supply.token-helper.ts
Making a resolver in Compound helper to allow app using it to be able to set a different label for the supply/borrow rate.
=> fix(compound): Create resolver for Supply/Borrow rate label

src/app-toolkit/helpers/master-chef/master-chef.contract-position-helper.ts, src/apps/beethoven-x/fantom/beethoven-x.farm.contract-position-fetcher.ts
Change the farm return on investment label to reflect `APR` from beethoven-x app
=> fix(beethoven-x): Update Farm APR label

src/app/app.definition.ts, src/app/app.interface.ts
Add the presentation config to the App definition interface.
This will allow to group certain asset like Supply/Borrow into to the same presentation section
=> chore: Add presentation config to App definition interface

src/apps/iron-bank/iron-bank.definition.ts
=> fix(iron-bank): Add presentation config to Iron Bank

src/app-toolkit/helpers/master-chef/master-chef.contract-position-helper.ts
Removing the `Staked` prefix from the label in the Masterchef helper
=> chore: Remove Staked prefix label on Masterchef helper

src/apps/iron-bank/iron-bank.definition.ts
=> feat(iron-bank): Update empty description

src/apps/aave-v2/helpers/aave-v2.lending.token-helper.ts
Reverting a previous change that removed the `* 100` on the displayed APY. That was happening somewhere else. Now we can properly set the behaviour at the source when building the position.
=> fix(aave-v2): Fix displayed APY

.all-contributorsrc, README.md
=> docs(README): Update contributors

src/apps/enzyme-finance/ethereum/enzyme-finance.vault.token-fetcher.ts, src/apps/pika-protocol/optimism/pika-protocol.balance-fetcher.ts, src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
- Filtered out uniswap-v2 pool with absurd price/supply
- Bump the number of enzyme-finance's vaults fetched
=> fix: filtered out uniswap-v2 pool with absurd price and supply + bump the amount of enzyme finance vault fetched

src/cache/cache.decorator.ts
In order to be consumed properly by Zapper API when using Nest.js' metadata
=> feat(cache): Align @Cache to match Zapper API

src/apps/uniswap-v2/helpers/uniswap-v2.the-graph.pool-token-address-strategy.ts
Cache key builder does not have app ID, network, or group ID. Instead, just use the subgraph URL as the differentiator.
=> feat(uniswap-v2): Build cache key from subgraph URL

src/apps/aave-v2/avalanche/aave-v2.stable-debt.token-fetcher.ts, src/apps/aave-v2/avalanche/aave-v2.variable-debt.token-fetcher.ts, src/apps/aave-v2/ethereum/aave-v2.variable-debt.token-fetcher.ts, src/apps/aave-v2/polygon/aave-v2.stable-debt.token-fetcher.ts, src/apps/aave-v2/polygon/aave-v2.variable-debt.token-fetcher.ts
- Removed borrow prefix on aave-v2 position's label
=> fix: removed 'borrow' prefix on aave-v2 positions

src/apps/pool-together/helpers/pool-together-v3.prize-pool.token-helper.ts, src/apps/pool-together/pool-together.definition.ts
- Split ticket and sponsorship liquidity (pool-together)
- Renamed "Pools" group label to "Deposit" matching Pool-Together's UI
=> fix: split ticket and sponsorship liquidity (pool-together)

src/apps/qi-dao/qi-dao.definition.ts
- Added liquidity on escrowed QI DAO position but forgot to removed the hiddenFromExplorer option 😬
=> fix: escrowed qi-dao position should be shown in explorer

src/apps/mean-finance/helpers/intervals.ts, src/apps/mean-finance/optimism/mean-finance.balance-fetcher.ts, src/apps/mean-finance/optimism/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/optimism/mean-finance.tvl-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.balance-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.tvl-fetcher.ts, src/position/position.utils.ts
- Changes the label for active Mean Finance positions (meaning the have swaps left) from "Swapping WMATIC to USDC" to "Swapping 0.008321 USDC every day to OP". These would 100% be better as a secondary or tertiary label, until there is support for those we would like to show this info on the label. Once tertiary/secondary are enabled we'll move them.
- Adds the "CLAIMABLE" metaType to the "To" token to which you are DCA'ing (basically what we have swapped for the user and they can withdraw on Mean Finance)
http://localhost:5001/apps/mean-finance/balances?addresses[]=0x7AfB052ae7B80aAc6e559281cC261089738b66F6&network=polygon
http://localhost:5001/apps/mean-finance/balances?addresses[]=0xf488aaf75D987cC30a84A2c3b6dA72bd17A0a555&network=optimism
=> feat(mean-finance): improve mean finance label to show position info

src/apps/sturdy/sturdy.definition.ts
Add presentation config to properly display lending related positions (Supply/Borrow) in the same UI section
=> feat(sturdy): add presentation config

src/apps/euler/ethereum/euler.p-token.token-fetcher.ts, src/apps/euler/euler.definition.ts, src/apps/yearn/yearn.definition.ts
- Yearn groupId "farm" has been renamed to governance in a prior PR
- Renamed Euler E Token and D Token to Supply and Borrow (only the labels, not the ids)
=> fix: farms has been renamed to governance

src/apps/yearn/ethereum/yearn.governance.contract-position-fetcher.ts
=> fix(yearn): Fix governance reward token as a Curve dependency

src/apps/rari-fuse/ethereum/rari-fuse.supply.token-fetcher.ts
Arrakis G-UNI token debt wasn't showing.
0x462a63d4405a6462b157341a78fd1babfd3f8065
=> fix(rari-fuse): Add missing Arrakis Finance dependency

src/apps/vvs-finance/vvs-finance.definition.ts
=> fix(vvs-finance): update vvs-finance name definition

src/apps/abracadabra/arbitrum/abracadabra.m-spell.contract-position-fetcher.ts, src/apps/abracadabra/avalanche/abracadabra.m-spell.contract-position-fetcher.ts, src/apps/abracadabra/fantom/abracadabra.m-spell.contract-position-fetcher.ts, src/apps/coslend/helper/coslend.borrow.contract-position-helper.ts, src/apps/coslend/helper/coslend.supply.token-helper.ts
- Removed prefix from Coslend (supply and borrow) position label
=> fix: removed prefix from coslend positions label

src/apps/arrakis/helpers/arrakis.pool.token-helper.ts, src/apps/balancer-v1/ethereum/balancer-v1.token-fetcher.ts, src/apps/balancer-v2/helpers/balancer-v2.pool.token-helper.ts, src/apps/curve/helpers/curve.pool.token-helper.ts, src/apps/unagii/ethereum/unagii.pool.token-fetcher.ts, src/apps/uniswap-v2/helpers/uniswap-v2.pool.token-helper.ts, src/apps/uniswap-v2/helpers/uniswap-v2.the-graph.pool-token-balance-helper.ts
=> feat: add pool ratio to statsItem

src/apps/rari-fuse/ethereum/rari-fuse.borrow.contract-position-balance-fetcher.ts, src/apps/rari-fuse/ethereum/rari-fuse.supply.token-balance-fetcher.ts
Reports from Discord indicated `0xCba1A275e2D858EcffaF7a87F606f74B719a8A93` was failing, and upon investigation, it was a call to the Lens contract that was throwing an error. Luckily, we don't need `getPoolsBySupplierWithData`, but just `getPoolsBySupplier` which does not throw.
This address is still missing bveCVX as collateral because we don't support that token yet in Badger.
=> fix(rari-fuse): Fix failing RPC calls in Rari Fuse

src/apps/symphony/optimism/symphony.balance-fetcher.ts, src/apps/symphony/optimism/symphony.yolo.contract-position-fetcher.ts, src/apps/symphony/symphony.module.ts
Adds Optimism network support for Symphony Finance.
TVL:
http://localhost:5001/apps/symphony/tvl?network=optimism
Contract Positions:
http://localhost:5001/apps/symphony/positions?groupIds%5B%5D=yolo&network=optimism
Balances:
http://localhost:5001/apps/symphony/balances?addresses%5B%5D=0x94db037207f6fb697dbd33524aadffd108819dc8&network=optimism
=> feat(symphony): Symphony Finance Optimism Integration

src/apps/angle/contracts/abis/angle-veangle.json, src/apps/angle/contracts/ethers/factories/AngleVeangle__factory.ts, src/apps/angle/ethereum/angle.perpetuals.contract-position-fetcher.ts, src/apps/angle/ethereum/angle.santoken.token-fetcher.ts, src/apps/angle/ethereum/angle.vaults.contract-position-fetcher.ts, src/apps/mean-finance/optimism/mean-finance.balance-fetcher.ts, src/apps/mean-finance/optimism/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.balance-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.dca-position.contract-position-fetcher.ts
- Fix types in Angle
- Fix address and key in DCA positions
=> fix(mean-finance): Fix types, fix address in DCA positions

src/apps/symphony/symphony.definition.ts
App page on Optimism wasn't loading because we're still using `supportedNetworks` to render application pages pages :rip:
=> fix(symphony): Add missing supported network in definition file

src/apps/rari-fuse/rari-fuse.definition.ts
- Uses the market name as the dynamic label, effectively splitting the markets on the explore page for Rari Fuse
- Each market will have its isolated supply and borrow positions visible as lists
=> feat(rari-fuse): Integrate presentation config for explore page

cli/commands/create-contract-position-fetcher.ts, cli/commands/create-token-fetcher.ts
Should be `GroupType.POSITION` for generating position groups.
=> fix(cli): Fix group generator for contract position groups

src/apps/maple/ethereum/maple.pool.token-fetcher.ts
Fix(maple): maple APYs were off by a factor of a 100
=> fix(maple): fix Maple apy

src/apps/balancer-v2/ethereum/balancer-v2.wrapped-aave.token-fetcher.ts, src/apps/balancer-v2/helpers/balancer-v2.pool.token-helper.ts
Use filtered underlying tokens from building token data, which already have redundant underlying tokens for Aave Linear and Phantom Stable pools removed.
=> fix(balancer-v2): Use filtered underlying tokens

src/apps/coslend/evmos/coslend.supply.token-fetcher.ts
fix [coslend](https://coslend.com/) comptroller address
1. edit/create .env adding ENABLED_APPS="coslend"
2. run pnpm dev to spin up nest server
3. visit dev endpoints below to see result of fetchers to integrate coslend:
- http://localhost:5001/apps/coslend/tokens?network=evmos&groupIds[]=supply
- http://localhost:5001/apps/coslend/positions?network=evmos&groupIds[]=borrow
- http://localhost:5001/apps/coslend/tvl?network=evmos
- http://localhost:5001/apps/coslend/balances?network=evmos&addresses[]=<wallet_address>
=> fix(coslend): update comptroller address

src/apps/rari-fuse/ethereum/rari-fuse.supply.token-fetcher.ts
Remove market from the label because it is already given enough context by the section in the UI.
=> fix(rari-fuse): Remove market in label, add Aave V2 as a dependency

src/apps/bastion-protocol/aurora/bastion-protocol.swap.token-fetcher.ts, src/apps/bastion-protocol/bastion-protocol.module.ts, src/apps/curve/curve.module.ts, src/apps/curve/curve.types.ts, src/apps/curve/helpers/curve.pool.default.token-helper.ts, src/apps/curve/helpers/curve.pool.on-chain.coin-strategy.ts, src/apps/curve/helpers/curve.pool.on-chain.reserve-strategy.ts, src/apps/curve/helpers/curve.pool.registry.ts, src/apps/curve/helpers/curve.pool.token-helper.ts, src/apps/curve/index.ts, src/apps/kinesis-labs/evmos/kinesis-labs.pool.definitions.ts, src/apps/kinesis-labs/evmos/kinesis-labs.pool.token-fetcher.ts, src/apps/kinesis-labs/kinesis-labs.module.ts, src/apps/saddle/ethereum/saddle.pool.definitions.ts, src/apps/saddle/ethereum/saddle.pool.token-fetcher.ts, src/apps/saddle/evmos/saddle.pool.definitions.ts, src/apps/saddle/evmos/saddle.pool.token-fetcher.ts, src/apps/saddle/saddle.module.ts, src/apps/tempus/helpers/tempus.amm.token-helper.ts, src/apps/velodrome/optimism/velodrome.pool.token-fetcher.ts
Easier to resolve addresses from on-chain requests, and catch underlying call failures using Multicall to filter out non-token indices.
=> feat(curve): Resolve coin addresses from on-chain again

src/apps/gmx/avalanche/gmx.balance-fetcher.ts
- Avalanche Balance-fetcher was using abitrum's addresses
=> fix(gmx): balancer fetcher on avalanche was using wrong addresses

src/apps/balancer-v2/balancer-v2.module.ts, src/apps/beethoven-x/optimism/beethoven-x.balance-fetcher.ts, src/apps/beethoven-x/optimism/beethoven-x.pool.token-fetcher.ts, src/token/price-selector.service.ts
Memory leaks would randomly appear when querying large sets of prices using dataloader when relying on the file-cache
=> feat(prices-selector): File cache is too slow, use memory cache

src/app-toolkit/app-toolkit.interface.ts, src/app-toolkit/app-toolkit.service.ts, src/app-toolkit/helpers/merkle/merkle.cache.ts
Expire the keys after 30m so that old Merkle amounts expire. I'll manually expire the keys without a TTL currently.
=> feat(votium): Add TTL on Votium keys to allow prior claimable amounts to expire

src/apps/curve/helpers/curve.pool.token-helper.ts
Velodrome is missing multiple pools. Only ETH and OP pools are showing. We where missing lowercasing addresses in one of the curve helper. ETH and OP where the only one working because there was no alphabetical character in their address.
[http://localhost:5001/apps/velodrome/tokens?groupIds%5B%5D=pool&network=optimism](http://localhost:5001/apps/velodrome/tokens?groupIds%5B%5D=pool&network=optimism)
=> feat(velodrome): Fix missing pools

src/apps/stargate/arbitrum/stargate.balance-fetcher.ts, src/apps/stargate/avalanche/stargate.balance-fetcher.ts, src/apps/stargate/binance-smart-chain/stargate.balance-fetcher.ts, src/apps/stargate/ethereum/stargate.balance-fetcher.ts, src/apps/stargate/fantom/stargate.balance-fetcher.ts, src/apps/stargate/optimism/stargate.balance-fetcher.ts, src/apps/stargate/polygon/stargate.balance-fetcher.ts
Stargate balance fetching is currently failing on Optimism. This due to a Multicall failure when trying to call `pendingStargate` on the [LP staking contract](https://optimistic.etherscan.io/address/0x4a364f8c717caad9a442737eb7b8a55cc6cf18d8#readContract).There is `SafeMath: division by zero` error returned by the contract. I found out that the call is throwing that because the reward period is over on that MasterChef contract and there is a [piece of code](https://optimistic.etherscan.deth.net/address/0x4a364f8c717caad9a442737eb7b8a55cc6cf18d8#readContract#123) attempting to divide by the `totalAllocPoint` which is equal to 0.
In this fix, I am catching the exception and falling back to 0.
=> fix(stargate): Fix balance fetcher when farm reward period is over

.github/workflows/release-please.yml
Leverages github event dispatch to trigger an action on the API instead of open the PR from here.
=> fix(ci): Dispatch action to zapper-api to trigger studio bump

src/apps/bastion-protocol/contracts/abis/bastion-protocol-comptroller.json, src/apps/bastion-protocol/contracts/abis/bastion-protocol-ctoken.json, src/apps/bastion-protocol/contracts/ethers/BastionProtocolComptroller.ts, src/apps/bastion-protocol/contracts/ethers/BastionProtocolCtoken.ts, src/apps/bastion-protocol/contracts/ethers/factories/BastionProtocolComptroller__factory.ts, src/apps/bastion-protocol/contracts/ethers/factories/BastionProtocolCtoken__factory.ts
Change the ABI to call the `borrowBalanceCurrent` method statically.
=> feat(bastion-protocol): Fix borrow balance

src/apps/b-protocol/adapters/liquity.b-protocol-adapter.ts, src/apps/liquity/ethereum/liquity.balance-fetcher.ts, src/apps/liquity/ethereum/liquity.staking.contract-position-fetcher.ts, src/apps/liquity/liquity.definition.ts, src/apps/liquity/liquity.module.ts
- Renamed liquidity farms group to `staking`
- Added new BAMM pool to b-protocol (liquity adapter)
https://github.com/Zapper-fi/studio/issues/1015
=> fix(b-protocol): fix b-protocol (liquity adapter)

src/apps/spool/ethereum/spool.vault.contract-position-fetcher.ts
Spool app: fix vault APY percentage display - multiply by 100 to show full percentage instead of 0.xx.
=> fix(spool): Transform percentage values when displaying APY (X*100)

src/apps/synthetix/optimism/synthetix.synth.token-fetcher.ts
- Enabled SNX to be exchangeable on Optimism
=> fix(synthetix): enable SNX to be exchangeable on optimism

src/apps/yearn/ethereum/yearn.v1-vault.token-fetcher.ts, src/apps/yearn/ethereum/yearn.yield.token-fetcher.ts, src/position/template/app-token.template.position-fetcher.ts
V1 vaults and yield tokens were using the app token decimals rather than 18. Fix it. Also, use the ERC20 contract in the app token template since some contracts return `decimals` as a BigNumber rather than a number.
=> fix(yearn): Fix Yearn token prices

src/apps/spool/ethereum/spool.vault.contract-position-fetcher.ts
Locally calculated base APY (used as a fallback) normalised to [0, 1.0].
=> fix(spool): vault locally calculated base APY to [0, 1.0]

src/app-toolkit/helpers/balance/token-balance.helper.ts, src/position/position-balance.interface.ts, src/position/position-fetcher.template-registry.ts, src/position/template/app-token.template.position-fetcher.ts, src/position/template/contract-position.template.position-fetcher.ts
Provides a way to fetch the app token and contract position balances without returning the entire asset so that the drilling/presentation can happen at a different time than the web3 calls.
=> feat(positions): Separate balance fetching from hydration in position fetchers

src/apps/kwenta/optimism/kwenta.perp.contract-position-fetcher.ts
Do not add enriched display if there is no open position (only margin deposited)
Test address: 
Position open, enriched display:
0xcd1d321485f74d740988f691276971f01073103b
No position open, no enriched display: 
0x324Fbd9536bf3d77d36137310fd4abe5130DfEA9
=> fix(kwenta): display when no position open

src/apps/dhedge-v2/polygon/dhedge-v2.pool.token-fetcher.ts
Graph query gives underlying assets with following format:
{vaultAddress}-{underlyingAssetAdress}
Only second part must be kept.
address holding USDt bear tokens
0xc6a21511ebd02525cf94bd1dd379fde007550dea
=> fix(dhedge-v2): polygon vaults underlying tokens

src/apps/synthetix/helpers/synthetix.loan.contract-position-helper.ts, src/apps/synthetix/helpers/synthetix.mintr.contract-position-helper.ts
use new synths logo in loan and mintr groups
address with staked SNX and loans on OP:
0x99d9cc5240b11c986037f5d010a405ac65e140c9
=> fix(synthetix): use new synths logos

src/apps/synthetix/helpers/synthetix.synth.token-helper.ts
Current code assume 1 sUSD = $1
We need to multiply synthRates by sUSD market price to take synth price premium (or discount) into account
This address holds sUSD on OP: 0x324Fbd9536bf3d77d36137310fd4abe5130DfEA9
=> fix(synthetix): synths price

src/apps/mean-finance/optimism/mean-finance.balance-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.balance-fetcher.ts
Fixes mean finance yield integration to search for appTokens first and then base tokens so yield bearing tokens are displayed correctly
http://localhost:5001/apps/mean-finance/balances?addresses[]=0xf488aaf75D987cC30a84A2c3b6dA72bd17A0a555&network=polygon
=> fix(mean-finance): find apptokens first and then basetokens

src/apps/aave-amm/helpers/aave-amm.lending.template.token-fetcher.ts, src/apps/aave-v2/helpers/aave-v2.lending.template.token-fetcher.ts, src/position/template/app-token.template.position-fetcher.ts
The only way apps can define an AppToken as a debt right now is to re-define the entire `getBalance` method on the AppTokenTemplatePositionFetcher to pass `{ isDebt: true }` to the `drill` call.
This PR adds an `isDebt` flag on the base AppTokenTemplatePositionFetcher that is default to false. This allows us to remove the `getBalance` overrides that we have in place and only have the app token templates define `isDebt = true` (https://github.com/Zapper-fi/studio/blob/main/src/apps/aave-v2/ethereum/aave-v2.stable-debt.token-fetcher.ts#L16).
=> feat(debt): Add ability to define debt for app token positions

src/position/template/contract-position.template.position-fetcher.ts
Follow up to https://github.com/Zapper-fi/studio/pull/1515, it seems like the contract position template already supported debt, but i forgot to add the `isDebt` flag in the drillBalance call of the new `drillRawBalance` method. This has for effect of having position balanceUSD values when a token has a `borrowed` meta type.
=> feat(debt): Add support for debt in drillRawBalance

src/apps/uniswap-v2/common/uniswap-v2.pool.subgraph.template.token-fetcher.ts
Providing a subgraph Url from Fura would throw since it doens't have a _meta attribute. The Quickswap app integration needs this change because it's the only valid subgraph synced with all the pools (plus, it's the one their website uses)
=> fix(uniswap-v2): Providing a subgraph url from Fura would throw since it doesn't have the _meta attribute

src/apps/lyra-avalon/optimism/helpers/graph.ts
No longer using the hosted service, new API has been added
=> Replace deprecated subgraph URL

src/apps/balancer-v2/common/balancer-v2.pool.token-fetcher.ts, src/apps/beethoven-x/common/beethoven-x.pool.token-fetcher.ts, src/apps/pickle/common/pickle.jar-univ3.token-fetcher.ts, src/apps/pool-together-v3/common/pool-together-v3.sponsorship.token-fetcher.ts, src/apps/rubicon/common/rubicon.bath.token-fetcher.ts, src/position/template/app-token.template.position-fetcher.ts, src/position/template/app-token.template.types.ts
ERC-1155 needs better support for `definitions` since many tokens can exist on a single contract. Adjust the template to treat definitions list as the source of truth for enumerating tokens (i.e.: 1 definition per token, rather than 1 address per token).
=> feat(templates): Adjust app token template for flexibility with ERC1155

src/scheduler/scheduler.decorator.ts, src/scheduler/scheduler.service.ts
This is to make sure the APIs on both api & studio are fully aligned.
=> fix(schedule): Use only 1 metadata attribute for @Schedule

src/apps/balancer-v2/common/balancer-v2.claimable.contract-position-fetcher.ts, src/apps/bend-dao/ethereum/bend-dao.variable-debt.token-fetcher.ts, src/apps/chicken-bond/ethereum/chicken-bond.bond.contract-position-fetcher.ts, src/apps/concave/ethereum/concave.liquid-staking.contract-position-fetcher.ts, src/apps/euler/common/euler.d-token.token-fetcher.ts, src/apps/euler/common/euler.e-token.token-fetcher.ts, src/apps/good-ghosting/common/good-ghosting.game.contract-position-fetcher.ts, src/apps/homora-v2/common/homora-v2.farm.contract-position-fetcher.ts, src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-fetcher.ts, src/apps/kyberswap-elastic/common/kyberswap-elastic.liquidity.contract-position-fetcher.ts, src/apps/maker/ethereum/maker.vault.contract-position-fetcher.ts, src/apps/meshswap/polygon/meshswap.supply.token-fetcher.ts, src/apps/polygon-staking/ethereum/polygon-staking.deposit.contract-position-fetcher.ts, src/apps/qi-dao/common/qi-dao.vault.contract-position-fetcher.ts, src/apps/rari-fuse/common/rari-fuse.borrow.contract-position-fetcher.ts, src/apps/rari-fuse/common/rari-fuse.supply.token-fetcher.ts, src/apps/ren/ethereum/ren.darknode.contract-position-fetcher.ts, src/apps/rhino-fi/ethereum/rhino-fi.deposit.contract-position-fetcher.ts, src/apps/sablier/ethereum/sablier.stream-legacy.contract-position-fetcher.ts, src/apps/sablier/ethereum/sablier.stream.contract-position-fetcher.ts, src/apps/uniswap-v3/common/uniswap-v3.liquidity.contract-position-fetcher.ts, src/apps/wolf-game/ethereum/wolf-game.wool-pouch.contract-position-fetcher.ts, src/apps/yield-protocol/common/yield-protocol.borrow.contract-position-fetcher.ts, src/position/position-fetcher.template-registry.ts, src/position/template/custom-contract-position.template.position-fetcher.ts
This PR introduces a new template called `CustomPositionTemplatePositionFetcher`. This template forces the implementer to write the `getBalances` method that directly returns the `ContractPositionBalance` instead of using the `getBalanceRaw` and `drillBalanceRaw` methods from the base template.
The goal is to be able to identify Apps with custom needs that don't fit in our model and treat them as such.
=> feat(contract-positions): Custom contract positions

src/position/template/contract-position.template.position-fetcher.ts
In the `getBalances` method, we default the raw balance to `0` if the array returned by `getTokenBalancesPerPosition` returns less balances than the amount of tokens in the contract position.
We added a `throw` statement in the getRawBalances because we thought this was an invalid scenario, but it looks like we should just return 0 in this case.
=> fix(template): Fix balance mistmatch for contract position template

src/apps/convex/common/convex.deposit-sidechain.token-fetcher.ts
Convex on sidechains/L2 works differently. It is tokenized, so include them in the TVL since they're not double-counted in the farms.
=> feat(convex): Show deposits in explore and TVL

src/apps/synthetix/common/synthetix.synth.token-fetcher.ts
- Use synth asset logo instead underlying
=> fix(synthetix): Use synth asset's logo instead of underlying

src/position/template/contract-position.template.position-fetcher.ts
Underlying app tokens are double counted since they use the same underlying key. E.g.
before:
```json
{
"groupId": "farm-pls-dpx-v2",
"balances": [
{
"key": "0x75c143460f6e3e22f439dff947e25c9ccb72d2e8:arbitrum:plutus:0xf236ea74b515ef96a9898f5a4ed4aa591f253ce1:arbitrum:supplied,0x51318b7d00db7acc4026c88c3952b66278b6a67f:arbitrum:claimable,0xf236ea74b515ef96a9898f5a4ed4aa591f253ce1:arbitrum:claimable,0xe7f6c3c1f0018e4c08acc52965e5cbff99e34a44:arbitrum:claimable,0x6c2c06790b3e3e3c38e12ee22f8183b37a13ee55:arbitrum:claimable:",
"tokens": [
{
"key": "plutus:0xf236ea74b515ef96a9898f5a4ed4aa591f253ce1:arbitrum:supplied:",
"balance": "501739962884776094812"
},
{
"key": "0x51318b7d00db7acc4026c88c3952b66278b6a67f:arbitrum:claimable",
"balance": "3369229421569993636398"
},
{
// THE FOLLOWING LINE IS …
```
=> fix(balances): Fix double counting for underlying app-tokens

src/apps/compound/helper/compound.borrow.balance-helper.ts
The metaType is missing for the borrowed token and is defaulting in some cases to a supplied token.
=> fix(compound): Add missing borrowed metaType

src/apps/geist/fantom/geist.platform-fees.contract-position-fetcher.ts
The address is actually lowercased and wasn't matching, so the claimable token ended up being duplicated.
=> fix(geist): Fix lowercased token address

src/apps/mycelium/helpers/mycelium.lev-trades.contract-position-helper.ts
IndexToken in mycelium is not really a supplied token, but a token to inform what the position is shorting/longing. Instead we can keep it only in the dataProps since it's used to calculate the balance of the supplied token.
=> fix(mycelium): Remove indexToken from list of underlying tokens

src/apps/spool/ethereum/spool.balance-fetcher.ts, src/apps/spool/ethereum/spool.staking.contract-position-fetcher.ts
Since the key generation of the different positions rely on the ordering of the tokens, we need to make sure the order of the tokens is the same in both the balance fetcher & contract-position fetcher.
=> fix(spool): Make list of underlying tokens order the same as balances

src/apps/convex/common/convex.farm.contract-position-fetcher.ts
If the bonus rewards include CVX, combine this with the minted CVX amount. Prevents confusion on the FE and better supported by balance snapshots since they keys are identical currently for the nested CVX rewards.
=> fix(convex): Combine minted and bonus claimable CVX

src/position/template/app-token.template.position-fetcher.ts
Time to start pulling more Uniswap V2 pools! Split the `getPositions` method so that we can batch in Zapper API by calling the batch method with a subset of the definitions.
=> feat(positions): Split getPositions to enable batching

src/balance/balance-presentation.service.ts
Since we are presenter the balances by using the groups, we may end up with an empty set of balances. For now let's ignore the fact that we may have empty balances.
Ideally, we should group the balances by groupId, then map the groupId => label, then regroup by label. This way we would never end up with an empty set of balances.
=> fix(presenter): ignore empty balance set

src/position/template/app-token.template.position-fetcher.ts, src/position/template/contract-position.template.position-fetcher.ts
This should have quite a significant improvement for apps that have a lot of positions since it would avoid doing O(N^2) lookups.
=> feat(balances): Improve performance by doing O(1) lookups

src/apps/aura/ethereum/aura.aura-bal-staking.contract-position-fetcher.ts, src/apps/aura/ethereum/aura.deposit.token-fetcher.ts, src/apps/aura/ethereum/aura.lp-farm.contract-position-fetcher.ts
Aura has just started an [LP migration](https://twitter.com/AuraFinance/status/1601065333925650432) for all users to opt in to. 
This PR makes several changes to support this migration, by showing the balances of the new pools, and showing a 'Needs migration' label for pools that will not be receiving further rewards.
The subgraph endpoint has also changed: 
```typescript
export class AuraSubgraphHelper {
static V1 = 'https://graph.aura.finance/subgraphs/name/aura/aura-mainnet-v1';
static V2 = 'https://graph.aura.finance/subgraphs/name/aura/aura-mainnet-v2';
```
The schema is the same; v1 contains the deprecated pools/accounts, and v2 contains the current pools/accounts, and also the locker.
You can test with `0x51D63958A63A31eB4028917F049Ce477c8DD07Bb` and optionally compare this with …
=> feat(aura): Aura pools upgrade

src/position/template/app-token.template.position-fetcher.ts
Support token ID as a string because Shell V2 has very large numeric token IDs.
=> feat(app-token): Support string token ID

src/apps/jpegd/ethereum/jpegd.bond.contract-position-fetcher.ts, src/apps/klima/polygon/klima.bond.contract-position-fetcher.ts, src/apps/olympus/common/olympus.bond.contract-position-fetcher.ts, src/apps/olympus/ethereum/olympus.bond.contract-position-fetcher.ts
A few integrations require this in Zapper API.
=> feat(olympus): Update bond template to support async definitions and custom data props

src/apps/euler/common/euler.token-definition-resolver.ts
- Filtered out RAD market because the supply on the contract is way higher than it should be which is causing liquidity to skyrocket
=> fix(euler): Remove RAD market

src/apps/pendle-v2/ethereum/pendle-v2.pool.token-fetcher.ts, src/apps/pendle-v2/ethereum/pendle-v2.principal.token-fetcher.ts, src/apps/pendle-v2/ethereum/pendle-v2.standardized-yield.token-fetcher.ts, src/apps/pendle-v2/ethereum/pendle-v2.yield.token-fetcher.ts, src/apps/pendle-v2/index.ts, src/apps/pendle-v2/pendle-v2.module.ts
Prevent circular dependency between pool group and SY/Y/P token groups.
=> feat(pendle-v2): Use API response to populate all token groups

src/apps/mux/helpers/mux.lev-trades.contract-position-helper.ts
After mux balanceFetcher went live, we found some user experience problems and decided to update it
1. edit/create `.env` adding `ENABLED_APPS=mux`
2. run `pnpm dev` to spin up nest server
3. visit dev endpoints below to see result to integrate mux
* http://localhost:5001/apps/mux/positions?groupIds[]=lev-trades&network=arbitrum
* http://localhost:5001/apps/mux/positions?groupIds[]=lev-trades&network=avalanche
* http://localhost:5001/apps/mux/positions?groupIds[]=lev-trades&network=binance-smart-chain
* http://localhost:5001/apps/mux/positions?groupIds[]=lev-trades&network=fantom
=> chore(mux): Update lev-trades ContractPositionFetcher

src/apps/mean-finance/ethereum/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/mean-finance.definition.ts, src/apps/mean-finance/mean-finance.module.ts
Adds Ethereum Mainnet integration for Mean Finance
http://localhost:5001/apps/mean-finance/balances?addresses[]=0x2421134c8e8278ad199f6886ae70c5c373da3b48&network=ethereum
=> feat(mean-finance): add Ethereum Mainnet for Mean Finance integration

src/app-toolkit/decorators/index.ts, src/apps/aave-v2/common/aave-v2.position-presenter.ts, src/apps/bastion-protocol/aurora/bastion-protocol.position-presenter.ts, src/apps/compound/common/compound.position-presenter.ts, src/apps/morpho/ethereum/morpho.position-presenter.ts, src/apps/rari-fuse/common/rari-fuse.position-presenter.ts, src/apps/synthetix/common/synthetix.position-presenter.ts, src/balance/balance-presentation.service.ts, src/balance/balance.service.ts, src/position/position-presenter.registry.ts, src/position/template/position-presenter.template.ts
I'm adding 2 new methods on presenters:
```
dataProps(address: string): Promise<T | undefined>
metadataItemsForBalanceGroup(groupLabel: string, balances: ReadonlyBalances, dataProps?: T): MetadataItemWithLabel[]
```
This will allow us to calculate the dataProps along with the balances, and massage the data after the fact. This will remove the remaining RPC calls that were being made when loading the balances for a given address.
=> feat(presenter): Add presenter dataProps

src/apps/keeper/common/keeper.job.queries.ts
Just changes the keep3r subgraph url to the official one
http://localhost:5001/apps/keeper/positions?groupIds[]=job&network=ethereum
=> feat(keeper): use official keep3r graph

src/apps/gmx/common/gmx.perp.contract-position-fetcher.ts
Fix missing balances on GMX
**Why?**
`if (v === t) return null;`
On Gmx, you can long ETH and use ETH as collateral
Refactor definitions removing positions that doesnt' exist (e.g collateral: ETH, long: USDT)
Arbitrum went from 144 => 72 (9 tokens can be used as collateral * 4 tokens you can long/short * 2 available position (short + long) 
Same applies for Avalanche, 84 => 56
=> fix(gmx): Refactor perpetuals definitions reflecting available position

src/apps/llama-airforce/ethereum/llama-airforce.vault.token-fetcher.ts
1. Adds a new uCRV pounder. People are advised to migrate from the old one to the new one.
I've build the app, went to http://localhost:5001/apps/llama-airforce/balances?addresses[]=0x71df067D1d2dF5291278b7C660Fd37d9b6272b4C&network=ethereum and saw that the JSON contained the correct balance for the new uCRV pounder: 9.896040787579413.
=> fix(llama-airforce): Add new uCRV pounder

src/apps/uniswap-v2/common/uniswap-v2.pool.subgraph.template.token-fetcher.ts
- Fix pool subgraph strategy APY (Uniswap-v2, sushiswap, etc APYs are off by 100)
=> fix(uniswap-v2): Fix pool subgraph strategy APY

src/apps/beefy/common/beefy.vault.token-fetcher.ts
Beefy was not working for vaulted token with less than 18 decimals. Adjust the logic since `balanceOf` and `supply` are always rendered in the precision of the underlying token, and `getPricePerFullShare` is always rendered in 18 decimals.
=> feat(beefy): Fix price per share and decimals

src/apps/llama-airforce/ethereum/llama-airforce.airdrop.contract-position-fetcher.ts, src/apps/llama-airforce/ethereum/llama-airforce.merkle-cache.ts
1. Changes the reward token of the uCRV Union airdrop contract so that it points to the new token inside the merkle distributor (since last tuesday).
I've build the app, went to http://localhost:5001/apps/llama-airforce/balances?addresses[]=[redacted]&network=ethereum and saw that the JSON contained my personal airdrop with the current new underlying vault share token: ucvxCRV
=> fix(llama-airforce): Fix uCRV distributor looking at the old vault address

src/apps/velodrome/common/velodrome.definitions-resolver.ts, src/apps/velodrome/optimism/velodrome.bribe.contract-position-fetcher.ts, src/apps/velodrome/optimism/velodrome.farm.contract-position-fetcher.ts, src/apps/velodrome/optimism/velodrome.pool.token-fetcher.ts, src/apps/velodrome/velodrome.module.ts
- Fix bribe positions/balances
- Extract external API calls into resolver
- Added APY to pool
=> fix(velodrome): Fix claimables and extract external api calls into a resolver

src/apps/amp/ethereum/amp.farm.contract-position-fetcher.ts
We updated the contract-position-fetcher from single-staking.template.contract-position-fetcher to contract-position.template.position-fetcher, which enables us to use getTokenBalancesPerPosition. This change allows for multiple positions to be represented as rows on the front end. The previous implementation had a misleading "claimable" green tag on the front end, as rewards are auto-compounding, not claimable. With getTokenBalancesPerPosition, we now return both the supplied total and reward total with metaType supplied. Additionally, we updated the label to display the range of pool APYs and the group label.
/apps/amp/balances?addresses[]=0x376F49Cf37632913E0F09f51D16bBcAc0f12263C&network=ethereum
=> feat(amp): Add getTokenBalancesPerPosition, update label & update group label.

src/apps/gearbox/ethereum/gearbox.phantom.token-fetcher.ts
- Exclude phantom tokens from balances
Phantom tokens are a wrapper on top of a mint token you get back when you stake into convex
=> fix(gearbox): Exclude phantom app tokens from balances

src/apps/velodrome/common/velodrome.voting-rewards.contract-position-fetcher.ts, src/apps/velodrome/optimism/velodrome.bribe.contract-position-fetcher.ts, src/apps/velodrome/optimism/velodrome.fees.contract-position-fetcher.ts
Since `getTokenBalancesPerPosition` is overridden to throw, we need to implement _both_ `getBalances` and `getRawBalances`. Our goal is to eventually remove `getBalances` entirely in favour of `getRawBalances`, but for now, both functions need to be present in our integrations (and usually, the default implementations in the template are good enough).
=> feat(velodrome): Fix raw balances

src/apps/beanstalk/beanstalk.module.ts, src/apps/beanstalk/ethereum/beanstalk.unripe-assets.token-fetcher.ts
- Rename silo deposit token to unripe assets
=> fix(beanstalk): Rename deposit token to unripe assets

src/apps/concentrator/ethereum/concentrator.vesting.contract-position-fetcher.ts
The purpose of this PR is to calculate the claimable from vesting from Concentrator correctly. As mentioned in #2285
The address 0xcfb3b99e0a7ad8008a5bd5d3255e338f493f8c15 has no vesting claimable anymore. Before this PR Zapper says that there stil is, after this PR not.
=> fix(concentrator): Calculate claimable using vesting state

src/apps/kwenta/common/kwenta.perp.contract-position-fetcher.ts, src/apps/synthetix/optimism/synthetix.perp-v2.contract-position-fetcher.ts
Synthetix/Kwenta perp fixes:
- Use ProxyPerpsV2 addresses instead of PerpV2MarketViews
- Filter Kwenta gql request as it returns a mix of v1 and v2 markets, keep only v1 to avoid duplicates
This address as a BNB-PERP position currently displayed twice (once in Kwenta and once in Synthetix):
0xd120cf3e0408dd794f856e8ca2a23e3396a9b687
It only shows up in Synthetix after fix as it is a v2 position
=> fix(kwenta): Perp markets duplicate

src/apps/gains-network/arbitrum/gains-network.g-token.token-fetcher.ts, src/apps/gains-network/arbitrum/gains-network.staking.contract-position-fetcher.ts, src/apps/gains-network/gains-network.module.ts
Adds Arbitrum support for Gains Network staking and gDAI vault.
Implementation matches 1:1 with the Polygon one
AppId `gains-network`
GNS staking : http://localhost:5001/apps/gains-network/balances?addresses[]=0xadae0cdb5b7fdbcdb6094b80af96869abf8ad394&network=arbitrum
gDAI vault : http://localhost:5001/apps/gains-network/balances?addresses[]=0xddd0898ccb492e78c714ea1baeb593100746510e&network=arbitrum
=> feat(gains-network): add arbitrum support

src/apps/abracadabra/common/abracadabra.cauldron.contract-position-fetcher.ts
Was getting reverts on my local setup, and found that the bentobox call wasn't wrapped in a multicall. Doing that seems to have helped.
http://localhost:5001/apps/abracadabra/balances?network=ethereum&addresses%5B%5D=0xDF2C270f610Dc35d8fFDA5B453E74db5471E126B
Prior to the changes I get:
```json
{
"statusCode": 500,
"message": "Internal server error"
}
```
After:
```json
{
"0xdf2c270f610dc35d8ffda5b453e74db5471e126b": {
"products": [],
"meta": [
{
"label": "Total",
"value": 0,
"type": "dollar"
},
{
"label": "Assets",
"value": 0,
"type": "dollar"
},
{
"label": "Debt",
"value": 0,
"type": "dollar"
}
]
}
}
```
=> fix(abracadabra): Wrap bentobox calls in multicall to mitigate reverts

src/apps/gains-network/arbitrum/gains-network.g-token.token-fetcher.ts, src/apps/gains-network/polygon/gains-network.g-token.token-fetcher.ts
The pricePerShare was wrongly reported for Gains Vaults ( gDAI ).
Fixed for Arbitrum and Polygon using the `shareToAssetsPrice` function.
AppId `gains-network`
Arbitrum : http://localhost:5001/apps/gains-network/balances?addresses%5B%5D=0xddd0898ccb492e78c714ea1baeb593100746510e&network=arbitrum
Polygon : http://localhost:5001/apps/gains-network/balances?addresses%5B%5D=0xdec01942f6c39554ebd652b15fe6c5a08551105a&network=polygon
=> fix(gains-network): fix pricePerShare call

src/apps/gmx/common/gmx.perp.contract-position-fetcher.ts
- Add leverage and size to GMX Perps's dataProps
Haven't added liquidation prices yet because it's way more tricky. The borrow fee % varies based on the amount of liquidity available in the pool
=> fix(gmx): Add size and leverage to perp's dataProps

src/apps/gmx/common/gmx.perp.contract-position-fetcher.ts
Overriding getBalances requires a CustomContractPositionTemplatePositionFetcher
=> fix(gmx): Overriding getBalances requires a CustomContractPositionTemplatePositionFetcher

src/apps/llama-airforce/ethereum/llama-airforce.airdrop.contract-position-fetcher.ts, src/apps/llama-airforce/ethereum/llama-airforce.merkle-cache.ts, src/apps/llama-airforce/ethereum/llama-airforce.vault.token-fetcher.ts
1. Adds a new uFXS pounder and distributor. People are advised to migrate from the old one to the new one.
I've built the app, went to [http://localhost:5001/apps/llama-airforce/balances?addresses[]=[redacted]&network=ethereum](http://localhost:5001/apps/llama-airforce/balances?addresses%5B%5D=[redacted]&network=ethereum) and saw that the JSON contained the correct balance and underlying cvxFXS balance for the new uFXS pounder and merkle airdrop for my personal account.
=> fix(llama-airforce): Add new uFXS pounder and distributor

src/apps/vela/common/vela.vlp.token-fetcher.ts
Updated the VLP APY endpoint. Also added a try catch s.t. it does not break the token fetcher if the APR endpoint is unavailable.
Address with a non-zero amount of VLP staked:
http://localhost:5001/apps/vela/balances?network=arbitrum&addresses%5B%5D=0x33774483bd9e61a5568a22fa90d32195e5ae0824
=> fix(vela): Update VLP APY endpoint

src/apps/llama-airforce/ethereum/llama-airforce.airdrop.contract-position-fetcher.ts, src/apps/llama-airforce/ethereum/llama-airforce.merkle-cache.ts, src/apps/llama-airforce/ethereum/llama-airforce.vault.token-fetcher.ts
1. Adds a new uCRV pounder and distributor. People are advised to migrate from the old one to the new one.
I've built the app, went to [http://localhost:5001/apps/llama-airforce/balances?addresses[]=[redacted]&network=ethereum](http://localhost:5001/apps/llama-airforce/balances?addresses%5B%5D=[redacted]&network=ethereum) and saw that the JSON contained the correct balance and underlying cvxCRV balance for the new uCRV pounder and merkle airdrop for my personal account.
=> fix(llama-airforce): Add new uCRV pounder and distributor

src/apps/lyra-avalon/arbitrum/lyra-avalon.options.contract-position-fetcher.ts
- Fix decimals for options on Arbitrum
`0xed5f239fc64c084afdd3fa2000e6e577638f4bd0`
=> fix(lyra-avalon): Fix option decimals on Arbitrum

src/apps/kyberswap-classic/kyberswap-classic.module.ts, src/apps/kyberswap-classic/polygon/kyberswap-classic.dmm-pool.token-fetcher.ts, src/apps/kyberswap-classic/polygon/kyberswap-classic.ks-pool.token-fetcher.ts
KyberSwap classic is only listing pools with dynamic fees (DMM) and farms that have launched for the first 2 FairLaunch. This PR is adding KS static fee pools (KS) as well as a way to fetch all farms for all fairlaunches dynamically.
=> fix(studio): Revamping KyberSwap classic pools+farms

src/apps/vela/arbitrum/vela.beta-vlp.token-fetcher.ts, src/apps/vela/vela.module.ts
Make PPS and APY zero for the beta VLP to avoid displaying a wrong amount of USDC. It was considered to remove the beta VLP completely, however, then unclaimed esVELA in the VLP would not be displayed. So a compromise was to just make it's PPS and APY zero.
Address with VLP staked:
http://localhost:5001/apps/vela/balances?network=arbitrum&addresses[]=0x128e50f8a4f1d9a53a7a0201243fcb72e6161bce
=> fix(vela): Make PPS and APY zero for beta VLP

src/apps/kwenta/optimism/kwenta.perp-v1-cross-margin.contract-position-fetcher.ts, src/apps/kwenta/optimism/kwenta.perp-v2-smart-margin.contract-position-fetcher.ts, src/apps/synthetix/optimism/synthetix.perp-v1.contract-position-fetcher.ts, src/apps/synthetix/optimism/synthetix.perp.contract-position-fetcher.ts
Create 3 contract position per market in order to show perp position side: long, short or neutral (no position open, only margin deposited).
This applies to synthetix perp v1 (including Kwenta cross margin implementation) and v2 (including Polynomial Perp and Kwenta Smart Margin).
BTC long: 0x1960feccc7f649d66457f81c270540a3b1785872
BTC/ETH/SOL shorts: 0x1960feccc7f649d66457f81c270540a3b1785872
ETH neutral: 0x15217ccc4d81d9ab3254ebb4414b30d24f08c71f (or 0xacbe85b298d2c1b791ece44ec2c17021b011db03 through polynomial app)
Can use https://watcher.synthetix.io/ to find other wallets
=> feat(synthetix): display perp position side

src/apps/abracadabra/ethereum/abracadabra.cauldron.contract-position-fetcher.ts
Add support for the CRV V2 cauldron.
Unfortunately it is not possible to really test yet as there not positions yet. However, the change is fairly trivial, so should work :eyes: :eyes: .
It is possible to verify that it is a cauldron and that it was deployed by Abracadabra on Etherscan: https://etherscan.io/address/0x7d8dF3E4D06B0e19960c19Ee673c0823BEB90815.
=> feat(abracadabra): Add support for the CRV V2 cauldron

src/apps/kyberswap-elastic/common/kyberswap-elastic.farm.contract-position-fetcher.ts
A single pool is mis-configured on Polygon and causes a lot of errors on production. This PR is filtering out the pool and keeps the other operating as normal, and should thus kill the errors.
- set the `kyberswap-elastic` for `ENABLED_APPS` in your `.env` and `pnpm dev`
- there shouldn't be any error thrown anymore
Previous error:
```
ERROR [CacheOnIntervalService] @CacheOnInterval error init for PolygonKyberswapElasticFarmContractPositionFetcher#getPositions: Multicall call failed for 0xF2057f0231bedCEcf32436E3cD6b0b93C6675E0a:token0(): call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="token0()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0) (decode)
```
=> fix(studio): KyberSwap elastic failing on Polygon

src/apps/synthetix/optimism/synthetix.perp.contract-position-fetcher.ts
Let perps built on top of synthetix use different market logos (currently kwenta)
0xd8e80c06f9f3a41c85cad28117e01ebd50fd535e currently has kwenta perp position opened
=> fix(synthetix): custom perp market logos

src/apps/lido/ethereum/lido.wsteth.token-fetcher.ts
Wrapped staked ETH shouldn't count towards TIV because it's double counting
=> fix(lido): Wrapped staked ETH should not count towards TIV

src/apps/arrakis/common/arrakis.pool-definition-resolver.ts, src/apps/aura/common/aura.balancer-pool.resolver.ts, src/apps/ren/common/ren.api.client.ts, src/apps/rubicon/common/rubicon.bath.token-definition-resolver.ts, src/apps/sentiment/common/sentiment.accounts-resolver.ts, src/apps/silo-finance/common/silo-finance.definition-resolver.ts, src/apps/solid-lizard/common/solid-lizard.definitions-resolver.ts, src/apps/sushiswap-bentobox/common/sushiswap-bentobox.vault-tokens-resolver.ts, src/apps/synthetix/common/synthetix.mintr.snx-holders.cache.ts, src/apps/tenderize/common/tenderize.token-definition-resolver.ts
- Bumped cached data TTL to an hour. This is temporary mesure preventing 'false' errors all over the place. This will be reverted as soon as maintenance is done
_theGraph hosted services subgraph will be under database maintenance on May 22, 2023 at 5am UTC_
=> fix(subgraph): Bump cached data ttl to an hour

.github/workflows/release-please.yml
Attempt to pin the version on release-please-action.
Seems like suddenly the release please action isn't running, and there has been a release in the last hour. Attempt to pin to the earlier version to see if an improvement is made.
=> feat(studio): Attempt to pin version on release-please-action

src/apps/raft/ethereum/raft.position-presenter.ts, src/apps/raft/raft.module.ts
see https://github.com/Zapper-fi/studio/pull/2728
solution for https://discord.com/channels/647279669388771329/964569348243075082/1116498228406394941. just not imported. still not testable. if this doesnt work I have an alternate approach, which is to override getBalances in the raft.position.contract-position-fetcher as follows
```
// Hack: should be position presenter
async getBalances(_address: string) {
const rawBalances = await super.getBalances(_address);
const balances = rawBalances.map(balance => {
const collateral = balance.tokens[0];
const collateralUSD = collateral?.balanceUSD ?? 0;
const debt = -(balance.tokens[1]?.balanceUSD ?? 0);
const cRatio = Math.abs(debt) > 0 ? Math.abs(collateralUSD / debt) : 0;
const liquidationPrice = (Number(balance.dataProps.minCRatio) * debt) / …
```
=> fix(raft): fix for position presenter

src/apps/raft/ethereum/raft.position-presenter.ts
sorry about pr spam for this app
Vukašin | Raft — Today at 5:40 PM
One small issue regarding C-ratio formatting. It should be 153.9%, not 1.539% Image
https://zapper.xyz/account/0x6bddefb9f04b01c326b43b218059ee6938ea1ca8/protocols/ethereum/raft
=> fix(raft): fix cratio percentage

src/apps/mean-finance/binance-smart-chain/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/ethereum/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/mean-finance.module.ts, src/apps/mean-finance/optimism/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/mean-finance/polygon/mean-finance.dca-position.contract-position-fetcher.ts
…sses
Adds the Mean deployment of Binance Smart Chain and updates old yield v4 hub addresses
Address: 0x1cb6020db373a3e1cfcda9489570933fd0f79d0d for binance smart chain can retrieve balances
=> feat(mean-finance): add Mean Finance bnb deployment and fix hub addresses

src/apps/raft/ethereum/raft.position-presenter.ts
- Early return if there's no balance will prevent throwing on 
`const liquidationPrice = (minCRatio * debt) / collateral.balance;`
If there's no balances
**collateral is undefined**
=> fix(raft): Early return if there's no balances

src/apps/polynomial/optimism/polynomial.smart-wallet.contract-position-fetcher.ts
TVL fetched from API was applied for each token hence triple counting, to display accurate data we'll assume all tvl is sUSD.
USDC deposited is converted to sUSD to trade, OP amounts are low (trading rewards).
address with sUSD: 0x22EEb166310EE35695dD856dF8b4F7AE489df933
with OP: 0x79926C541D1f28f9a0ABc9C84592E31743Cd1997
=> fix(polynomial): fix triple count smart wallet tvl

src/multicall/multicall.contract.ts, src/multicall/multicall.ethers.ts, src/multicall/multicall.interface.ts
Add `load` to the Multicall wrapper interface.
=> feat(studio): Add load to Multicall wrapper interface

src/apps/gmx/common/gmx.perp.contract-position-fetcher.ts
- Add size and leverage to dsplay props
=> feat(gmx): Add size and leverage to perp display props

src/apps/aelin/optimism/aelin.farm.contract-position-fetcher.ts, src/apps/gains-network/common/gains-network.staking.contract-position-fetcher.ts, src/apps/helio/binance-smart-chain/helio.staking.contract-position-fetcher.ts, src/apps/jones-dao/arbitrum/jones-dao.farm.contract-position-fetcher.ts, src/apps/looks-rare/ethereum/looks-rare.farm.contract-position-fetcher.ts, src/apps/pie-dao/ethereum/pie-dao.farm-single-staking.contract-position-fetcher.ts, src/apps/tokemak/ethereum/tokemak.farm.contract-position-fetcher.ts, src/apps/wolf-game/ethereum/wolf-game.wool-pouch.contract-position-fetcher.ts
In Zapper API, we import the module from Studio which ends up pulling the `AppToolkit` service class, which has downstream dependencies to `file-system-cache`. Instead, resolve the `IAppToolkit` interface to avoid pulling in the dependencies in the import structure.
=> feat(studio): Use interface for app toolkit to avoid importing AppToolkit dependency tree

src/position/template/vesting-escrow.template-contract-position-fetcher.ts
- Fix underlying token order
edit:  Here's an example - ~51m CRV should show up as locked 
`0x7a16ff8270133f063aab6c9977183d9e72835428`
=> fix(curve): Fix vesting escrow underlying token order

src/apps/spool/ethereum/spool.vault.contract-position-fetcher.ts
Issue found when invoking `/apps/{appId}/balances`.
Subgraph query wasn't taking into account that strategies could be removed from the system and should be ignored. As a consequence, a contract call failed due to an invalid list of strategies.
=> fix(spool): ignore removed strategies

src/apps/curve/common/curve.pool-dynamic-v2.token-fetcher.ts, src/apps/curve/common/curve.pool-gauge-v6.contract-position-fetcher.ts
- some dynamic pools have fees
- some gauge v6 position aren't fully implemented yet and return the ZERO_ADDRESS instead of the 'real' gauge address
=> fix(curve): Fix gauge v6 and dynamic pools without fee

src/apps/yearn/common/yearn.vault.token-definitions-resolver.ts
Revert temporary yDeamon url update
=> fix(yearn): Revert pointing to ydeamon stating environment

src/apps/reserve-protocol/ethereum/reserve-protocol.cooldown.contract-position-fetcher.ts
Filtering out contract address until `main.pausedOrFrozen();` is supported
=> fix(reserve-protocol): Filter out address which isnt fully supported yet

src/apps/balancer-v2/base/balancer-v2.farm.contract-position-fetcher.ts, src/apps/balancer-v2/common/balancer-v2.farm.contract-position-fetcher.ts
One of the Balancer-v2 Gauge has a wrong setup and one of the reward token address is a gnosis safe. Will be filtering this address out from reward token addresses
=> fix(balancer-v2): Filter out faulty reawrd address from Balancer-v2 farm position

src/apps/meta-street/ethereum/meta-street.lending-v2-legacy.contract-position-fetcher.ts, src/apps/meta-street/ethereum/meta-street.lending-v2.contract-position-fetcher.ts
Fix computation of supplied and claimable balances to avoid negative balances.
The negative balance on Zapper causing the frontend bug is removed as observed in a local test.
**Bug on Zapper:**
[https://zapper.xyz/account/0x66ceac5ee8f093059c4bc9628c06e63076505b15?tab=apps](https://zapper.xyz/account/0x66ceac5ee8f093059c4bc9628c06e63076505b15?tab=apps)
**Tested locally:**
http://localhost:5001/apps/meta-street/balances?addresses[]=0x66ceac5ee8f093059c4bc9628c06e63076505b15&network=ethereum
=> feat(metastreet): Fix MetaStreet app

src/apps/stargate/arbitrum/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/avalanche/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/base/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/binance-smart-chain/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/common/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/ethereum/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/fantom/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/optimism/stargate.farm.contract-position-fetcher.ts, src/apps/stargate/polygon/stargate.farm.contract-position-fetcher.ts
`stargatePerBlock` method doesn't exist on the contracts on Base
=> fix(stargate): Fix farms on Base

src/apps/exactly/common/exactly.borrow.token-fetcher.ts, src/apps/exactly/common/exactly.fixed-borrow.token-fetcher.ts, src/apps/exactly/common/exactly.fixed-deposit.token-fetcher.ts, src/apps/spice-finance/ethereum/spice-finance.weth.token-fetcher.ts, src/apps/synthetix/common/synthetix.snx.token-fetcher.ts
Working on simplifying the balances system for app tokens. Remove overrides for getBalancePerToken. Disabled Exactly since the implementation doesn't conform with `balanceOf` for tokens.
=> feat(studio): Remove overrides on getBalancePerToken

src/multicall/impl/multicall.ethers.ts, src/multicall/impl/multicall.viem.ts, src/multicall/multicall.types.ts
New Ethers versions create types as `PromiseOrValue`, but we just need the call struct as values.
=> fix(studio): Fix multicall call struct types

src/apps/pool-together-v3/common/pool-together-v3.community-ticket.token-fetcher.ts, src/apps/pool-together-v3/common/pool-together-v3.log-provider.ts
BigInt is non-serializable (DUMB?). Instead, only cache the part of the logs that is required (which happens to be serializable already).
=> fix(studio): Fix PoolTogether community pool fetcher

src/app-toolkit/app-toolkit.interface.ts, src/app-toolkit/app-toolkit.service.ts
`getAppTokenPositionsFromDatabase` is a duplicate of `getAppContractPositions`
=> fix(app-toolkit): Remove duplicate function

src/apps/midas/binance-smart-chain/midas.market.token-fetcher.ts, src/apps/midas/common/midas.market.token-fetcher.ts, src/apps/midas/polygon/midas.market.token-fetcher.ts
Midas lens addresses were incorrect. Also, the request for `getPoolAssetsWithData` fails for some comptrollers, so catch and handle the error by filtering out those markets.
=> feat(studio): Fix Midas revert error

src/apps/kyberswap-elastic/common/kyberswap-elastic.apy.data-loader.ts, src/apps/market-xyz/common/market-xyz.supply.token-fetcher.ts, src/apps/rari-fuse/common/rari-fuse.supply.token-fetcher.ts, src/apps/rari-fuse/ethereum/rari-fuse.borrow.contract-position-fetcher.ts, src/apps/rari-fuse/ethereum/rari-fuse.supply.token-fetcher.ts, src/apps/spice-finance/ethereum/spice-finance.weth.token-fetcher.ts, src/apps/synthetix/common/synthetix.snx.token-fetcher.ts, src/apps/uniswap-v2/ethereum/uniswap-v2.pool.token-fetcher.ts
These were removed while attempting to resolve Ethers memory spike problems in the balance calculations, but since migrating to Viem, this pattern can be reintroduced.
=> feat(studio): Revert removal of overrides for get raw balances and get balance per token

src/apps/abracadabra/arbitrum/abracadabra.arbitrum.constants.ts
Add support for Abracadabra's GM cauldrons. I have not been able to test it as I am unable to run `pnpm install` in the project. The changes should be pretty straightforward though.
**gmARB**: `0x972b0f9cde1266e860e546ac92e783741769400f`
**gmBTC**: `0x93652ae25d0ba757c3c92a4deb0b05dd1d4efe35`
**gmETH**: `0xd0f1258563a9d14fb746059246e11ef02632a5f6`
**gmSOL**: `0xf2df969f59b2c86e4b230da88918cdebcfc4ccbc`
=> feat(abracadabra): Add support for GM cauldrons on Arbitrum

src/apps/pickle/common/pickle.jar.token-fetcher.ts
There's one jar on ethereum without a `getRatio()` method on the contract
=> fix(pickle): Fix Jars without getRatio method

src/apps/dhedge-v2/common/dhedge-v2.staking.contract-position-fetcher.ts
=> fix(dhedge-v2): Early return if position has been unstaked

src/apps/gearbox/ethereum/gearbox.lending-v3.token-fetcher.ts
=> fix(gearbox): Fix lending token v3 liquidity and pricePerShare

src/apps/maker/ethereum/maker.vault.contract-position-fetcher.ts
debt balance = art (amount) * ilk rate
=> fix(maker): Update vault debt balances to account for the ilk rate

src/apps/shapeshift/ethereum/shapeshift.farm.contract-position-fetcher.ts
- Updates ShapeShift's Fox Farms up to v8.
- Marks inactive farms as such (up to v7).
http://localhost:5001/apps/shapeshift/positions?groupIds[]=farm
=> fix(shapeshift): update fox farms

src/apps/curve/common/curve.child-liquidity-gauge.contract-position-fetcher.ts, src/apps/curve/common/curve.pool-gauge.contract-position-fetcher.ts, src/apps/hidden-hand/common/hidden-hand.rewards-resolver.ts, src/apps/hidden-hand/common/hidden-hand.rewards.contract-position-fetcher.ts, src/apps/inverse-firm/ethereum/inverse-firm.loan.contract-position-fetcher.ts, src/apps/mean-finance/common/mean-finance.dca-position.contract-position-fetcher.ts, src/apps/pool-together-v4/common/pool-together-v4.api.prize-pool-registry.ts, src/apps/spool/ethereum/spool.vault.contract-position-fetcher.ts
=> chore(apps): Linting
